import type { Flashcard } from "./types";

// Original study flashcards. Types: "task" (purpose recall), "io" (input/output maps),
// "technique" (name→purpose), "concept" (cross-cutting BABOK concepts).
export const flashcards: Flashcard[] = [
  // ─────────── Concepts (cross-cutting) ───────────
  {
    id: "FC-CONCEPT-baccm",
    kaId: "BAPM",
    type: "concept",
    front: "Name the 6 BACCM core concepts.",
    back: "Change, Need, Solution, Stakeholder, Value, Context. (Business Analysis Core Concept Model — all six are interrelated and equally necessary.)",
  },
  {
    id: "FC-CONCEPT-six-kas",
    kaId: "BAPM",
    type: "concept",
    front: "Name the 6 BABOK knowledge areas.",
    back: "Business Analysis Planning & Monitoring; Elicitation & Collaboration; Requirements Life Cycle Management; Strategy Analysis; Requirements Analysis & Design Definition; Solution Evaluation.",
  },
  {
    id: "FC-CONCEPT-req-types",
    kaId: "RADD",
    type: "concept",
    front: "What are the 4 requirement classification types in BABOK?",
    back: "Business requirements, Stakeholder requirements, Solution requirements (functional + non-functional), and Transition requirements.",
  },
  {
    id: "FC-CONCEPT-transition-req",
    kaId: "RADD",
    type: "concept",
    front: "What are transition requirements?",
    back: "Temporary capabilities needed to move from the current to the future state (e.g. data conversion, training, parallel running). They cease to be needed once transition is complete.",
  },
  {
    id: "FC-CONCEPT-verify-vs-validate",
    kaId: "RADD",
    type: "concept",
    front: "Verify vs. Validate requirements — what's the difference?",
    back: "Verify = building the requirements RIGHT (quality: clear, complete, consistent, testable). Validate = building the RIGHT requirements (they deliver value and align to business objectives).",
  },
  {
    id: "FC-CONCEPT-req-vs-design",
    kaId: "RADD",
    type: "concept",
    front: "Requirement vs. Design — what distinguishes them?",
    back: "A requirement is a usable representation of a NEED (focus on the problem); a design is a usable representation of a SOLUTION (focus on the how). The boundary is contextual and they elaborate iteratively.",
  },
  {
    id: "FC-CONCEPT-quality-characteristics",
    kaId: "RADD",
    type: "concept",
    front: "List the quality characteristics of requirements/designs (verification).",
    back: "Atomic, Complete, Consistent, Concise, Feasible, Unambiguous, Testable, Prioritized, Understandable.",
  },
  {
    id: "FC-CONCEPT-risk-responses",
    kaId: "SA",
    type: "concept",
    front: "What are the risk response strategies?",
    back: "For threats: Avoid, Transfer, Mitigate, Accept. For opportunities: Increase (exploit/enhance). Acceptance can be active (contingency) or passive.",
  },
  {
    id: "FC-CONCEPT-risk-tolerance",
    kaId: "SA",
    type: "concept",
    front: "Name the three risk tolerance levels.",
    back: "Risk-averse (avoids uncertainty), Risk-neutral (balances), and Risk-seeking (accepts more uncertainty for potential reward).",
  },
  {
    id: "FC-CONCEPT-moscow",
    kaId: "RLCM",
    type: "concept",
    front: "What does MoSCoW prioritization stand for?",
    back: "Must have, Should have, Could have, Won't have (this time). A grouping-based prioritization approach.",
  },
  {
    id: "FC-CONCEPT-prioritization-bases",
    kaId: "RLCM",
    type: "concept",
    front: "On what bases can requirements be prioritized?",
    back: "Benefit, Penalty, Cost, Risk, Dependencies, Time sensitivity, Stability, and Regulatory/policy compliance.",
  },
  {
    id: "FC-CONCEPT-trace-relationships",
    kaId: "RLCM",
    type: "concept",
    front: "Name the requirement traceability relationship types.",
    back: "Derive, Depends (necessity or effort), Satisfy, and Validate.",
  },
  {
    id: "FC-CONCEPT-elicitation-types",
    kaId: "EC",
    type: "concept",
    front: "What are the three broad types of elicitation?",
    back: "Collaborative (interviews, workshops), Research (document analysis, benchmarking), and Experiments (observation, prototyping, surveys).",
  },
  {
    id: "FC-CONCEPT-design-approaches",
    kaId: "RADD",
    type: "concept",
    front: "What are the solution approaches when defining design options?",
    back: "Create (build new), Purchase (buy/COTS), or a Combination of both. Each allocates requirements across components differently.",
  },
  {
    id: "FC-CONCEPT-future-state-objectives",
    kaId: "SA",
    type: "concept",
    front: "What quality should future-state business objectives have?",
    back: "They should be SMART — Specific, Measurable, Achievable, Relevant, Time-bounded.",
  },
  {
    id: "FC-CONCEPT-solution-vs-enterprise-limitation",
    kaId: "SE",
    type: "concept",
    front: "Solution limitation vs. Enterprise limitation?",
    back: "Solution limitation = factors INSIDE the solution restricting value (defects, design). Enterprise limitation = factors OUTSIDE the solution (culture, structure, processes, adoption).",
  },
  {
    id: "FC-CONCEPT-se-recommendations",
    kaId: "SE",
    type: "concept",
    front: "What recommendation options exist to increase solution value (SE-5)?",
    back: "Do nothing, organizational change, reduce complexity, eliminate redundancy, avoid waste, identify additional capabilities, or retire the solution.",
  },
  {
    id: "FC-CONCEPT-design-thinking-value",
    kaId: "BAPM",
    type: "concept",
    front: "How does BABOK define 'value'?",
    back: "The worth, importance, or usefulness of something to a stakeholder in a context. It can be tangible or intangible, and potential or actual.",
  },

  // ─────────── BAPM task purposes & IO ───────────
  { id: "FC-BAPM-1-purpose", kaId: "BAPM", type: "task", front: "Purpose of 'Plan Business Analysis Approach'?", back: "Define an appropriate method to conduct BA activities — how formal, detailed, and predictive vs. adaptive the work will be." },
  { id: "FC-BAPM-2-purpose", kaId: "BAPM", type: "task", front: "Purpose of 'Plan Stakeholder Engagement'?", back: "Plan an approach for establishing and maintaining effective working relationships with stakeholders (analysis + collaboration + communication)." },
  { id: "FC-BAPM-3-purpose", kaId: "BAPM", type: "task", front: "Purpose of 'Plan Business Analysis Governance'?", back: "Define how decisions are made about requirements/designs: decision making, change control, prioritization, and approvals." },
  { id: "FC-BAPM-4-purpose", kaId: "BAPM", type: "task", front: "Purpose of 'Plan Business Analysis Information Management'?", back: "Define how BA information is stored, accessed, organized, traced, and reused." },
  { id: "FC-BAPM-5-purpose", kaId: "BAPM", type: "task", front: "Purpose of 'Identify Business Analysis Performance Improvements'?", back: "Assess BA work against performance objectives and plan improvements; output is the Business Analysis Performance Assessment." },
  { id: "FC-BAPM-1-io", kaId: "BAPM", type: "io", front: "Inputs and output of 'Plan Business Analysis Approach'?", back: "Input: Needs. Output: Business Analysis Approach." },
  { id: "FC-BAPM-2-io", kaId: "BAPM", type: "io", front: "Output of 'Plan Stakeholder Engagement'?", back: "Stakeholder Engagement Approach (inputs: Needs, Business Analysis Approach)." },

  // ─────────── EC task purposes & IO ───────────
  { id: "FC-EC-1-purpose", kaId: "EC", type: "task", front: "Purpose of 'Prepare for Elicitation'?", back: "Understand the scope of the elicitation activity, select techniques, and plan logistics. Output: Elicitation Activity Plan." },
  { id: "FC-EC-2-purpose", kaId: "EC", type: "task", front: "Purpose of 'Conduct Elicitation'?", back: "Draw out, explore, and identify information relevant to the change. Output: Elicitation Results (unconfirmed)." },
  { id: "FC-EC-3-purpose", kaId: "EC", type: "task", front: "Purpose of 'Confirm Elicitation Results'?", back: "Check gathered information for accuracy and consistency against sources. Output: Elicitation Results (confirmed)." },
  { id: "FC-EC-4-purpose", kaId: "EC", type: "task", front: "Purpose of 'Communicate Business Analysis Information'?", back: "Ensure stakeholders share a common understanding of BA information (the right package, in the right form, for the audience)." },
  { id: "FC-EC-5-purpose", kaId: "EC", type: "task", front: "Purpose of 'Manage Stakeholder Collaboration'?", back: "Encourage stakeholders to work toward a common goal; manage commitments, attitudes, and trust — ongoing throughout." },
  { id: "FC-EC-2-io", kaId: "EC", type: "io", front: "Input and output of 'Conduct Elicitation'?", back: "Input: Elicitation Activity Plan. Output: Elicitation Results (unconfirmed)." },
  { id: "FC-EC-3-io", kaId: "EC", type: "io", front: "Input and output of 'Confirm Elicitation Results'?", back: "Input: Elicitation Results (unconfirmed). Output: Elicitation Results (confirmed)." },

  // ─────────── RLCM task purposes & IO ───────────
  { id: "FC-RLCM-1-purpose", kaId: "RLCM", type: "task", front: "Purpose of 'Trace Requirements'?", back: "Ensure requirements and designs at different levels are aligned, and enable management of the effects of change (impact analysis, coverage)." },
  { id: "FC-RLCM-2-purpose", kaId: "RLCM", type: "task", front: "Purpose of 'Maintain Requirements'?", back: "Retain requirement accuracy and consistency throughout and beyond the change so they can be reused." },
  { id: "FC-RLCM-3-purpose", kaId: "RLCM", type: "task", front: "Purpose of 'Prioritize Requirements'?", back: "Rank requirements in order of relative importance; continual, not one-time." },
  { id: "FC-RLCM-4-purpose", kaId: "RLCM", type: "task", front: "Purpose of 'Assess Requirements Changes'?", back: "Evaluate proposed changes for benefit, cost, impact, schedule, and urgency before accepting them." },
  { id: "FC-RLCM-5-purpose", kaId: "RLCM", type: "task", front: "Purpose of 'Approve Requirements'?", back: "Obtain agreement on and approval of requirements/designs so BA work can continue (per the governance approach)." },
  { id: "FC-RLCM-4-io", kaId: "RLCM", type: "io", front: "Inputs of 'Assess Requirements Changes'?", back: "Requirements, Designs, and a Proposed Change. Outputs: Requirements Change Assessment, Designs Change Assessment." },
  { id: "FC-RLCM-5-io", kaId: "RLCM", type: "io", front: "Input that distinguishes 'Approve Requirements'?", back: "Requirements (VERIFIED) — approval follows verification. Output: Requirements (approved)." },

  // ─────────── SA task purposes & IO ───────────
  { id: "FC-SA-1-purpose", kaId: "SA", type: "task", front: "Purpose of 'Analyze Current State'?", back: "Understand why the enterprise needs to change and what would be affected — establishing the baseline. Outputs: Current State Description, Business Requirements." },
  { id: "FC-SA-2-purpose", kaId: "SA", type: "task", front: "Purpose of 'Define Future State'?", back: "Determine the necessary conditions to meet the business need. Outputs: Business Objectives, Future State Description, Potential Value." },
  { id: "FC-SA-3-purpose", kaId: "SA", type: "task", front: "Purpose of 'Assess Risks'?", back: "Understand undesirable consequences of forces during transition to / in the future state. Output: Risk Analysis Results." },
  { id: "FC-SA-4-purpose", kaId: "SA", type: "task", front: "Purpose of 'Define Change Strategy'?", back: "Develop, assess, and select an approach to the change (via gap analysis). Outputs: Change Strategy, Solution Scope." },
  { id: "FC-SA-1-io", kaId: "SA", type: "io", front: "Inputs and outputs of 'Analyze Current State'?", back: "Inputs: Elicitation Results (confirmed), Needs. Outputs: Current State Description, Business Requirements." },
  { id: "FC-SA-2-io", kaId: "SA", type: "io", front: "Outputs of 'Define Future State'?", back: "Business Objectives, Future State Description, and Potential Value." },
  { id: "FC-SA-4-io", kaId: "SA", type: "io", front: "Outputs of 'Define Change Strategy'?", back: "Change Strategy and Solution Scope." },

  // ─────────── RADD task purposes & IO ───────────
  { id: "FC-RADD-1-purpose", kaId: "RADD", type: "task", front: "Purpose of 'Specify and Model Requirements'?", back: "Analyze, synthesize, and refine elicitation results into structured requirements and designs (models, attributes, abstraction)." },
  { id: "FC-RADD-2-purpose", kaId: "RADD", type: "task", front: "Purpose of 'Verify Requirements'?", back: "Ensure specifications/models meet quality standards and are usable — building the requirements RIGHT." },
  { id: "FC-RADD-3-purpose", kaId: "RADD", type: "task", front: "Purpose of 'Validate Requirements'?", back: "Ensure requirements/designs align to business requirements and support needed value — building the RIGHT requirements." },
  { id: "FC-RADD-4-purpose", kaId: "RADD", type: "task", front: "Purpose of 'Define Requirements Architecture'?", back: "Structure all requirements/designs (viewpoints and views) so they work together and serve the business purpose." },
  { id: "FC-RADD-5-purpose", kaId: "RADD", type: "task", front: "Purpose of 'Define Design Options'?", back: "Define solution approaches, identify improvement opportunities, allocate requirements, and describe design options." },
  { id: "FC-RADD-6-purpose", kaId: "RADD", type: "task", front: "Purpose of 'Analyze Potential Value and Recommend Solution'?", back: "Estimate potential value of each design option and recommend the most appropriate. Output: Solution Recommendation." },
  { id: "FC-RADD-5-io", kaId: "RADD", type: "io", front: "Inputs of 'Define Design Options'?", back: "Change Strategy, Requirements (validated, prioritized), Requirements Architecture. Output: Design Options." },
  { id: "FC-RADD-6-io", kaId: "RADD", type: "io", front: "Inputs and output of 'Analyze Potential Value and Recommend Solution'?", back: "Inputs: Potential Value, Design Options. Output: Solution Recommendation." },

  // ─────────── SE task purposes & IO ───────────
  { id: "FC-SE-1-purpose", kaId: "SE", type: "task", front: "Purpose of 'Measure Solution Performance'?", back: "Define performance measures and collect data to evaluate the solution's effectiveness vs. the value it brings." },
  { id: "FC-SE-2-purpose", kaId: "SE", type: "task", front: "Purpose of 'Analyze Performance Measures'?", back: "Provide insight into solution performance relative to potential value (trends, variances, risks)." },
  { id: "FC-SE-3-purpose", kaId: "SE", type: "task", front: "Purpose of 'Assess Solution Limitations'?", back: "Determine factors INTERNAL to the solution restricting value realization. Output: Solution Limitation." },
  { id: "FC-SE-4-purpose", kaId: "SE", type: "task", front: "Purpose of 'Assess Enterprise Limitations'?", back: "Determine factors EXTERNAL to the solution (the enterprise) restricting value. Output: Enterprise Limitation." },
  { id: "FC-SE-5-purpose", kaId: "SE", type: "task", front: "Purpose of 'Recommend Actions to Increase Solution Value'?", back: "Understand gaps between potential and actual value and recommend a course of action. Output: Recommended Actions." },
  { id: "FC-SE-3-io", kaId: "SE", type: "io", front: "Inputs of 'Assess Solution Limitations'?", back: "Implemented Solution (External) and Solution Performance Analysis. Output: Solution Limitation." },
  { id: "FC-SE-5-io", kaId: "SE", type: "io", front: "Inputs of 'Recommend Actions to Increase Solution Value'?", back: "Enterprise Limitation and Solution Limitation. Output: Recommended Actions." },

  // ─────────── Techniques ───────────
  { id: "FC-TECH-document-analysis", kaId: "EC", type: "technique", front: "Technique: Document Analysis — purpose?", back: "Elicit information by examining existing materials/documentation (a research-style technique for current-state info)." },
  { id: "FC-TECH-interviews", kaId: "EC", type: "technique", front: "Technique: Interviews — purpose?", back: "Elicit information from a person/group via a directed conversation (structured or unstructured)." },
  { id: "FC-TECH-workshops", kaId: "EC", type: "technique", front: "Technique: Workshops — purpose?", back: "A focused, facilitated group session (facilitator + scribe) to elicit, refine, or reach agreement quickly." },
  { id: "FC-TECH-observation", kaId: "EC", type: "technique", front: "Technique: Observation — purpose?", back: "Elicit information by viewing activities in their environment (passive or active/participatory); captures tacit knowledge." },
  { id: "FC-TECH-prototyping", kaId: "RADD", type: "technique", front: "Technique: Prototyping — purpose?", back: "Elicit/validate needs via an early working model (throwaway or evolutionary); makes requirements concrete." },
  { id: "FC-TECH-root-cause", kaId: "SA", type: "technique", front: "Technique: Root Cause Analysis — purpose?", back: "Identify the underlying causes of a problem (fishbone/Ishikawa, five whys); separate causes from symptoms." },
  { id: "FC-TECH-swot", kaId: "SA", type: "technique", front: "Technique: SWOT Analysis — purpose?", back: "Evaluate Strengths, Weaknesses (internal) and Opportunities, Threats (external) relevant to a change." },
  { id: "FC-TECH-decision-analysis", kaId: "RADD", type: "technique", front: "Technique: Decision Analysis — purpose?", back: "Assess a problem and alternatives under uncertainty using decision tables/trees, weighted scoring, expected value." },
  { id: "FC-TECH-financial-analysis", kaId: "RADD", type: "technique", front: "Technique: Financial Analysis — purpose?", back: "Understand financial aspects: ROI, NPV, IRR, payback period — to compare options on financial value." },
  { id: "FC-TECH-mfr-vs-nfr", kaId: "RADD", type: "technique", front: "Technique: Non-Functional Requirements Analysis — what does it capture?", back: "Quality attributes — performance, security, usability, reliability, maintainability ('how well', not 'what')." },
  { id: "FC-TECH-business-rules", kaId: "RLCM", type: "technique", front: "Technique: Business Rules Analysis — key distinction?", back: "Definitional rules (structure) vs. behavioral rules (conduct); keep rules atomic, declarative, implementation-independent." },
  { id: "FC-TECH-stakeholder-map", kaId: "BAPM", type: "technique", front: "Technique: Stakeholder List, Map, or Personas — purpose?", back: "Identify stakeholders and analyze influence/interest (RACI, onion diagram, personas) to plan engagement." },
  { id: "FC-TECH-acceptance-criteria", kaId: "RLCM", type: "technique", front: "Acceptance vs. evaluation criteria?", back: "Acceptance = pass/fail conditions (must be met). Evaluation = criteria allowing comparison/ranking among options." },
  { id: "FC-TECH-estimation", kaId: "BAPM", type: "technique", front: "Technique: Estimation — common approaches?", back: "Analogous, parametric, three-point (PERT), and rolling-wave (refined as more is known)." },
];
