import type { Question } from "./types";

// Original CBAP-style practice questions. Study-grade, not real exam items.
// Answers reflect BABOK v3 reasoning (the "single source of truth" mindset).
export const questions: Question[] = [
  // ─────────────── BAPM ───────────────
  {
    id: "Q-BAPM-001",
    kaId: "BAPM",
    taskId: "BAPM-1",
    stem: "An organization mandates fixed, signed-off requirements before any build begins. Which planning approach does this most align with?",
    options: ["Adaptive", "Predictive", "Hybrid by default", "Exploratory"],
    correctIndex: 1,
    explanation: "A predictive approach favors up-front, formally controlled requirements; adaptive favors progressive elaboration and frequent change.",
    difficulty: "easy",
  },
  {
    id: "Q-BAPM-002",
    kaId: "BAPM",
    taskId: "BAPM-2",
    stem: "Which artifact is the primary output of Plan Stakeholder Engagement?",
    options: ["Governance Approach", "Stakeholder Engagement Approach", "Business Analysis Approach", "Information Management Approach"],
    correctIndex: 1,
    explanation: "Plan Stakeholder Engagement produces the Stakeholder Engagement Approach (stakeholder analysis, collaboration, and communication needs).",
    difficulty: "easy",
  },
  {
    id: "Q-BAPM-003",
    kaId: "BAPM",
    taskId: "BAPM-2",
    caseStudyId: "CS-001",
    stem: "At MeridianBank, branch staff fear losing relevance while the sponsor pushes speed. Which BABOK activity best addresses managing these differing positions up front?",
    options: ["Define Change Strategy", "Plan Stakeholder Engagement", "Measure Solution Performance", "Specify and Model Requirements"],
    correctIndex: 1,
    explanation: "Understanding influence/attitude and planning how to collaborate with conflicting stakeholders is the purpose of Plan Stakeholder Engagement.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-004",
    kaId: "BAPM",
    taskId: "BAPM-3",
    stem: "Defining who can approve requirements, how changes are controlled, and how prioritization happens is the purpose of which task?",
    options: ["Plan Business Analysis Approach", "Plan Business Analysis Governance", "Plan Business Analysis Information Management", "Plan Stakeholder Engagement"],
    correctIndex: 1,
    explanation: "Plan Business Analysis Governance defines decision making, change control, prioritization, and approvals.",
    difficulty: "easy",
  },
  {
    id: "Q-BAPM-005",
    kaId: "BAPM",
    taskId: "BAPM-4",
    stem: "Deciding how business analysis information will be traced, stored, and reused after the project is covered by:",
    options: ["Plan Business Analysis Information Management", "Maintain Requirements", "Trace Requirements", "Plan Business Analysis Governance"],
    correctIndex: 0,
    explanation: "Plan Business Analysis Information Management plans organization, traceability, storage/access, attributes, and reuse of BA information.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-006",
    kaId: "BAPM",
    taskId: "BAPM-5",
    stem: "The output of Identify Business Analysis Performance Improvements is:",
    options: ["Business Analysis Approach", "Performance Objectives", "Business Analysis Performance Assessment", "Governance Approach"],
    correctIndex: 2,
    explanation: "The task assesses BA work against performance objectives and produces the Business Analysis Performance Assessment, feeding back into the approach.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-007",
    kaId: "BAPM",
    taskId: "BAPM-1",
    stem: "Which is the single input to Plan Business Analysis Approach?",
    options: ["Needs", "Elicitation Results", "Solution Scope", "Requirements"],
    correctIndex: 0,
    explanation: "Needs is the only listed input; the approach is shaped early, before most other BA information exists.",
    difficulty: "easy",
  },
  {
    id: "Q-BAPM-008",
    kaId: "BAPM",
    taskId: "BAPM-3",
    stem: "A change request arrives. Which planning output should already define the path it follows to a decision?",
    options: ["Information Management Approach", "Governance Approach", "Stakeholder Engagement Approach", "Future State Description"],
    correctIndex: 1,
    explanation: "The Governance Approach defines the change control process and who decides — established during planning so changes don't stall later.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-009",
    kaId: "BAPM",
    taskId: "BAPM-2",
    stem: "Which technique is most directly used to analyze stakeholder influence and interest?",
    options: ["Data Modelling", "Stakeholder List, Map, or Personas", "Process Modelling", "Financial Analysis"],
    correctIndex: 1,
    explanation: "Stakeholder List, Map, or Personas (e.g. RACI, onion diagram) analyzes who is affected and their influence/attitude.",
    difficulty: "easy",
  },
  {
    id: "Q-BAPM-010",
    kaId: "BAPM",
    taskId: "BAPM-1",
    stem: "In BABOK, the level of formality and detail of BA work products is primarily decided in which task?",
    options: ["Plan Business Analysis Approach", "Approve Requirements", "Verify Requirements", "Conduct Elicitation"],
    correctIndex: 0,
    explanation: "Formality and level of detail are elements of Plan Business Analysis Approach.",
    difficulty: "easy",
  },

  // ─────────────── EC ───────────────
  {
    id: "Q-EC-001",
    kaId: "EC",
    taskId: "EC-1",
    stem: "Selecting elicitation techniques and arranging logistics happens in which task?",
    options: ["Conduct Elicitation", "Prepare for Elicitation", "Confirm Elicitation Results", "Communicate Business Analysis Information"],
    correctIndex: 1,
    explanation: "Prepare for Elicitation scopes the activity, selects techniques, and sets up logistics and materials.",
    difficulty: "easy",
  },
  {
    id: "Q-EC-002",
    kaId: "EC",
    taskId: "EC-2",
    caseStudyId: "CS-001",
    stem: "MeridianBank's onboarding process is undocumented and varies by branch. Which elicitation technique best captures how staff actually perform it today?",
    options: ["Survey via email", "Observation (job shadowing)", "Document analysis", "Prototyping"],
    correctIndex: 1,
    explanation: "Observation captures tacit, real-world process knowledge that isn't documented and that staff may not fully articulate.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-003",
    kaId: "EC",
    taskId: "EC-3",
    stem: "Checking captured elicitation results against their sources for accuracy and consistency is:",
    options: ["Verify Requirements", "Validate Requirements", "Confirm Elicitation Results", "Approve Requirements"],
    correctIndex: 2,
    explanation: "Confirm Elicitation Results checks the captured information against sources — distinct from RADD verification/validation.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-004",
    kaId: "EC",
    taskId: "EC-2",
    stem: "Interviews and workshops are examples of which elicitation approach?",
    options: ["Experiments", "Research", "Collaborative", "Observational"],
    correctIndex: 2,
    explanation: "Collaborative elicitation works directly with stakeholders; research uses existing materials; experiments include observation/prototyping/surveys.",
    difficulty: "easy",
  },
  {
    id: "Q-EC-005",
    kaId: "EC",
    taskId: "EC-2",
    stem: "What is the output of Conduct Elicitation?",
    options: ["Elicitation Activity Plan", "Elicitation Results (unconfirmed)", "Elicitation Results (confirmed)", "Requirements (specified and modeled)"],
    correctIndex: 1,
    explanation: "Conduct Elicitation yields unconfirmed results; they become confirmed only after Confirm Elicitation Results.",
    difficulty: "easy",
  },
  {
    id: "Q-EC-006",
    kaId: "EC",
    taskId: "EC-4",
    stem: "Communicate Business Analysis Information is fundamentally about:",
    options: ["Transmitting documents on schedule", "Achieving a shared understanding among stakeholders", "Getting formal sign-off", "Storing requirements for reuse"],
    correctIndex: 1,
    explanation: "The task ensures stakeholders have a common understanding — not mere transmission of documents.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-007",
    kaId: "EC",
    taskId: "EC-5",
    stem: "Why is Manage Stakeholder Collaboration considered ongoing rather than a one-time task?",
    options: ["Approvals must be re-signed weekly", "Stakeholder commitment, attitudes, and trust must be maintained throughout", "Requirements always change", "It is a governance requirement"],
    correctIndex: 1,
    explanation: "Collaboration is continuous work to keep stakeholders engaged and committed across the initiative.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-008",
    kaId: "EC",
    taskId: "EC-1",
    stem: "Which pair are inputs to Prepare for Elicitation?",
    options: ["Needs and Stakeholder Engagement Approach", "Requirements and Designs", "Solution Scope and Change Strategy", "Business Objectives and Potential Value"],
    correctIndex: 0,
    explanation: "Prepare for Elicitation takes Needs and the Stakeholder Engagement Approach as inputs.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-009",
    kaId: "EC",
    taskId: "EC-2",
    stem: "A survey/questionnaire is most appropriate when the BA needs:",
    options: ["Deep, nuanced understanding from one expert", "Input from many people at low cost", "To observe a process in action", "To reach consensus in a room"],
    correctIndex: 1,
    explanation: "Surveys reach many respondents cheaply and yield breadth/quantitative data, at the cost of depth.",
    difficulty: "easy",
  },
  {
    id: "Q-EC-010",
    kaId: "EC",
    taskId: "EC-3",
    stem: "Confirming elicitation results primarily reduces the cost of:",
    options: ["Stakeholder onboarding", "Errors discovered late in the life cycle", "Tooling licenses", "Governance overhead"],
    correctIndex: 1,
    explanation: "Catching inaccurate or inconsistent captured information early is far cheaper than fixing it after design/build.",
    difficulty: "medium",
  },

  // ─────────────── RLCM ───────────────
  {
    id: "Q-RLCM-001",
    kaId: "RLCM",
    taskId: "RLCM-1",
    stem: "Which capability does Trace Requirements primarily enable?",
    options: ["Stakeholder analysis", "Impact analysis and coverage", "Elicitation preparation", "Value measurement"],
    correctIndex: 1,
    explanation: "Traceability links requirements to one another, to designs, and to objectives, enabling impact analysis and coverage checks.",
    difficulty: "easy",
  },
  {
    id: "Q-RLCM-002",
    kaId: "RLCM",
    taskId: "RLCM-4",
    caseStudyId: "CS-002",
    stem: "At Northwind, change requests arrive weekly. Before accepting one, the BA should evaluate it for benefit, cost, impact, schedule, and urgency. Which task is this?",
    options: ["Prioritize Requirements", "Assess Requirements Changes", "Maintain Requirements", "Approve Requirements"],
    correctIndex: 1,
    explanation: "Assess Requirements Changes performs impact analysis (benefit, cost, impact, schedule, urgency) on a proposed change.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-003",
    kaId: "RLCM",
    taskId: "RLCM-3",
    stem: "Which is NOT a typical basis for prioritizing requirements in BABOK?",
    options: ["Risk", "Dependencies", "Alphabetical order", "Regulatory compliance"],
    correctIndex: 2,
    explanation: "Bases include benefit, penalty, cost, risk, dependencies, time sensitivity, stability, and regulatory/policy — not alphabetical order.",
    difficulty: "easy",
  },
  {
    id: "Q-RLCM-004",
    kaId: "RLCM",
    taskId: "RLCM-2",
    stem: "Keeping a business rule accurate so it can be reused after the project ends is the purpose of:",
    options: ["Trace Requirements", "Maintain Requirements", "Approve Requirements", "Validate Requirements"],
    correctIndex: 1,
    explanation: "Maintain Requirements retains accuracy/consistency so requirements remain valuable, reusable assets.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-005",
    kaId: "RLCM",
    taskId: "RLCM-5",
    stem: "Which input distinguishes Approve Requirements from the other RLCM tasks?",
    options: ["Proposed Change", "Requirements (verified)", "Needs", "Elicitation Results"],
    correctIndex: 1,
    explanation: "Approve Requirements takes verified requirements as input — approval follows verification.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-006",
    kaId: "RLCM",
    taskId: "RLCM-1",
    stem: "'Requirement A cannot be implemented unless Requirement B is also implemented.' This is which traceability relationship?",
    options: ["Satisfy", "Validate", "Depends", "Derive"],
    correctIndex: 2,
    explanation: "A Depends relationship captures necessity or effort dependencies between requirements.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-007",
    kaId: "RLCM",
    taskId: "RLCM-3",
    caseStudyId: "CS-002",
    stem: "With a fixed go-live date and conflicting requirements, Northwind's BA must continually rank what gets built first. This is:",
    options: ["Maintain Requirements", "Prioritize Requirements", "Trace Requirements", "Verify Requirements"],
    correctIndex: 1,
    explanation: "Prioritize Requirements ranks relative importance and is continual — essential under fixed time constraints.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-008",
    kaId: "RLCM",
    taskId: "RLCM-4",
    stem: "Effective impact analysis of a proposed change depends most directly on having:",
    options: ["A signed business case", "Good requirements traceability", "A completed mock exam", "Vendor assessments"],
    correctIndex: 1,
    explanation: "Traceability (RLCM-1) reveals what a change touches, which is the foundation of impact analysis.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-009",
    kaId: "RLCM",
    taskId: "RLCM-5",
    stem: "Who may approve requirements is determined by:",
    options: ["The Information Management Approach", "The Governance Approach", "The Change Strategy", "The Solution Scope"],
    correctIndex: 1,
    explanation: "The Governance Approach defines decision authority and the approval process.",
    difficulty: "easy",
  },
  {
    id: "Q-RLCM-010",
    kaId: "RLCM",
    taskId: "RLCM-3",
    stem: "In an adaptive (agile) context, prioritization is best described as:",
    options: ["Done once at project start", "Continual, at each iteration", "Handled only by governance", "Unnecessary"],
    correctIndex: 1,
    explanation: "Prioritization is continual; backlogs are re-prioritized frequently as understanding evolves.",
    difficulty: "easy",
  },
  {
    id: "Q-RLCM-011",
    kaId: "RLCM",
    taskId: "RLCM-2",
    stem: "Which requirements are most likely to be maintained for reuse beyond a single initiative?",
    options: ["Transition requirements", "Business rules and non-functional requirements", "Meeting notes", "Status reports"],
    correctIndex: 1,
    explanation: "Stable artifacts like business rules and NFRs often outlive the project and are reused.",
    difficulty: "medium",
  },

  // ─────────────── SA ───────────────
  {
    id: "Q-SA-001",
    kaId: "SA",
    taskId: "SA-1",
    caseStudyId: "CS-001",
    stem: "Before defining MeridianBank's future onboarding, the BA must establish a baseline of how things work today. Which task produces that baseline?",
    options: ["Define Future State", "Analyze Current State", "Define Change Strategy", "Assess Risks"],
    correctIndex: 1,
    explanation: "Analyze Current State establishes the baseline (capabilities, processes, constraints) against which future state and value are judged.",
    difficulty: "easy",
  },
  {
    id: "Q-SA-002",
    kaId: "SA",
    taskId: "SA-2",
    stem: "Which set are outputs of Define Future State?",
    options: ["Current State Description and Business Requirements", "Business Objectives, Future State Description, Potential Value", "Change Strategy and Solution Scope", "Risk Analysis Results"],
    correctIndex: 1,
    explanation: "Define Future State outputs Business Objectives, the Future State Description, and Potential Value.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-003",
    kaId: "SA",
    taskId: "SA-4",
    stem: "Bridging the current and future states through gap analysis and transition planning is the purpose of:",
    options: ["Assess Risks", "Define Change Strategy", "Analyze Current State", "Define Design Options"],
    correctIndex: 1,
    explanation: "Define Change Strategy uses gap analysis to plan how to move from current to future state, producing the Change Strategy and Solution Scope.",
    difficulty: "easy",
  },
  {
    id: "Q-SA-004",
    kaId: "SA",
    taskId: "SA-2",
    stem: "Future-state business objectives are best written to be:",
    options: ["Aspirational and broad", "SMART (specific, measurable, achievable, relevant, time-bounded)", "Technology-specific", "Confidential"],
    correctIndex: 1,
    explanation: "SMART objectives make the future state measurable and testable.",
    difficulty: "easy",
  },
  {
    id: "Q-SA-005",
    kaId: "SA",
    taskId: "SA-3",
    stem: "An organization that prefers to avoid uncertainty even at higher cost is best described as:",
    options: ["Risk-seeking", "Risk-neutral", "Risk-averse", "Risk-ignorant"],
    correctIndex: 2,
    explanation: "Risk-averse stakeholders prioritize avoiding uncertainty; this shapes which risk responses are acceptable.",
    difficulty: "easy",
  },
  {
    id: "Q-SA-006",
    kaId: "SA",
    taskId: "SA-3",
    stem: "Transferring a risk to a third party (e.g. insurance or a vendor contract) is which response strategy?",
    options: ["Avoid", "Transfer", "Mitigate", "Accept"],
    correctIndex: 1,
    explanation: "Transfer shifts the impact/ownership of a risk to another party.",
    difficulty: "easy",
  },
  {
    id: "Q-SA-007",
    kaId: "SA",
    taskId: "SA-1",
    stem: "Which technique helps separate the root cause of a business problem from its symptoms during current-state analysis?",
    options: ["Prototyping", "Root Cause Analysis", "Backlog Management", "User Stories"],
    correctIndex: 1,
    explanation: "Root Cause Analysis (e.g. five whys, fishbone) distinguishes underlying causes from symptoms.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-008",
    kaId: "SA",
    taskId: "SA-4",
    stem: "Solution Scope is an output of which task?",
    options: ["Analyze Current State", "Define Future State", "Define Change Strategy", "Assess Risks"],
    correctIndex: 2,
    explanation: "Define Change Strategy produces both the Change Strategy and the Solution Scope.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-009",
    kaId: "SA",
    taskId: "SA-2",
    caseStudyId: "CS-001",
    stem: "The MeridianBank sponsor wants onboarding under 1 hour. Where does this measurable target most properly belong?",
    options: ["As a business objective in the Future State Description", "As a transition requirement", "As a governance rule", "As a traceability relationship"],
    correctIndex: 0,
    explanation: "A measurable target for the desired end state is a business objective defined when describing the future state.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-010",
    kaId: "SA",
    taskId: "SA-1",
    stem: "Which are the outputs of Analyze Current State?",
    options: ["Business Objectives and Potential Value", "Current State Description and Business Requirements", "Change Strategy and Solution Scope", "Risk Analysis Results and Influences"],
    correctIndex: 1,
    explanation: "Analyze Current State outputs the Current State Description and Business Requirements.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-011",
    kaId: "SA",
    taskId: "SA-4",
    stem: "Defining intermediate transition states and a release plan is part of which task?",
    options: ["Define Change Strategy", "Maintain Requirements", "Verify Requirements", "Measure Solution Performance"],
    correctIndex: 0,
    explanation: "Transition states and release planning are elements of Define Change Strategy.",
    difficulty: "medium",
  },

  // ─────────────── RADD ───────────────
  {
    id: "Q-RADD-001",
    kaId: "RADD",
    taskId: "RADD-2",
    stem: "Confirming that a requirement is atomic, testable, and unambiguous is part of:",
    options: ["Validate Requirements", "Verify Requirements", "Approve Requirements", "Trace Requirements"],
    correctIndex: 1,
    explanation: "Verify Requirements checks quality characteristics — building the requirements right.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-002",
    kaId: "RADD",
    taskId: "RADD-3",
    stem: "Confirming that a requirement actually delivers value and aligns to business objectives is:",
    options: ["Verify Requirements", "Validate Requirements", "Specify and Model Requirements", "Maintain Requirements"],
    correctIndex: 1,
    explanation: "Validate Requirements ensures alignment to business needs and value — building the right requirements.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-003",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "Turning confirmed elicitation results into structured models and specifications is the purpose of:",
    options: ["Specify and Model Requirements", "Define Requirements Architecture", "Define Design Options", "Verify Requirements"],
    correctIndex: 0,
    explanation: "Specify and Model Requirements analyzes and represents requirements/designs at appropriate abstraction.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-004",
    kaId: "RADD",
    taskId: "RADD-5",
    caseStudyId: "CS-002",
    stem: "Northwind must decide between a custom integration and a vendor connector. In BABOK terms, describing and comparing these is part of:",
    options: ["Define Design Options", "Specify and Model Requirements", "Define Requirements Architecture", "Validate Requirements"],
    correctIndex: 0,
    explanation: "Define Design Options describes solution approaches (create vs. purchase vs. combine) and allocates requirements to components.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-005",
    kaId: "RADD",
    taskId: "RADD-6",
    stem: "When recommending a solution among options, the recommendation should be driven primarily by:",
    options: ["Lowest cost", "Highest potential value (benefits net of costs and risk)", "Vendor preference", "Shortest timeline"],
    correctIndex: 1,
    explanation: "Analyze Potential Value and Recommend Solution weighs benefits against costs and risk — value, not cost alone.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-006",
    kaId: "RADD",
    taskId: "RADD-4",
    stem: "Structuring requirements using viewpoints and views so they fit together coherently is:",
    options: ["Define Requirements Architecture", "Trace Requirements", "Prioritize Requirements", "Define Design Options"],
    correctIndex: 0,
    explanation: "Define Requirements Architecture organizes requirements into a coherent whole using viewpoints and views.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-007",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "Performance, security, and usability requirements are classified as:",
    options: ["Business requirements", "Functional requirements", "Non-functional requirements", "Transition requirements"],
    correctIndex: 2,
    explanation: "These quality attributes are non-functional requirements ('how well' rather than 'what').",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-008",
    kaId: "RADD",
    taskId: "RADD-3",
    stem: "Which guideline/input is essential to validate requirements against?",
    options: ["Proposed Change", "Future State Description / Business Objectives", "Elicitation Activity Plan", "Information Management Approach"],
    correctIndex: 1,
    explanation: "Validation checks alignment to business objectives, the future state, and potential value.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-009",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "A 'usable representation of a need' is BABOK's definition of a:",
    options: ["Design", "Requirement", "Stakeholder", "Solution component"],
    correctIndex: 1,
    explanation: "A requirement represents a need; a design represents a solution. The boundary is contextual.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-010",
    kaId: "RADD",
    taskId: "RADD-5",
    stem: "The three broad solution approaches when defining design options are:",
    options: ["Build, test, deploy", "Create, purchase, or a combination", "Plan, do, check", "Avoid, transfer, accept"],
    correctIndex: 1,
    explanation: "Solution approaches are create (build), purchase (buy/COTS), or a combination.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-011",
    kaId: "RADD",
    taskId: "RADD-6",
    stem: "Which pair are the inputs to Analyze Potential Value and Recommend Solution?",
    options: ["Potential Value and Design Options", "Requirements and Designs", "Change Strategy and Solution Scope", "Needs and Elicitation Results"],
    correctIndex: 0,
    explanation: "The task takes Potential Value and Design Options and outputs a Solution Recommendation.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-012",
    kaId: "RADD",
    taskId: "RADD-2",
    stem: "Reviews and checklists are most associated with which RADD task?",
    options: ["Specify and Model Requirements", "Verify Requirements", "Define Design Options", "Define Requirements Architecture"],
    correctIndex: 1,
    explanation: "Verify Requirements uses reviews, checklists, and acceptance/evaluation criteria to confirm quality.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-013",
    kaId: "RADD",
    taskId: "RADD-1",
    caseStudyId: "CS-002",
    stem: "Northwind's warehouse, finance, and logistics stakeholders need different views of the same requirements. Which technique set best serves this in Specify and Model Requirements?",
    options: ["Financial Analysis only", "Models such as process models, data models, and use cases for different viewpoints", "Survey only", "Vendor Assessment"],
    correctIndex: 1,
    explanation: "Different models (process, data, use cases) present requirements from the viewpoints each audience needs.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-014",
    kaId: "RADD",
    taskId: "RADD-4",
    stem: "Which input does Define Requirements Architecture rely on to know how information should be organized and reused?",
    options: ["Information Management Approach", "Risk Analysis Results", "Stakeholder Engagement Approach", "Elicitation Activity Plan"],
    correctIndex: 0,
    explanation: "The Information Management Approach (from BAPM-4) guides how the architecture organizes and relates requirements.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-015",
    kaId: "RADD",
    taskId: "RADD-3",
    stem: "An agile team writes acceptance criteria for each user story. In BABOK this most supports which task?",
    options: ["Validate Requirements", "Trace Requirements", "Plan Business Analysis Governance", "Measure Solution Performance"],
    correctIndex: 0,
    explanation: "Acceptance/evaluation criteria help validate that the requirement delivers the intended value.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-016",
    kaId: "RADD",
    taskId: "RADD-5",
    stem: "Design Options take which validated/prioritized artifact plus the requirements architecture and change strategy as inputs?",
    options: ["Requirements", "Needs", "Solution Performance Measures", "Proposed Change"],
    correctIndex: 0,
    explanation: "Define Design Options takes Change Strategy, Requirements (validated, prioritized), and Requirements Architecture.",
    difficulty: "hard",
  },

  // ─────────────── SE ───────────────
  {
    id: "Q-SE-001",
    kaId: "SE",
    taskId: "SE-1",
    stem: "Defining and collecting measures to evaluate a solution's effectiveness is:",
    options: ["Analyze Performance Measures", "Measure Solution Performance", "Assess Solution Limitations", "Recommend Actions to Increase Solution Value"],
    correctIndex: 1,
    explanation: "Measure Solution Performance defines, validates, and collects performance measures tied to objectives.",
    difficulty: "easy",
  },
  {
    id: "Q-SE-002",
    kaId: "SE",
    taskId: "SE-4",
    caseStudyId: "CS-003",
    stem: "BrightMart's loyalty app works fine, but store staff don't promote it and adoption is low. This shortfall is best classified as a:",
    options: ["Solution limitation", "Enterprise limitation", "Requirements defect", "Traceability gap"],
    correctIndex: 1,
    explanation: "The solution itself functions; the limit is in the enterprise (staff behavior/adoption) — an enterprise limitation.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-003",
    kaId: "SE",
    taskId: "SE-3",
    stem: "A defect inside the deployed solution that caps the value delivered is a:",
    options: ["Enterprise limitation", "Solution limitation", "Business requirement", "Transition requirement"],
    correctIndex: 1,
    explanation: "Factors internal to the solution that restrict value are solution limitations.",
    difficulty: "easy",
  },
  {
    id: "Q-SE-004",
    kaId: "SE",
    taskId: "SE-2",
    stem: "Comparing actual performance against potential value to spot trends and variances is:",
    options: ["Measure Solution Performance", "Analyze Performance Measures", "Assess Enterprise Limitations", "Define Future State"],
    correctIndex: 1,
    explanation: "Analyze Performance Measures interprets the collected data against expected value.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-005",
    kaId: "SE",
    taskId: "SE-3",
    caseStudyId: "CS-003",
    stem: "BrightMart discovers a key promotion rule was never configured in the app. In SE terms this missing configuration is a:",
    options: ["Enterprise limitation", "Solution limitation", "Risk response", "Governance gap"],
    correctIndex: 1,
    explanation: "A missing configuration inside the solution that caps value is a solution limitation.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-006",
    kaId: "SE",
    taskId: "SE-5",
    stem: "Which is a valid recommended action to increase solution value in BABOK?",
    options: ["Ignore the measures", "Retire the solution", "Skip governance", "Remove traceability"],
    correctIndex: 1,
    explanation: "Options include do nothing, organizational change, reduce complexity, eliminate redundancy/waste, add capabilities, or retire the solution.",
    difficulty: "easy",
  },
  {
    id: "Q-SE-007",
    kaId: "SE",
    taskId: "SE-1",
    stem: "Solution performance measures should be tied most closely to:",
    options: ["Vendor SLAs only", "The business objectives / potential value", "The project schedule", "Stakeholder seniority"],
    correctIndex: 1,
    explanation: "Measures should reflect the value/objectives the solution was meant to deliver.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-008",
    kaId: "SE",
    taskId: "SE-5",
    caseStudyId: "CS-003",
    stem: "Given low adoption (enterprise) and a missing rule (solution), what should BrightMart's BA deliver to leadership?",
    options: ["A new Stakeholder Engagement Approach", "Recommended Actions addressing each limitation", "A revised Elicitation Activity Plan", "A traceability matrix"],
    correctIndex: 1,
    explanation: "Recommend Actions to Increase Solution Value ties recommendations to the specific solution and enterprise limitations found.",
    difficulty: "hard",
  },
  {
    id: "Q-SE-009",
    kaId: "SE",
    taskId: "SE-4",
    stem: "Inputs to Assess Enterprise Limitations include the Current State Description and:",
    options: ["Solution Performance Analysis", "Elicitation Activity Plan", "Governance Approach", "Business Analysis Approach"],
    correctIndex: 0,
    explanation: "Assess Enterprise Limitations uses the Current State Description, the Solution Performance Analysis, and the implemented solution.",
    difficulty: "hard",
  },
  {
    id: "Q-SE-010",
    kaId: "SE",
    taskId: "SE-2",
    stem: "The output of Analyze Performance Measures is:",
    options: ["Solution Performance Measures", "Solution Performance Analysis", "Recommended Actions", "Enterprise Limitation"],
    correctIndex: 1,
    explanation: "Analyze Performance Measures produces the Solution Performance Analysis, which feeds the limitation-assessment tasks.",
    difficulty: "medium",
  },
];
