import type { Task } from "./types";

// All 30 BABOK v3 tasks. Inputs/outputs follow the BABOK Guide v3 input/output maps.
// `notes` are original study phrasing (no verbatim BABOK text).
export const tasks: Task[] = [
  // ─── Business Analysis Planning & Monitoring ───
  {
    id: "BAPM-1",
    kaId: "BAPM",
    name: "Plan Business Analysis Approach",
    purpose:
      "Define an appropriate method to conduct business analysis activities for the initiative.",
    elements: [
      "Planning approach (predictive vs. adaptive)",
      "Formality and level of detail",
      "Business analysis activities",
      "Timing of BA work",
      "Complexity and risk",
      "Acceptance",
    ],
    inputs: ["Needs"],
    outputs: ["Business Analysis Approach"],
    techniques: [
      "TECH-document-analysis",
      "TECH-estimation",
      "TECH-process-modelling",
      "TECH-risk-analysis",
      "TECH-workshops",
    ],
    stakeholders: ["Domain SME", "Project Manager", "Regulator", "Sponsor"],
    guidelines: ["Business Analysis Performance Assessment", "Expert Judgment", "Methodologies and Frameworks"],
    notes:
      "Sets how formal, detailed, and predictive vs. adaptive the BA effort will be. Drives every other planning task. Predictive favors up-front detail; adaptive favors progressive elaboration.",
  },
  {
    id: "BAPM-2",
    kaId: "BAPM",
    name: "Plan Stakeholder Engagement",
    purpose:
      "Plan an approach for establishing and maintaining effective working relationships with stakeholders.",
    elements: [
      "Perform stakeholder analysis",
      "Define stakeholder collaboration",
      "Stakeholder communication needs",
    ],
    inputs: ["Needs", "Business Analysis Approach"],
    outputs: ["Stakeholder Engagement Approach"],
    techniques: [
      "TECH-brainstorming",
      "TECH-document-analysis",
      "TECH-interviews",
      "TECH-stakeholder-list-map",
      "TECH-workshops",
    ],
    stakeholders: ["Customer", "Domain SME", "End User", "Project Manager", "Sponsor", "Supplier"],
    guidelines: ["Business Analysis Approach", "Change Strategy", "Current State Description"],
    notes:
      "Identify who is affected, their influence/interest, and how to collaborate. A stakeholder map (e.g. RACI or influence/impact grid) is the central artifact.",
  },
  {
    id: "BAPM-3",
    kaId: "BAPM",
    name: "Plan Business Analysis Governance",
    purpose:
      "Define how decisions are made about requirements and designs, including reviews, change control, approvals, and prioritization.",
    elements: ["Decision making", "Change control process", "Plan prioritization approach", "Plan for approvals"],
    inputs: ["Business Analysis Approach", "Stakeholder Engagement Approach"],
    outputs: ["Governance Approach"],
    techniques: [
      "TECH-document-analysis",
      "TECH-interviews",
      "TECH-item-tracking",
      "TECH-workshops",
    ],
    stakeholders: ["Domain SME", "Project Manager", "Regulator", "Sponsor"],
    guidelines: ["Business Analysis Approach", "Business Policies", "Current State Description", "Legal/Regulatory Information"],
    notes:
      "Establishes who has decision authority, how changes are proposed and approved, and how requirements are prioritized. Without it, approvals and change control stall.",
  },
  {
    id: "BAPM-4",
    kaId: "BAPM",
    name: "Plan Business Analysis Information Management",
    purpose:
      "Define how business analysis information will be stored, accessed, organized, and reused after the initiative ends.",
    elements: ["Organization of BA information", "Level of abstraction", "Plan traceability approach", "Plan for requirements reuse", "Storage and access", "Requirements attributes"],
    inputs: ["Business Analysis Approach", "Governance Approach", "Stakeholder Engagement Approach"],
    outputs: ["Information Management Approach"],
    techniques: ["TECH-interviews", "TECH-item-tracking", "TECH-workshops"],
    stakeholders: ["Domain SME", "Regulator", "Sponsor"],
    guidelines: ["Business Analysis Approach", "Governance Approach", "Legal/Regulatory Information"],
    notes:
      "Decides how BA information is captured, traced, and reused — the foundation for traceability and long-term value of requirements.",
  },
  {
    id: "BAPM-5",
    kaId: "BAPM",
    name: "Identify Business Analysis Performance Improvements",
    purpose:
      "Assess business analysis work and plan to improve it where required.",
    elements: ["Performance analysis", "Assessment measures", "Analyze results", "Recommend actions for improvement"],
    inputs: ["Business Analysis Approach", "Performance Objectives"],
    outputs: ["Business Analysis Performance Assessment"],
    techniques: [
      "TECH-brainstorming",
      "TECH-interviews",
      "TECH-metrics-kpis",
      "TECH-observation",
      "TECH-process-modelling",
      "TECH-reviews",
      "TECH-risk-analysis",
    ],
    stakeholders: ["Domain SME", "Project Manager", "Sponsor"],
    guidelines: ["Business Analysis Approach", "Organizational Performance Standards"],
    notes:
      "Monitor BA work against performance objectives and recommend improvements. The assessment feeds back into Plan Business Analysis Approach.",
  },

  // ─── Elicitation & Collaboration ───
  {
    id: "EC-1",
    kaId: "EC",
    name: "Prepare for Elicitation",
    purpose: "Understand the scope of the elicitation activity, select techniques, and plan appropriate logistics.",
    elements: ["Understand the scope of elicitation", "Select elicitation techniques", "Set up logistics", "Secure supporting material", "Prepare stakeholders"],
    inputs: ["Needs", "Stakeholder Engagement Approach"],
    outputs: ["Elicitation Activity Plan"],
    techniques: [
      "TECH-brainstorming",
      "TECH-document-analysis",
      "TECH-estimation",
      "TECH-interviews",
      "TECH-risk-analysis",
      "TECH-stakeholder-list-map",
    ],
    stakeholders: ["Domain SME", "Project Manager", "Sponsor"],
    guidelines: ["Business Analysis Approach", "Business Objectives", "Existing BA Information", "Potential Value"],
    notes:
      "Choose techniques fit to purpose and prepare stakeholders and materials. Good preparation is the difference between a productive session and a wasted one.",
  },
  {
    id: "EC-2",
    kaId: "EC",
    name: "Conduct Elicitation",
    purpose: "Draw out, explore, and identify information relevant to the change.",
    elements: ["Guide elicitation activity", "Capture elicitation outcomes"],
    inputs: ["Elicitation Activity Plan"],
    outputs: ["Elicitation Results (unconfirmed)"],
    techniques: [
      "TECH-brainstorming",
      "TECH-document-analysis",
      "TECH-interviews",
      "TECH-observation",
      "TECH-prototyping",
      "TECH-survey",
      "TECH-workshops",
    ],
    stakeholders: ["Customer", "Domain SME", "End User", "Implementation SME", "Sponsor"],
    guidelines: ["Business Analysis Approach", "Existing BA Information", "Stakeholder Engagement Approach", "Supporting Materials"],
    notes:
      "Three broad approaches: collaborative (interviews, workshops), research (document analysis), and experiments (observation, prototyping, surveys). Results are unconfirmed until validated.",
  },
  {
    id: "EC-3",
    kaId: "EC",
    name: "Confirm Elicitation Results",
    purpose: "Check the information gathered during an elicitation session for accuracy and consistency.",
    elements: ["Compare elicitation results against source information", "Compare elicitation results against other elicitation results"],
    inputs: ["Elicitation Results (unconfirmed)"],
    outputs: ["Elicitation Results (confirmed)"],
    techniques: ["TECH-document-analysis", "TECH-interviews", "TECH-reviews", "TECH-workshops"],
    stakeholders: ["Customer", "Domain SME", "End User", "Implementation SME", "Sponsor"],
    guidelines: ["Elicitation Activity Plan", "Existing BA Information"],
    notes:
      "Confirm that captured results match the source and are internally consistent. Cheap to fix errors here; expensive later. Distinct from verification/validation, which happen in RADD.",
  },
  {
    id: "EC-4",
    kaId: "EC",
    name: "Communicate Business Analysis Information",
    purpose: "Ensure stakeholders have a shared understanding of business analysis information.",
    elements: ["Determine objectives and format of communication", "Communicate business analysis package"],
    inputs: ["Business Analysis Information", "Stakeholder Engagement Approach"],
    outputs: ["Business Analysis Information (communicated)"],
    techniques: ["TECH-interviews", "TECH-reviews", "TECH-workshops"],
    stakeholders: ["End User", "Customer", "Domain SME", "Implementation SME", "Project Manager", "Regulator", "Sponsor", "Supplier", "Tester"],
    guidelines: ["Business Analysis Approach", "Information Management Approach"],
    notes:
      "Package and deliver BA information in the right form for the audience. Communication is about shared understanding, not just transmission.",
  },
  {
    id: "EC-5",
    kaId: "EC",
    name: "Manage Stakeholder Collaboration",
    purpose: "Encourage stakeholders to work towards a common goal.",
    elements: ["Gain agreement on commitments", "Monitor stakeholder engagement", "Collaboration"],
    inputs: ["Stakeholder Engagement Approach", "Business Analysis Performance Assessment"],
    outputs: ["Stakeholder Engagement"],
    techniques: ["TECH-stakeholder-list-map", "TECH-risk-analysis", "TECH-lessons-learned"],
    stakeholders: ["All stakeholders"],
    guidelines: ["Business Analysis Approach", "Business Objectives", "Future State Description", "Recommended Actions", "Risk Analysis Results"],
    notes:
      "Ongoing, not a one-time task. Manage commitments, attitudes, and trust throughout. Poor collaboration is a leading cause of requirements failure.",
  },

  // ─── Requirements Life Cycle Management ───
  {
    id: "RLCM-1",
    kaId: "RLCM",
    name: "Trace Requirements",
    purpose: "Ensure requirements and designs at different levels are aligned, and manage the effects of change.",
    elements: ["Level of formality", "Relationships (derive, depends, satisfy, validate)", "Traceability repository"],
    inputs: ["Requirements", "Designs"],
    outputs: ["Requirements (traced)", "Designs (traced)"],
    techniques: ["TECH-business-rules-analysis", "TECH-functional-decomposition", "TECH-process-modelling", "TECH-scope-modelling"],
    stakeholders: ["Customer", "Domain SME", "Implementation SME", "Operational Support", "Project Manager", "Supplier", "Tester"],
    guidelines: ["Domain Knowledge", "Information Management Approach", "Legal/Regulatory Information", "Requirements Management Tools/Repository"],
    notes:
      "Links requirements to one another, to designs, and to solution components and business objectives. Enables impact analysis and coverage. Key relationship types: derive, depends, satisfy, validate.",
  },
  {
    id: "RLCM-2",
    kaId: "RLCM",
    name: "Maintain Requirements",
    purpose: "Retain requirement accuracy and consistency throughout and beyond the change, so they can be reused.",
    elements: ["Maintain requirements", "Maintain attributes", "Reusing requirements"],
    inputs: ["Requirements", "Designs"],
    outputs: ["Requirements (maintained)", "Designs (maintained)"],
    techniques: ["TECH-business-rules-analysis", "TECH-document-analysis", "TECH-functional-decomposition", "TECH-process-modelling"],
    stakeholders: ["Domain SME", "Implementation SME", "Operational Support", "Regulator", "Tester"],
    guidelines: ["Information Management Approach"],
    notes:
      "Keep requirements correct and current so they hold value as reusable assets after the project. Maintained requirements (e.g. business rules, NFRs) often outlive the initiative.",
  },
  {
    id: "RLCM-3",
    kaId: "RLCM",
    name: "Prioritize Requirements",
    purpose: "Rank requirements in the order of relative importance.",
    elements: ["Basis for prioritization (benefit, penalty, cost, risk, dependencies, time sensitivity, stability, regulatory)", "Challenges of prioritization", "Continual prioritization"],
    inputs: ["Requirements", "Designs"],
    outputs: ["Requirements (prioritized)", "Designs (prioritized)"],
    techniques: ["TECH-backlog-management", "TECH-business-cases", "TECH-decision-analysis", "TECH-estimation", "TECH-financial-analysis", "TECH-prioritization", "TECH-risk-analysis", "TECH-workshops"],
    stakeholders: ["Customer", "End User", "Implementation SME", "Project Manager", "Regulator", "Sponsor"],
    guidelines: ["Business Constraints", "Change Strategy", "Domain Knowledge", "Governance Approach", "Requirements Architecture"],
    notes:
      "Prioritization bases: benefit, penalty, cost, risk, dependencies, time sensitivity, stability, regulatory/policy compliance. It is continual, not one-time.",
  },
  {
    id: "RLCM-4",
    kaId: "RLCM",
    name: "Assess Requirements Changes",
    purpose: "Evaluate the implications of proposed changes to requirements and designs.",
    elements: ["Assessment formality", "Impact analysis (benefit, cost, impact, schedule, urgency)", "Impact resolution"],
    inputs: ["Requirements", "Designs", "Proposed Change"],
    outputs: ["Requirements Change Assessment", "Designs Change Assessment"],
    techniques: ["TECH-business-cases", "TECH-business-rules-analysis", "TECH-decision-analysis", "TECH-estimation", "TECH-financial-analysis", "TECH-interface-analysis", "TECH-item-tracking", "TECH-risk-analysis", "TECH-workshops"],
    stakeholders: ["Customer", "Domain SME", "Operational Support", "Project Manager", "Regulator", "Sponsor", "Tester"],
    guidelines: ["Change Strategy", "Domain Knowledge", "Governance Approach", "Legal/Regulatory Information", "Requirements Architecture", "Solution Scope"],
    notes:
      "Analyze each proposed change for benefit, cost, impact, schedule, and urgency before accepting it. Impact analysis relies on traceability (RLCM-1).",
  },
  {
    id: "RLCM-5",
    kaId: "RLCM",
    name: "Approve Requirements",
    purpose: "Obtain agreement on and approval of requirements and designs for business analysis work to continue.",
    elements: ["Understand stakeholder roles", "Conflict and issue management", "Gain consensus", "Track and communicate approval"],
    inputs: ["Requirements (verified)", "Designs"],
    outputs: ["Requirements (approved)", "Designs (approved)"],
    techniques: ["TECH-acceptance-evaluation-criteria", "TECH-decision-analysis", "TECH-item-tracking", "TECH-reviews", "TECH-workshops"],
    stakeholders: ["Customer", "Domain SME", "End User", "Operational Support", "Project Manager", "Regulator", "Sponsor", "Tester"],
    guidelines: ["Change Strategy", "Governance Approach", "Legal/Regulatory Information", "Requirements Management Tools/Repository", "Solution Scope"],
    notes:
      "Approval depends on the governance approach (who can approve) and may require resolving conflicts and building consensus first. In adaptive contexts approval can be incremental.",
  },

  // ─── Strategy Analysis ───
  {
    id: "SA-1",
    kaId: "SA",
    name: "Analyze Current State",
    purpose:
      "Understand why an enterprise needs to change some aspect of how it operates and what would be directly or indirectly affected by the change.",
    elements: ["Business needs", "Organizational structure and culture", "Capabilities and processes", "Technology and infrastructure", "Policies", "Business architecture", "Internal assets", "External influencers"],
    inputs: ["Elicitation Results (confirmed)", "Needs"],
    outputs: ["Current State Description", "Business Requirements"],
    techniques: ["TECH-business-capability-analysis", "TECH-document-analysis", "TECH-financial-analysis", "TECH-organizational-modelling", "TECH-process-modelling", "TECH-root-cause-analysis", "TECH-swot-analysis"],
    stakeholders: ["Customer", "Domain SME", "End User", "Regulator", "Sponsor", "Supplier"],
    guidelines: ["Business Analysis Approach", "Enterprise Limitation", "Organizational Strategy", "Solution Limitation"],
    notes:
      "Establishes the baseline against which the future state and delivered value are judged. The need drives the analysis — never start from a presumed solution.",
  },
  {
    id: "SA-2",
    kaId: "SA",
    name: "Define Future State",
    purpose: "Determine the set of necessary conditions to meet the business need.",
    elements: ["Business goals and objectives", "Scope of solution space", "Constraints", "Organizational structure and culture", "Capabilities and processes", "Technology and infrastructure", "Policies", "Business architecture", "Internal assets", "Identify assumptions", "Potential value"],
    inputs: ["Business Requirements"],
    outputs: ["Business Objectives", "Future State Description", "Potential Value"],
    techniques: ["TECH-acceptance-evaluation-criteria", "TECH-balanced-scorecard", "TECH-business-capability-analysis", "TECH-business-cases", "TECH-decision-analysis", "TECH-financial-analysis", "TECH-organizational-modelling", "TECH-scope-modelling"],
    stakeholders: ["Customer", "Domain SME", "End User", "Regulator", "Sponsor"],
    guidelines: ["Current State Description", "Metrics and Key Performance Indicators (KPIs)", "Organizational Strategy"],
    notes:
      "Describes the desired end state and the value it should deliver. Objectives should be SMART. Potential value is the net benefit expected once the future state is reached.",
  },
  {
    id: "SA-3",
    kaId: "SA",
    name: "Assess Risks",
    purpose: "Understand the undesirable consequences of internal and external forces on the enterprise during a transition to, or once in, the future state.",
    elements: ["Unknowns", "Constraints, assumptions, and dependencies", "Negative impact to value", "Risk tolerance", "Recommendation"],
    inputs: ["Business Objectives", "Influences", "Potential Value", "Requirements", "Elicitation Results (confirmed)"],
    outputs: ["Risk Analysis Results"],
    techniques: ["TECH-brainstorming", "TECH-business-cases", "TECH-decision-analysis", "TECH-document-analysis", "TECH-financial-analysis", "TECH-interviews", "TECH-risk-analysis", "TECH-workshops"],
    stakeholders: ["Domain SME", "Implementation SME", "Operational Support", "Project Manager", "Regulator", "Sponsor", "Supplier"],
    guidelines: ["Business Analysis Approach", "Business Policies", "Change Strategy", "Current State Description", "Future State Description", "Identified Risks", "Stakeholder Engagement Approach"],
    notes:
      "Identify, analyze, and plan responses to risks that threaten the value of the change. Risk tolerance (averse, neutral, seeking) shapes which responses are acceptable.",
  },
  {
    id: "SA-4",
    kaId: "SA",
    name: "Define Change Strategy",
    purpose: "Develop and assess alternative approaches to the change, and then select the recommended approach.",
    elements: ["Solution scope", "Gap analysis", "Enterprise readiness assessment", "Change strategy", "Transition states and release planning"],
    inputs: ["Current State Description", "Future State Description", "Risk Analysis Results", "Stakeholder Engagement Approach"],
    outputs: ["Change Strategy", "Solution Scope"],
    techniques: ["TECH-balanced-scorecard", "TECH-business-capability-analysis", "TECH-business-cases", "TECH-decision-analysis", "TECH-estimation", "TECH-financial-analysis", "TECH-functional-decomposition", "TECH-organizational-modelling", "TECH-process-modelling", "TECH-scope-modelling", "TECH-swot-analysis", "TECH-vendor-assessment"],
    stakeholders: ["Customer", "Domain SME", "End User", "Implementation SME", "Operational Support", "Project Manager", "Regulator", "Sponsor", "Supplier"],
    guidelines: ["Business Analysis Approach", "Design Options", "Solution Recommendations"],
    notes:
      "Bridges current and future state via gap analysis. Defines transition states, release plan, and solution scope. The change strategy is the 'how we will get there'.",
  },

  // ─── Requirements Analysis & Design Definition ───
  {
    id: "RADD-1",
    kaId: "RADD",
    name: "Specify and Model Requirements",
    purpose: "Analyze, synthesize, and refine elicitation results into requirements and designs.",
    elements: ["Model requirements", "Analyze requirements", "Represent requirements and attributes", "Implement the appropriate levels of abstraction"],
    inputs: ["Elicitation Results (any)"],
    outputs: ["Requirements (specified and modeled)"],
    techniques: ["TECH-business-rules-analysis", "TECH-data-flow-diagrams", "TECH-data-modelling", "TECH-functional-decomposition", "TECH-glossary", "TECH-interface-analysis", "TECH-nfr-analysis", "TECH-process-modelling", "TECH-prototyping", "TECH-scope-modelling", "TECH-use-cases-scenarios", "TECH-user-stories"],
    stakeholders: ["Any stakeholder"],
    guidelines: ["Modeling Notations/Standards", "Modeling Tools", "Requirements Architecture", "Requirements Life Cycle Management Tools", "Solution Scope"],
    notes:
      "Turns raw elicitation results into structured requirements and models. Choose models (process, data, rules, NFRs) by viewpoint and audience. Distinguishes requirements (need) from designs (solution).",
  },
  {
    id: "RADD-2",
    kaId: "RADD",
    name: "Verify Requirements",
    purpose: "Ensure that requirements and designs specifications and models meet quality standards and are usable.",
    elements: ["Characteristics of requirements and designs quality", "Verification activities", "Checklists"],
    inputs: ["Requirements (specified and modeled)", "Designs"],
    outputs: ["Requirements (verified)", "Designs (verified)"],
    techniques: ["TECH-acceptance-evaluation-criteria", "TECH-item-tracking", "TECH-metrics-kpis", "TECH-reviews"],
    stakeholders: ["Implementation SME", "Any stakeholder"],
    guidelines: ["Requirements Life Cycle Management Tools"],
    notes:
      "Verify = 'are we building the requirements right?' (quality: clear, complete, consistent, testable, feasible). Validation is separate (RADD-3). Quality characteristics: atomic, complete, consistent, concise, feasible, unambiguous, testable, prioritized, understandable.",
  },
  {
    id: "RADD-3",
    kaId: "RADD",
    name: "Validate Requirements",
    purpose: "Ensure that all requirements and designs align to the business requirements and support the delivery of needed value.",
    elements: ["Identify assumptions", "Define measurable evaluation criteria", "Evaluate alignment with solution scope"],
    inputs: ["Requirements (specified and modeled)", "Designs"],
    outputs: ["Requirements (validated)", "Designs (validated)"],
    techniques: ["TECH-acceptance-evaluation-criteria", "TECH-document-analysis", "TECH-financial-analysis", "TECH-item-tracking", "TECH-metrics-kpis", "TECH-reviews", "TECH-risk-analysis"],
    stakeholders: ["Customer", "End User", "Sponsor", "Any stakeholder"],
    guidelines: ["Business Objectives", "Future State Description", "Potential Value", "Solution Scope"],
    notes:
      "Validate = 'are we building the right requirements?' — do they deliver value and align to business objectives. Verification (RADD-2) is about quality; validation is about value/alignment.",
  },
  {
    id: "RADD-4",
    kaId: "RADD",
    name: "Define Requirements Architecture",
    purpose: "Structure all the requirements and designs so that they support the overall business purpose for a change and work together effectively.",
    elements: ["Requirements viewpoints and views", "Template architectures", "Completeness", "Relate and verify requirements relationships", "Business analysis information architecture"],
    inputs: ["Information Management Approach", "Requirements (any)", "Solution Scope"],
    outputs: ["Requirements Architecture"],
    techniques: ["TECH-data-modelling", "TECH-functional-decomposition", "TECH-interviews", "TECH-organizational-modelling", "TECH-scope-modelling", "TECH-workshops"],
    stakeholders: ["Domain SME", "Implementation SME", "Project Manager", "Sponsor", "Tester"],
    guidelines: ["Architecture Management Software", "Legal/Regulatory Information", "Methodologies and Frameworks"],
    notes:
      "Organizes requirements into a coherent whole using viewpoints and views, ensuring completeness and that requirements fit together to serve the business purpose.",
  },
  {
    id: "RADD-5",
    kaId: "RADD",
    name: "Define Design Options",
    purpose: "Define solution approaches, identify opportunities to improve the business, allocate requirements across solution components, and represent design options.",
    elements: ["Define solution approaches", "Identify improvement opportunities", "Requirements allocation", "Describe design options"],
    inputs: ["Change Strategy", "Requirements (validated, prioritized)", "Requirements Architecture"],
    outputs: ["Design Options"],
    techniques: ["TECH-brainstorming", "TECH-document-analysis", "TECH-interviews", "TECH-organizational-modelling", "TECH-vendor-assessment", "TECH-workshops"],
    stakeholders: ["Domain SME", "Implementation SME", "Operational Support", "Project Manager", "Supplier"],
    guidelines: ["Existing Solutions", "Future State Description", "Requirements (traced)", "Solution Scope"],
    notes:
      "Solution approaches: create, purchase, or combine. Each design option allocates requirements to components and describes the trade-offs. Feeds RADD-6.",
  },
  {
    id: "RADD-6",
    kaId: "RADD",
    name: "Analyze Potential Value and Recommend Solution",
    purpose: "Estimate the potential value for each design option and establish which one is most appropriate to recommend.",
    elements: ["Expected benefits", "Expected costs", "Determine value", "Assess design options and recommend solution"],
    inputs: ["Potential Value", "Design Options"],
    outputs: ["Solution Recommendation"],
    techniques: ["TECH-acceptance-evaluation-criteria", "TECH-backlog-management", "TECH-decision-analysis", "TECH-estimation", "TECH-financial-analysis", "TECH-risk-analysis", "TECH-survey"],
    stakeholders: ["Customer", "Domain SME", "End User", "Project Manager", "Regulator", "Sponsor"],
    guidelines: ["Business Objectives", "Current State Description", "Future State Description", "Risk Analysis Results", "Solution Scope"],
    notes:
      "Compare options on expected benefits minus costs (net value), considering risk, and recommend the most valuable feasible option. Value, not cost alone, drives the recommendation.",
  },

  // ─── Solution Evaluation ───
  {
    id: "SE-1",
    kaId: "SE",
    name: "Measure Solution Performance",
    purpose: "Define performance measures and use the data collected to evaluate the effectiveness of a solution in relation to the value it brings.",
    elements: ["Define solution performance measures", "Validate performance measures", "Collect performance measures"],
    inputs: ["Business Objectives", "Implemented Solution (External)"],
    outputs: ["Solution Performance Measures"],
    techniques: ["TECH-acceptance-evaluation-criteria", "TECH-brainstorming", "TECH-business-cases", "TECH-data-modelling", "TECH-decision-analysis", "TECH-financial-analysis", "TECH-metrics-kpis", "TECH-observation", "TECH-prototyping", "TECH-survey"],
    stakeholders: ["Customer", "Domain SME", "End User", "Sponsor", "Regulator"],
    guidelines: ["Change Strategy", "Future State Description", "Solution Scope"],
    notes:
      "Choose measures tied to business objectives (quantitative where possible). Measures may be dictated by the organization, by stakeholders, or defined by the BA.",
  },
  {
    id: "SE-2",
    kaId: "SE",
    name: "Analyze Performance Measures",
    purpose: "Provide insights into the performance of a solution in relation to the value it brings.",
    elements: ["Solution performance versus desired value", "Risks", "Trends", "Accuracy", "Performance variances"],
    inputs: ["Potential Value", "Solution Performance Measures"],
    outputs: ["Solution Performance Analysis"],
    techniques: ["TECH-data-modelling", "TECH-decision-analysis", "TECH-financial-analysis", "TECH-interviews", "TECH-metrics-kpis", "TECH-observation", "TECH-risk-analysis", "TECH-survey"],
    stakeholders: ["Customer", "Domain SME", "End User", "Sponsor", "Regulator"],
    guidelines: ["Change Strategy", "Future State Description", "Risk Analysis Results", "Solution Scope"],
    notes:
      "Interpret the measures: compare actual performance to potential value, spot trends and variances, and judge whether the solution delivers the intended value.",
  },
  {
    id: "SE-3",
    kaId: "SE",
    name: "Assess Solution Limitations",
    purpose: "Determine the factors internal to the solution that restrict the full realization of value.",
    elements: ["Identify internal solution component dependencies", "Investigate solution problems", "Impact assessment"],
    inputs: ["Implemented Solution (External)", "Solution Performance Analysis"],
    outputs: ["Solution Limitation"],
    techniques: ["TECH-acceptance-evaluation-criteria", "TECH-business-rules-analysis", "TECH-data-modelling", "TECH-decision-analysis", "TECH-interviews", "TECH-item-tracking", "TECH-risk-analysis", "TECH-root-cause-analysis", "TECH-survey"],
    stakeholders: ["Customer", "Domain SME", "End User", "Sponsor", "Implementation SME"],
    guidelines: ["Change Strategy", "Solution Scope"],
    notes:
      "When performance falls short, find limits inside the solution itself (defects, design constraints). Root cause analysis separates true causes from symptoms.",
  },
  {
    id: "SE-4",
    kaId: "SE",
    name: "Assess Enterprise Limitations",
    purpose: "Determine how factors external to the solution are restricting value realization.",
    elements: ["Enterprise culture assessment", "Stakeholder impact analysis", "Organizational structure changes", "Operational assessment"],
    inputs: ["Current State Description", "Implemented Solution (External)", "Solution Performance Analysis"],
    outputs: ["Enterprise Limitation"],
    techniques: ["TECH-data-modelling", "TECH-decision-analysis", "TECH-document-analysis", "TECH-interviews", "TECH-item-tracking", "TECH-observation", "TECH-organizational-modelling", "TECH-process-modelling", "TECH-risk-analysis", "TECH-root-cause-analysis", "TECH-survey"],
    stakeholders: ["Customer", "Domain SME", "End User", "Regulator", "Sponsor"],
    guidelines: ["Business Objectives", "Current State Description", "Future State Description", "Solution Scope"],
    notes:
      "When the solution works but value still isn't realized, the limit is in the enterprise — culture, structure, processes, or stakeholder adoption.",
  },
  {
    id: "SE-5",
    kaId: "SE",
    name: "Recommend Actions to Increase Solution Value",
    purpose: "Understand the factors that create differences between potential value and actual value, and recommend a course of action to align them.",
    elements: ["Adjust solution performance measures", "Recommendations (do nothing, organizational change, reduce complexity, eliminate redundancy, avoid waste, identify additional capabilities, retire the solution)"],
    inputs: ["Enterprise Limitation", "Solution Limitation"],
    outputs: ["Recommended Actions"],
    techniques: ["TECH-data-modelling", "TECH-decision-analysis", "TECH-financial-analysis", "TECH-organizational-modelling", "TECH-prioritization", "TECH-risk-analysis", "TECH-survey"],
    stakeholders: ["Customer", "Domain SME", "End User", "Sponsor", "Regulator"],
    guidelines: ["Business Objectives", "Current State Description", "Solution Scope"],
    notes:
      "Recommendation options range from do nothing, to organizational change, reduce complexity, eliminate redundancy/waste, add capabilities, or retire the solution. Tie each to the limitation it addresses.",
  },
];
