import type { Technique } from "./types";

// Defines every technique id referenced by tasks.ts. Summaries are original phrasing.
export const techniques: Technique[] = [
  {
    id: "TECH-acceptance-evaluation-criteria",
    name: "Acceptance and Evaluation Criteria",
    purpose: "Define requirements that must be met for a solution to be acceptable, and criteria for comparing options.",
    summary: "Acceptance criteria are pass/fail conditions (common in contracts and agile stories); evaluation criteria allow ranking among multiple options.",
    relatedTaskIds: ["RLCM-5", "RADD-2", "RADD-3", "RADD-6", "SE-1"],
  },
  {
    id: "TECH-backlog-management",
    name: "Backlog Management",
    purpose: "Plan and manage the recording, tracking, and prioritization of remaining work items.",
    summary: "A single, prioritized list of work (requirements, designs, defects) refined continuously; the source from which work is pulled in adaptive approaches.",
    relatedTaskIds: ["RLCM-3", "RADD-6"],
  },
  {
    id: "TECH-balanced-scorecard",
    name: "Balanced Scorecard",
    purpose: "Manage performance across financial, customer, internal process, and learning-and-growth perspectives.",
    summary: "Links strategic objectives to measures across four perspectives so value is judged beyond just financial results.",
    relatedTaskIds: ["SA-2", "SA-4"],
  },
  {
    id: "TECH-brainstorming",
    name: "Brainstorming",
    purpose: "Generate many ideas and foster creative thinking among a group.",
    summary: "Divergent idea generation without judgment, followed by convergent grouping and prioritization of the ideas produced.",
    relatedTaskIds: ["BAPM-2", "EC-1", "EC-2", "SA-3", "RADD-5", "SE-1"],
  },
  {
    id: "TECH-business-capability-analysis",
    name: "Business Capability Analysis",
    purpose: "Describe what an enterprise can do, and identify gaps and priorities for investment.",
    summary: "Capability maps (what the business does, not how) with performance and value heat-mapping to target change.",
    relatedTaskIds: ["SA-1", "SA-2", "SA-4"],
  },
  {
    id: "TECH-business-cases",
    name: "Business Cases",
    purpose: "Justify a proposed change by capturing the rationale, costs, benefits, and risks.",
    summary: "Assesses need, alternatives, and expected value to support an invest/do-not-invest decision.",
    relatedTaskIds: ["RLCM-3", "RLCM-4", "SA-2", "SA-3", "SA-4", "SE-1"],
  },
  {
    id: "TECH-business-rules-analysis",
    name: "Business Rules Analysis",
    purpose: "Identify, express, and manage the rules that govern decisions in an organization.",
    summary: "Separates definitional rules (structure) from behavioral rules (conduct); keeps rules atomic, declarative, and independent of implementation.",
    relatedTaskIds: ["RLCM-1", "RLCM-2", "RLCM-4", "RADD-1", "SE-3"],
  },
  {
    id: "TECH-data-flow-diagrams",
    name: "Data Flow Diagrams",
    purpose: "Show how information flows through processes, stores, and external entities.",
    summary: "Models inputs, processes, data stores, and outputs to reveal how data moves and is transformed.",
    relatedTaskIds: ["RADD-1"],
  },
  {
    id: "TECH-data-modelling",
    name: "Data Modelling",
    purpose: "Describe the entities, attributes, and relationships relevant to a domain.",
    summary: "Entity-relationship/class models capturing concepts, their attributes, and cardinality of relationships.",
    relatedTaskIds: ["RADD-1", "RADD-4", "SE-1", "SE-2", "SE-3", "SE-4", "SE-5"],
  },
  {
    id: "TECH-decision-analysis",
    name: "Decision Analysis",
    purpose: "Assess a problem and possible decisions to compare alternatives under uncertainty.",
    summary: "Structures options, criteria, and outcomes (decision tables/trees, weighted scoring, expected value) to make defensible choices.",
    relatedTaskIds: ["RLCM-3", "RLCM-4", "RLCM-5", "SA-2", "SA-3", "RADD-6", "SE-2"],
  },
  {
    id: "TECH-document-analysis",
    name: "Document Analysis",
    purpose: "Elicit information by examining existing materials and documentation.",
    summary: "A research-style technique mining existing artifacts (procedures, contracts, systems) for current-state information.",
    relatedTaskIds: ["BAPM-1", "EC-2", "EC-3", "SA-1", "SA-3", "RADD-3", "RADD-5", "SE-4"],
  },
  {
    id: "TECH-estimation",
    name: "Estimation",
    purpose: "Forecast the cost and effort of pursuing a course of action under uncertainty.",
    summary: "Techniques like analogous, parametric, three-point (PERT), and rolling-wave estimation, refined as more is known.",
    relatedTaskIds: ["BAPM-1", "EC-1", "RLCM-3", "RLCM-4", "SA-4", "RADD-6"],
  },
  {
    id: "TECH-financial-analysis",
    name: "Financial Analysis",
    purpose: "Understand the financial aspects of an investment, solution, or approach.",
    summary: "Cost-benefit and return measures: ROI, NPV, IRR, payback period — to compare options on financial value.",
    relatedTaskIds: ["RLCM-3", "SA-1", "SA-2", "SA-4", "RADD-6", "SE-1", "SE-2"],
  },
  {
    id: "TECH-functional-decomposition",
    name: "Functional Decomposition",
    purpose: "Break down complex systems, processes, or scope into smaller, more manageable parts.",
    summary: "Hierarchical breakdown of a whole into components to manage complexity and enable analysis and estimation.",
    relatedTaskIds: ["RLCM-1", "RLCM-2", "SA-4", "RADD-1", "RADD-4"],
  },
  {
    id: "TECH-glossary",
    name: "Glossary",
    purpose: "Maintain a common, agreed set of definitions for terms used by stakeholders.",
    summary: "A shared vocabulary that reduces ambiguity and miscommunication across stakeholder groups.",
    relatedTaskIds: ["RADD-1"],
  },
  {
    id: "TECH-interface-analysis",
    name: "Interface Analysis",
    purpose: "Identify and analyze interactions between solutions, systems, organizations, and people.",
    summary: "Identifies inputs/outputs across interfaces (user, system, hardware) to ensure complete and consistent integration requirements.",
    relatedTaskIds: ["RLCM-4", "RADD-1"],
  },
  {
    id: "TECH-interviews",
    name: "Interviews",
    purpose: "Elicit information from a person or group in a directed conversation.",
    summary: "Structured or unstructured questioning, one-on-one or small group; depends on rapport and good question design.",
    relatedTaskIds: ["BAPM-2", "BAPM-3", "EC-2", "EC-3", "SA-3", "RADD-4", "SE-2", "SE-4"],
  },
  {
    id: "TECH-item-tracking",
    name: "Item Tracking",
    purpose: "Capture and assign responsibility for issues and stakeholder concerns to resolution.",
    summary: "An issue/action log recording status, owner, priority, and resolution so concerns are not lost.",
    relatedTaskIds: ["BAPM-3", "RLCM-4", "RLCM-5", "RADD-2", "RADD-3", "SE-3", "SE-4"],
  },
  {
    id: "TECH-lessons-learned",
    name: "Lessons Learned",
    purpose: "Compile and document successes, opportunities for improvement, and recommendations.",
    summary: "A retrospective review capturing what worked and what to improve, for future initiatives and process improvement.",
    relatedTaskIds: ["EC-5", "BAPM-5"],
  },
  {
    id: "TECH-metrics-kpis",
    name: "Metrics and Key Performance Indicators (KPIs)",
    purpose: "Measure the performance of solutions, components, and other matters of interest.",
    summary: "Metrics are quantifiable measures; KPIs are the subset that track progress toward objectives. Good metrics are SMART.",
    relatedTaskIds: ["BAPM-5", "RADD-2", "RADD-3", "SE-1", "SE-2"],
  },
  {
    id: "TECH-nfr-analysis",
    name: "Non-Functional Requirements Analysis",
    purpose: "Specify and describe quality attributes the solution must exhibit.",
    summary: "Captures qualities like performance, security, usability, reliability, and maintainability — the 'how well' rather than 'what'.",
    relatedTaskIds: ["RADD-1"],
  },
  {
    id: "TECH-observation",
    name: "Observation",
    purpose: "Elicit information by viewing and understanding activities in their environment.",
    summary: "Watching work as it happens (passive or active/participatory) to capture tacit knowledge people cannot easily articulate.",
    relatedTaskIds: ["BAPM-5", "EC-2", "SE-1", "SE-2", "SE-4"],
  },
  {
    id: "TECH-organizational-modelling",
    name: "Organizational Modelling",
    purpose: "Describe roles, responsibilities, and reporting structures within an organization.",
    summary: "Org charts and role models showing structure, lines of authority, and stakeholder relationships.",
    relatedTaskIds: ["SA-1", "SA-2", "SA-4", "RADD-4", "RADD-5", "SE-4", "SE-5"],
  },
  {
    id: "TECH-prioritization",
    name: "Prioritization",
    purpose: "Rank items to determine their relative importance and the order of work.",
    summary: "Approaches include grouping (MoSCoW), ranking, time-boxing/budgeting, and weighted scoring against criteria.",
    relatedTaskIds: ["RLCM-3", "SE-5"],
  },
  {
    id: "TECH-process-modelling",
    name: "Process Modelling",
    purpose: "Describe the sequential flow of work or activities to achieve an outcome.",
    summary: "Flowcharts, BPMN, or value-stream models showing steps, decisions, roles, and hand-offs in a process.",
    relatedTaskIds: ["BAPM-1", "BAPM-5", "RLCM-1", "RLCM-2", "SA-1", "SA-4", "RADD-1", "SE-4"],
  },
  {
    id: "TECH-prototyping",
    name: "Prototyping",
    purpose: "Elicit and validate needs through an early, often partial, working model.",
    summary: "Throwaway or evolutionary mock-ups that make requirements concrete and surface issues early.",
    relatedTaskIds: ["EC-2", "RADD-1", "SE-1"],
  },
  {
    id: "TECH-reviews",
    name: "Reviews",
    purpose: "Evaluate the content of a work product and confirm it meets standards.",
    summary: "Formal or informal inspections/walkthroughs to find defects and gain agreement on a work product.",
    relatedTaskIds: ["BAPM-5", "EC-3", "EC-4", "RLCM-5", "RADD-2", "RADD-3"],
  },
  {
    id: "TECH-risk-analysis",
    name: "Risk Analysis and Management",
    purpose: "Identify and manage areas of uncertainty that can affect value, positively or negatively.",
    summary: "Identify risks, assess likelihood and impact, and plan responses (avoid, transfer, mitigate, accept, increase).",
    relatedTaskIds: ["BAPM-1", "BAPM-5", "EC-1", "EC-5", "RLCM-3", "RLCM-4", "SA-3", "RADD-3", "RADD-6", "SE-2", "SE-3", "SE-4", "SE-5"],
  },
  {
    id: "TECH-root-cause-analysis",
    name: "Root Cause Analysis",
    purpose: "Identify and evaluate the underlying causes of a problem.",
    summary: "Structured examination (fishbone/Ishikawa, the five whys) distinguishing root causes from symptoms.",
    relatedTaskIds: ["SA-1", "SE-3", "SE-4"],
  },
  {
    id: "TECH-scope-modelling",
    name: "Scope Modelling",
    purpose: "Define the nature and extent of a change, what is in and out of scope.",
    summary: "Context diagrams, in/out lists, and boundary models defining what the solution and effort include.",
    relatedTaskIds: ["RLCM-1", "SA-2", "SA-4", "RADD-1", "RADD-4"],
  },
  {
    id: "TECH-stakeholder-list-map",
    name: "Stakeholder List, Map, or Personas",
    purpose: "Identify stakeholders and analyze their influence, attitude, and interest.",
    summary: "Lists, influence/impact grids (RACI, onion diagram), and personas to plan engagement based on power and interest.",
    relatedTaskIds: ["BAPM-2", "EC-1", "EC-5"],
  },
  {
    id: "TECH-survey",
    name: "Survey or Questionnaire",
    purpose: "Elicit information from many people, anonymously and at relatively low cost.",
    summary: "Open or closed questions distributed to a group; good for breadth and quantitative data, weaker for depth.",
    relatedTaskIds: ["EC-2", "RADD-6", "SE-1", "SE-2", "SE-3", "SE-4", "SE-5"],
  },
  {
    id: "TECH-swot-analysis",
    name: "SWOT Analysis",
    purpose: "Evaluate strengths, weaknesses, opportunities, and threats relevant to a change.",
    summary: "A strategic framework relating internal strengths/weaknesses to external opportunities/threats.",
    relatedTaskIds: ["SA-1", "SA-4"],
  },
  {
    id: "TECH-use-cases-scenarios",
    name: "Use Cases and Scenarios",
    purpose: "Describe how a person or system interacts with a solution to achieve a goal.",
    summary: "Actors, goals, main success scenario, and alternate/exception flows describing system behavior from the outside.",
    relatedTaskIds: ["RADD-1"],
  },
  {
    id: "TECH-user-stories",
    name: "User Stories",
    purpose: "Capture a small, valuable need from the perspective of a person who needs it.",
    summary: "Short 'As a… I want… so that…' statements with acceptance criteria, used as placeholders for conversation in adaptive approaches.",
    relatedTaskIds: ["RADD-1"],
  },
  {
    id: "TECH-vendor-assessment",
    name: "Vendor Assessment",
    purpose: "Assess the ability of a vendor to meet commitments regarding a product or service.",
    summary: "Evaluates vendor reliability, fit, licensing, and risk when a buy or outsource option is considered.",
    relatedTaskIds: ["SA-4", "RADD-5"],
  },
  {
    id: "TECH-workshops",
    name: "Workshops",
    purpose: "Bring stakeholders together in a focused, facilitated session to achieve a defined goal.",
    summary: "A structured group event with a facilitator and scribe to elicit, refine, or reach agreement quickly.",
    relatedTaskIds: ["BAPM-1", "BAPM-2", "BAPM-3", "BAPM-4", "EC-2", "EC-3", "EC-4", "RLCM-3", "RLCM-4", "RLCM-5", "SA-3", "RADD-4", "RADD-5"],
  },
];
