import type { Question } from "../types";

export const bapmQuestions: Question[] = [
  {
    id: "Q-BAPM-001",
    kaId: "BAPM",
    taskId: "BAPM-1",
    stem: "An organization mandates fixed, signed-off requirements before any build begins. Which planning approach does this most align with?",
    options: ["Hybrid by default", "Exploratory", "Adaptive", "Predictive"],
    correctIndex: 3,
    explanation: "A predictive approach favors up-front, formally controlled requirements; adaptive favors progressive elaboration and frequent change.",
    difficulty: "easy",
  },
  {
    id: "Q-BAPM-002",
    kaId: "BAPM",
    taskId: "BAPM-2",
    stem: "Which artifact is the primary output of Plan Stakeholder Engagement?",
    options: ["Information Management Approach", "Governance Approach", "Stakeholder Engagement Approach", "Business Analysis Approach"],
    correctIndex: 2,
    explanation: "Plan Stakeholder Engagement produces the Stakeholder Engagement Approach (stakeholder analysis, collaboration, and communication needs).",
    difficulty: "easy",
  },
  {
    id: "Q-BAPM-003",
    kaId: "BAPM",
    taskId: "BAPM-2",
    caseStudyId: "CS-001",
    stem: "At MeridianBank, branch staff fear losing relevance while the sponsor pushes speed. Which BABOK activity best addresses managing these differing positions up front?",
    options: ["Define Change Strategy", "Plan Stakeholder Engagement", "Measure Solution Performance", "Specify and Model Requirements"],
    correctIndex: 1,
    explanation: "Understanding influence/attitude and planning how to collaborate with conflicting stakeholders is the purpose of Plan Stakeholder Engagement.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-004",
    kaId: "BAPM",
    taskId: "BAPM-3",
    stem: "Defining who can approve requirements, how changes are controlled, and how prioritization happens is the purpose of which task?",
    options: ["Plan Business Analysis Governance", "Plan Business Analysis Information Management", "Plan Stakeholder Engagement", "Plan Business Analysis Approach"],
    correctIndex: 0,
    explanation: "Plan Business Analysis Governance defines decision making, change control, prioritization, and approvals.",
    difficulty: "easy",
  },
  {
    id: "Q-BAPM-005",
    kaId: "BAPM",
    taskId: "BAPM-4",
    stem: "Deciding how business analysis information will be traced, stored, and reused after the project is covered by:",
    options: ["Maintain Requirements", "Trace Requirements", "Plan Business Analysis Governance", "Plan Business Analysis Information Management"],
    correctIndex: 3,
    explanation: "Plan Business Analysis Information Management plans organization, traceability, storage/access, attributes, and reuse of BA information.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-006",
    kaId: "BAPM",
    taskId: "BAPM-5",
    stem: "The output of Identify Business Analysis Performance Improvements is:",
    options: ["Business Analysis Approach", "Performance Objectives", "Business Analysis Performance Assessment", "Governance Approach"],
    correctIndex: 2,
    explanation: "The task assesses BA work against performance objectives and produces the Business Analysis Performance Assessment, feeding back into the approach.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-007",
    kaId: "BAPM",
    taskId: "BAPM-1",
    stem: "Which is the single input to Plan Business Analysis Approach?",
    options: ["Requirements", "Needs", "Elicitation Results", "Solution Scope"],
    correctIndex: 1,
    explanation: "Needs is the only listed input; the approach is shaped early, before most other BA information exists.",
    difficulty: "easy",
  },
  {
    id: "Q-BAPM-008",
    kaId: "BAPM",
    taskId: "BAPM-3",
    stem: "A change request arrives. Which planning output should already define the path it follows to a decision?",
    options: ["Governance Approach", "Stakeholder Engagement Approach", "Future State Description", "Information Management Approach"],
    correctIndex: 0,
    explanation: "The Governance Approach defines the change control process and who decides — established during planning so changes don't stall later.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-009",
    kaId: "BAPM",
    taskId: "BAPM-2",
    stem: "Which technique is most directly used to analyze stakeholder influence and interest?",
    options: ["Process Modelling", "Financial Analysis", "Data Modelling", "Stakeholder List, Map, or Personas"],
    correctIndex: 3,
    explanation: "Stakeholder List, Map, or Personas (e.g. RACI, onion diagram) analyzes who is affected and their influence/attitude.",
    difficulty: "easy",
  },
  {
    id: "Q-BAPM-010",
    kaId: "BAPM",
    taskId: "BAPM-1",
    stem: "In BABOK, the level of formality and detail of BA work products is primarily decided in which task?",
    options: ["Conduct Elicitation", "Plan Business Analysis Approach", "Approve Requirements", "Verify Requirements"],
    correctIndex: 1,
    explanation: "Formality and level of detail are elements of Plan Business Analysis Approach.",
    difficulty: "easy",
  },
  {
    id: "Q-BAPM-011",
    kaId: "BAPM",
    taskId: "BAPM-1",
    stem: "A regulator requires a full audit trail of every requirement decision, but the delivery team works in two-week sprints. What should the business analysis approach reflect?",
    options: ["A purely adaptive approach with minimal documentation", "Force the team onto a predictive lifecycle", "A hybrid approach that keeps formal traceability while delivering iteratively", "Defer approach decisions until requirements stabilise"],
    correctIndex: 2,
    explanation: "The approach is selected to fit context, not ideology. BABOK explicitly supports predictive, adaptive, or hybrid; here regulatory formality raises traceability rigour without removing iterative delivery.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-012",
    kaId: "BAPM",
    taskId: "BAPM-1",
    stem: "Which element of Plan Business Analysis Approach determines how much documentation the initiative will produce?",
    options: ["Complexity and risk", "Acceptance", "Timing of business analysis work", "Formality and level of detail"],
    correctIndex: 3,
    explanation: "Formality and level of detail sets how rigorous and detailed BA deliverables will be. Timing covers when work happens; acceptance covers how the approach itself is agreed.",
    difficulty: "easy",
  },
  {
    id: "Q-BAPM-013",
    kaId: "BAPM",
    taskId: "BAPM-2",
    stem: "Stakeholder analysis identifies a regulator with high influence but little interest until go-live. What is the most appropriate engagement decision?",
    options: ["Keep them informed at targeted checkpoints so requirements satisfy the rules before build", "Treat them as the primary decision maker for all requirements", "Route all regulator contact through the sponsor", "Exclude them until go-live to conserve effort"],
    correctIndex: 0,
    explanation: "High influence with low current interest still means late objections can be fatal. Engagement is matched to influence and impact, not to how loud a stakeholder currently is.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-014",
    kaId: "BAPM",
    taskId: "BAPM-2",
    stem: "Which technique most directly supports the 'perform stakeholder analysis' element of Plan Stakeholder Engagement?",
    options: ["Financial Analysis", "Stakeholder List, Map, or Personas", "Estimation", "Backlog Management"],
    correctIndex: 1,
    explanation: "Stakeholder List, Map, or Personas is the technique for identifying stakeholders and characterising their influence, attitude, and authority.",
    difficulty: "easy",
  },
  {
    id: "Q-BAPM-015",
    kaId: "BAPM",
    taskId: "BAPM-3",
    stem: "Two senior managers each claim final approval rights over the same requirement set, and delivery has stalled. Which planning gap does this reveal?",
    options: ["An incomplete Change Strategy", "An incomplete Information Management Approach", "An incomplete Governance Approach", "An incomplete Elicitation Activity Plan"],
    correctIndex: 2,
    explanation: "Decision-making authority and approval rights are defined in the Governance Approach. Ambiguous approval authority is a governance failure, not an elicitation or information-management one.",
    difficulty: "hard",
  },
  {
    id: "Q-BAPM-016",
    kaId: "BAPM",
    taskId: "BAPM-3",
    stem: "The Governance Approach defines all of the following EXCEPT:",
    options: ["Who has authority to approve requirements", "How proposed changes are assessed and decided", "How requirements will be prioritized", "How individual elicitation sessions will be scheduled"],
    correctIndex: 3,
    explanation: "Scheduling specific elicitation activities belongs to Prepare for Elicitation. Governance covers decision making, change control, prioritization, and approvals.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-017",
    kaId: "BAPM",
    taskId: "BAPM-4",
    stem: "Six months after go-live, a new team cannot find the rationale behind a critical business rule. Which planning task should have prevented this?",
    options: ["Plan Business Analysis Information Management", "Plan Business Analysis Governance", "Maintain Requirements", "Plan Stakeholder Engagement"],
    correctIndex: 0,
    explanation: "Deciding how information is organised, stored, accessed, and kept reusable after the initiative is the purpose of Plan Business Analysis Information Management. Maintain Requirements executes against that plan.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-018",
    kaId: "BAPM",
    taskId: "BAPM-4",
    stem: "Which of these is NOT an input to Plan Business Analysis Information Management?",
    options: ["Stakeholder Engagement Approach", "Performance Objectives", "Business Analysis Approach", "Governance Approach"],
    correctIndex: 1,
    explanation: "Performance Objectives is an input to Identify Business Analysis Performance Improvements. Information management planning consumes the other three planning outputs.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-019",
    kaId: "BAPM",
    taskId: "BAPM-5",
    stem: "Midway through an initiative, stakeholders complain that workshops overrun and decisions keep getting reopened. What should the business analyst do first?",
    options: ["Rewrite the Governance Approach", "Escalate to the sponsor for more authority", "Assess business analysis performance against the agreed performance objectives and identify improvements", "Replace all remaining workshops with interviews"],
    correctIndex: 2,
    explanation: "Identify Business Analysis Performance Improvements is the task for diagnosing BA effectiveness against agreed objectives before changing tactics. Switching techniques first treats a symptom.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-020",
    kaId: "BAPM",
    taskId: "BAPM-5",
    stem: "Performance Objectives, as an input to Identify Business Analysis Performance Improvements, represent:",
    options: ["The results of Analyze Performance Measures", "The business analyst's personal development goals", "What the organization or stakeholders have defined as effective business analysis work", "The terms of the vendor contract"],
    correctIndex: 2,
    explanation: "Performance objectives are the agreed standard the BA work is measured against. Solution Performance Analysis measures the solution, not the analysis effort.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-021",
    kaId: "BAPM",
    taskId: "BAPM-4",
    stem: "Which business analysis planning output most directly constrains how requirements will later be traced?",
    options: ["Stakeholder Engagement Approach", "Information Management Approach", "Business Analysis Performance Assessment", "Governance Approach"],
    correctIndex: 1,
    explanation: "Traceability is an element of information management planning, and the Information Management Approach is an input to Define Requirements Architecture where tracing structure is realised.",
    difficulty: "hard",
  },
  {
    id: "Q-BAPM-022",
    kaId: "BAPM",
    taskId: "BAPM-1",
    stem: "A business analysis approach was agreed assuming a stable regulatory environment. New legislation lands mid-initiative. What is the BABOK-aligned response?",
    options: ["Revisit and adapt the approach, since it is reassessed as the initiative's context changes", "Pause all business analysis work pending legal advice", "Add the legislation to the product backlog and carry on unchanged", "Keep the agreed approach for consistency"],
    correctIndex: 0,
    explanation: "The business analysis approach is not frozen at kickoff. When complexity, risk, or regulatory context shifts materially, the approach is revisited and the downstream planning outputs adjusted.",
    difficulty: "hard",
  },
  {
    id: "Q-BAPM-023",
    kaId: "BAPM",
    taskId: "BAPM-2",
    stem: "The Stakeholder Engagement Approach is an input to which other planning task?",
    options: ["Identify Business Analysis Performance Improvements", "Analyze Current State", "Plan Business Analysis Approach", "Plan Business Analysis Governance"],
    correctIndex: 3,
    explanation: "Governance planning needs to know who the stakeholders are and how they collaborate before it can assign decision and approval authority.",
    difficulty: "easy",
  },
  {
    id: "Q-BAPM-024",
    kaId: "BAPM",
    taskId: "BAPM-3",
    stem: "The Governance Approach requires a change board for changes above five days of effort. A stakeholder asks the analyst to 'just slip in' a change, calling it a clarification. What is the best response?",
    options: ["Put it in the backlog for a later release without assessing it", "Add it, because clarifications are exempt from change control", "Assess the request against the agreed change process and route it accordingly", "Refuse to discuss it and escalate to the sponsor"],
    correctIndex: 2,
    explanation: "Whether something is a clarification or a change is itself a governance determination. The analyst applies the agreed process rather than accepting the requester's label.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-025",
    kaId: "BAPM",
    taskId: "BAPM-3",
    caseStudyId: "CS-002",
    stem: "At Northwind, weekly change requests are overwhelming the analyst and the fixed go-live date is at risk. Which planning output should be revisited first to restore control?",
    options: ["Elicitation Activity Plan", "Governance Approach", "Business Analysis Performance Assessment", "Requirements Architecture"],
    correctIndex: 1,
    explanation: "An uncontrolled flow of change requests is a change-control problem. The Governance Approach defines how changes are proposed, assessed, prioritized, and approved.",
    difficulty: "hard",
  },
  {
    id: "Q-BAPM-026",
    kaId: "BAPM",
    taskId: "BAPM-1",
    stem: "Estimation appears as a technique in Plan Business Analysis Approach primarily to:",
    options: ["Forecast the effort and timing of business analysis activities", "Calculate the net present value in the business case", "Rank requirements by value", "Size the solution for a vendor quotation"],
    correctIndex: 0,
    explanation: "In planning, estimation is applied to the analysis work itself — how long elicitation, modelling, and validation will take — not to the solution or its financials.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-027",
    kaId: "BAPM",
    taskId: "BAPM-2",
    stem: "An analyst discovers a group of night-shift operators who will use the solution daily but were never consulted. What is the correct classification and action?",
    options: ["Relevant only during Solution Evaluation", "Add them to the stakeholder list as 'informed' with no further engagement", "Out of scope, since they were not named in the project charter", "Stakeholders; update stakeholder analysis and engagement planning to include them"],
    correctIndex: 3,
    explanation: "Anyone whose needs the solution affects or who affects the change is a stakeholder. Discovery of a missed group triggers a revision of stakeholder analysis and the engagement approach.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-028",
    kaId: "BAPM",
    stem: "Which pair correctly matches a planning task to its output?",
    options: ["Plan Business Analysis Governance → Information Management Approach", "Plan Stakeholder Engagement → Governance Approach", "Plan Business Analysis Information Management → Information Management Approach", "Plan Business Analysis Approach → Performance Objectives"],
    correctIndex: 2,
    explanation: "Each planning task is named for its output: Approach → Business Analysis Approach, Stakeholder Engagement → Stakeholder Engagement Approach, Governance → Governance Approach, Information Management → Information Management Approach.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-029",
    kaId: "BAPM",
    taskId: "BAPM-4",
    stem: "Leadership wants all business analysis information in one shared tool, but some requirements contain personally identifiable data. Which information management element addresses this?",
    options: ["Level of abstraction", "Storage and access", "Requirements reuse", "Traceability"],
    correctIndex: 1,
    explanation: "Storage and access covers where information lives and who may see it, which is exactly where confidentiality and access restrictions are decided.",
    difficulty: "hard",
  },
  {
    id: "Q-BAPM-030",
    kaId: "BAPM",
    taskId: "BAPM-1",
    stem: "An analyst is deciding how detailed requirements documentation should be. Which factor from the business analysis approach most influences this decision?",
    options: ["Acceptance", "Timing of business analysis work", "Stakeholder communication needs", "Formality and level of detail"],
    correctIndex: 3,
    explanation: "Formality and level of detail is the element that governs documentation depth, driven by complexity, risk, regulation, and organizational norms.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-031",
    kaId: "BAPM",
    taskId: "BAPM-1",
    stem: "An adaptive initiative must still satisfy an external auditor. Which statement best reflects BABOK's position?",
    options: ["Formality can be raised selectively within an adaptive approach where risk or regulation demands it", "The initiative must convert to a predictive lifecycle", "Audit requirements fall outside business analysis scope", "Adaptive approaches cannot satisfy external audit"],
    correctIndex: 0,
    explanation: "Formality is a dial, not a lifecycle. An adaptive initiative can carry heavier documentation and approval rigour for the specific areas that regulation touches.",
    difficulty: "hard",
  },
  {
    id: "Q-BAPM-032",
    kaId: "BAPM",
    taskId: "BAPM-5",
    stem: "The Business Analysis Performance Assessment feeds back into which task as a guideline?",
    options: ["Measure Solution Performance", "Plan Business Analysis Approach", "Conduct Elicitation", "Define Design Options"],
    correctIndex: 1,
    explanation: "The assessment is a guideline for Plan Business Analysis Approach, closing the loop so lessons about how analysis is performed shape the next approach. It is also an input to Manage Stakeholder Collaboration.",
    difficulty: "easy",
  },
  {
    id: "Q-BAPM-033",
    kaId: "BAPM",
    taskId: "BAPM-3",
    stem: "Midway through an initiative, requirements are being approved by whoever happens to attend the meeting. What is the most accurate diagnosis?",
    options: ["An elicitation failure", "A traceability failure", "A failure to apply the decision-making and approval authority defined in the Governance Approach", "A prioritization failure"],
    correctIndex: 2,
    explanation: "Approval authority is a governance concern. Who may approve what, and by which process, is set in the Governance Approach and then applied in Approve Requirements.",
    difficulty: "medium",
  },
  {
    id: "Q-BAPM-034",
    kaId: "BAPM",
    taskId: "BAPM-1",
    stem: "Which technique best helps an analyst work out the sequence and dependencies of business analysis activities while planning the approach?",
    options: ["Balanced Scorecard", "Vendor Assessment", "Survey or Questionnaire", "Process Modelling"],
    correctIndex: 3,
    explanation: "Process modelling can be turned on the analysis work itself to lay out the sequence, dependencies, and handoffs of BA activities.",
    difficulty: "hard",
  },
  {
    id: "Q-BAPM-035",
    kaId: "BAPM",
    taskId: "BAPM-3",
    caseStudyId: "CS-001",
    stem: "MeridianBank's sponsor wants to skip formal requirements sign-off to hit a launch date, while compliance requires documented evidence of KYC decisions. What should the analyst recommend?",
    options: ["Tailor the Governance Approach so compliance-critical requirements keep formal approval while lower-risk ones use lighter confirmation", "Apply full formal sign-off to every requirement without exception", "Hand ownership of all requirements approval to compliance", "Skip sign-off now and document retrospectively"],
    correctIndex: 0,
    explanation: "Governance is tailored to risk. Differentiating approval rigour by risk satisfies compliance evidence needs without imposing uniform overhead that the schedule cannot absorb.",
    difficulty: "hard",
  },
];
