import type { Question } from "../types";

export const ecQuestions: Question[] = [
  {
    id: "Q-EC-001",
    kaId: "EC",
    taskId: "EC-1",
    stem: "Selecting elicitation techniques and arranging logistics happens in which task?",
    options: ["Conduct Elicitation", "Prepare for Elicitation", "Confirm Elicitation Results", "Communicate Business Analysis Information"],
    correctIndex: 1,
    explanation: "Prepare for Elicitation scopes the activity, selects techniques, and sets up logistics and materials.",
    difficulty: "easy",
  },
  {
    id: "Q-EC-002",
    kaId: "EC",
    taskId: "EC-2",
    caseStudyId: "CS-001",
    stem: "MeridianBank's onboarding process is undocumented and varies by branch. Which elicitation technique best captures how staff actually perform it today?",
    options: ["Observation (job shadowing)", "Document analysis", "Prototyping", "Survey via email"],
    correctIndex: 0,
    explanation: "Observation captures tacit, real-world process knowledge that isn't documented and that staff may not fully articulate.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-003",
    kaId: "EC",
    taskId: "EC-3",
    stem: "Checking captured elicitation results against their sources for accuracy and consistency is:",
    options: ["Approve Requirements", "Verify Requirements", "Validate Requirements", "Confirm Elicitation Results"],
    correctIndex: 3,
    explanation: "Confirm Elicitation Results checks the captured information against sources — distinct from RADD verification/validation.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-004",
    kaId: "EC",
    taskId: "EC-2",
    stem: "Interviews and workshops are examples of which elicitation approach?",
    options: ["Experiments", "Research", "Collaborative", "Observational"],
    correctIndex: 2,
    explanation: "Collaborative elicitation works directly with stakeholders; research uses existing materials; experiments include observation/prototyping/surveys.",
    difficulty: "easy",
  },
  {
    id: "Q-EC-005",
    kaId: "EC",
    taskId: "EC-2",
    stem: "What is the output of Conduct Elicitation?",
    options: ["Elicitation Activity Plan", "Elicitation Results (unconfirmed)", "Elicitation Results (confirmed)", "Requirements (specified and modeled)"],
    correctIndex: 1,
    explanation: "Conduct Elicitation yields unconfirmed results; they become confirmed only after Confirm Elicitation Results.",
    difficulty: "easy",
  },
  {
    id: "Q-EC-006",
    kaId: "EC",
    taskId: "EC-4",
    stem: "Communicate Business Analysis Information is fundamentally about:",
    options: ["Achieving a shared understanding among stakeholders", "Getting formal sign-off", "Storing requirements for reuse", "Transmitting documents on schedule"],
    correctIndex: 0,
    explanation: "The task ensures stakeholders have a common understanding — not mere transmission of documents.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-007",
    kaId: "EC",
    taskId: "EC-5",
    stem: "Why is Manage Stakeholder Collaboration considered ongoing rather than a one-time task?",
    options: ["Requirements always change", "It is a governance requirement", "Approvals must be re-signed weekly", "Stakeholder commitment, attitudes, and trust must be maintained throughout"],
    correctIndex: 3,
    explanation: "Collaboration is continuous work to keep stakeholders engaged and committed across the initiative.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-008",
    kaId: "EC",
    taskId: "EC-1",
    stem: "Which pair are inputs to Prepare for Elicitation?",
    options: ["Solution Scope and Change Strategy", "Business Objectives and Potential Value", "Needs and Stakeholder Engagement Approach", "Requirements and Designs"],
    correctIndex: 2,
    explanation: "Prepare for Elicitation takes Needs and the Stakeholder Engagement Approach as inputs.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-009",
    kaId: "EC",
    taskId: "EC-2",
    stem: "A survey/questionnaire is most appropriate when the BA needs:",
    options: ["Deep, nuanced understanding from one expert", "Input from many people at low cost", "To observe a process in action", "To reach consensus in a room"],
    correctIndex: 1,
    explanation: "Surveys reach many respondents cheaply and yield breadth/quantitative data, at the cost of depth.",
    difficulty: "easy",
  },
  {
    id: "Q-EC-010",
    kaId: "EC",
    taskId: "EC-3",
    stem: "Confirming elicitation results primarily reduces the cost of:",
    options: ["Tooling licenses", "Governance overhead", "Stakeholder onboarding", "Errors discovered late in the life cycle"],
    correctIndex: 3,
    explanation: "Catching inaccurate or inconsistent captured information early is far cheaper than fixing it after design/build.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-011",
    kaId: "EC",
    taskId: "EC-1",
    stem: "An analyst schedules a workshop, books the room, and sends an agenda, but does not decide what information the session must produce. Which element of Prepare for Elicitation was skipped?",
    options: ["Understand the scope of the elicitation activity", "Select elicitation techniques", "Set up logistics", "Secure supporting material"],
    correctIndex: 0,
    explanation: "Understanding the scope of the elicitation activity defines what information is needed and why, which is what makes technique selection and logistics purposeful rather than arbitrary.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-012",
    kaId: "EC",
    taskId: "EC-2",
    stem: "BABOK groups elicitation into three types. Running a controlled A/B test to learn which checkout flow users prefer is an example of which type?",
    options: ["Research", "Experiments", "Observation", "Collaborative"],
    correctIndex: 1,
    explanation: "Experiments generate information that was not previously known and cannot be obtained by asking or reading, such as A/B tests, proofs of concept, and prototypes used to learn.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-013",
    kaId: "EC",
    taskId: "EC-2",
    stem: "Reviewing existing process manuals and prior system documentation to understand the current state is which type of elicitation?",
    options: ["Confirmation", "Collaborative", "Research", "Experiments"],
    correctIndex: 2,
    explanation: "Research elicitation obtains information from materials or subject matter sources that already exist, including document analysis and benchmarking.",
    difficulty: "easy",
  },
  {
    id: "Q-EC-014",
    kaId: "EC",
    taskId: "EC-3",
    stem: "Two stakeholders gave conflicting accounts of the same approval step during separate interviews. What does Confirm Elicitation Results require the analyst to do?",
    options: ["Record both versions as approved requirements", "Escalate immediately to the change board", "Accept the more senior stakeholder's version", "Compare the results against other sources or stakeholders to resolve the inconsistency before using them"],
    correctIndex: 3,
    explanation: "Confirming results means checking them for consistency and accuracy against other elicitation results or stakeholders. Seniority is not a correctness test.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-015",
    kaId: "EC",
    taskId: "EC-3",
    stem: "Confirm Elicitation Results checks that information is accurate and consistent. What does it deliberately NOT do?",
    options: ["Establish that the requirements are correct and will deliver value", "Identify inconsistencies for follow-up", "Produce confirmed elicitation results", "Compare results against other sources"],
    correctIndex: 0,
    explanation: "Confirmation is a lightweight accuracy check with stakeholders. Establishing that requirements are correct and valuable is the work of Verify Requirements and Validate Requirements in RADD.",
    difficulty: "hard",
  },
  {
    id: "Q-EC-016",
    kaId: "EC",
    taskId: "EC-4",
    stem: "An analyst sends the same 80-page requirements package to executives, developers, and end users. Which principle of Communicate Business Analysis Information has been violated?",
    options: ["Information must always be delivered in writing", "The form and level of detail should be tailored to the audience and their communication needs", "All stakeholders must receive identical information for fairness", "Communication should be deferred until requirements are approved"],
    correctIndex: 1,
    explanation: "Communication is packaged for its audience. Executives need summarised value and decisions; developers need specification detail. Uniform delivery guarantees most recipients are poorly served.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-017",
    kaId: "EC",
    taskId: "EC-4",
    stem: "The output of Communicate Business Analysis Information is best described as:",
    options: ["Stakeholder Engagement", "Approved requirements", "Business analysis information that stakeholders have received and understood", "Confirmed elicitation results"],
    correctIndex: 2,
    explanation: "The output is business analysis information (communicated) — understanding has been reached, not merely that a document was sent. Approval belongs to Approve Requirements.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-018",
    kaId: "EC",
    taskId: "EC-5",
    stem: "A key stakeholder who was previously engaged stops attending sessions and replies late. What should the analyst do under Manage Stakeholder Collaboration?",
    options: ["Report them to the sponsor for non-compliance", "Reassign their requirements to another stakeholder", "Proceed without them and note the risk", "Understand why engagement has dropped and adjust the collaboration approach to re-establish the relationship"],
    correctIndex: 3,
    explanation: "Manage Stakeholder Collaboration is about maintaining working relationships through the initiative — diagnosing and repairing waning engagement rather than routing around it.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-019",
    kaId: "EC",
    taskId: "EC-5",
    stem: "Which pair are the inputs to Manage Stakeholder Collaboration?",
    options: ["Stakeholder Engagement Approach and Business Analysis Performance Assessment", "Needs and Business Analysis Approach", "Elicitation Activity Plan and Needs", "Governance Approach and Requirements"],
    correctIndex: 0,
    explanation: "The engagement approach says how collaboration was planned; the performance assessment says how the analysis work, including collaboration, is actually going.",
    difficulty: "hard",
  },
  {
    id: "Q-EC-020",
    kaId: "EC",
    taskId: "EC-1",
    stem: "Users describe their process one way, but the analyst suspects undocumented workarounds are common. Which elicitation technique is most appropriate?",
    options: ["Observation", "Brainstorming", "Document Analysis", "Survey or Questionnaire"],
    correctIndex: 0,
    explanation: "Observation surfaces the gap between described and actual behaviour, including tacit knowledge and workarounds that people omit when describing their own work.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-021",
    kaId: "EC",
    taskId: "EC-1",
    stem: "An analyst must gather input from 400 field staff across 30 locations within two weeks. Which technique is most appropriate as the primary method?",
    options: ["Focus group with all 400", "Interviews", "Workshops", "Survey or Questionnaire"],
    correctIndex: 3,
    explanation: "Surveys scale to large, dispersed populations under time pressure. Interviews and workshops give richer data but cannot cover that population in the window.",
    difficulty: "easy",
  },
  {
    id: "Q-EC-022",
    kaId: "EC",
    taskId: "EC-2",
    stem: "During a workshop, one executive dominates and junior staff stop contributing. What is the analyst's most appropriate action?",
    options: ["Record only the executive's input as authoritative", "Let the discussion run, since the executive has decision authority", "Actively facilitate to draw out quieter participants and manage airtime", "End the session and switch permanently to interviews"],
    correctIndex: 2,
    explanation: "Facilitation is core to collaborative elicitation. The analyst manages group dynamics so the session produces the range of information it was designed to elicit.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-023",
    kaId: "EC",
    taskId: "EC-2",
    caseStudyId: "CS-001",
    stem: "MeridianBank's onboarding process is undocumented and varies by branch. Which combination of techniques best establishes what actually happens today?",
    options: ["Brainstorming and prototyping", "Observation at multiple branches plus interviews with branch staff", "Survey of executives plus financial analysis", "Vendor assessment plus benchmarking"],
    correctIndex: 1,
    explanation: "With no documentation and known variation, the analyst must see the work and talk to those doing it. Observation captures actual practice; interviews capture reasons and exceptions.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-024",
    kaId: "EC",
    taskId: "EC-1",
    stem: "Which is the correct output of Prepare for Elicitation?",
    options: ["Elicitation Activity Plan", "Stakeholder Engagement Approach", "Business Analysis Information", "Elicitation Results (unconfirmed)"],
    correctIndex: 0,
    explanation: "Prepare for Elicitation produces the Elicitation Activity Plan, which then becomes the sole input to Conduct Elicitation.",
    difficulty: "easy",
  },
  {
    id: "Q-EC-025",
    kaId: "EC",
    taskId: "EC-2",
    stem: "A stakeholder repeatedly answers 'the system should just work properly'. What should the analyst do?",
    options: ["Discard the input as unusable", "Replace it with the analyst's own assumption of intent", "Record the statement verbatim as a requirement", "Probe for the specific conditions, measures, and failures behind the statement"],
    correctIndex: 3,
    explanation: "Eliciting means drawing out. Vague statements are prompts for deeper questioning to reach the measurable need beneath, not raw material to transcribe or discard.",
    difficulty: "easy",
  },
  {
    id: "Q-EC-026",
    kaId: "EC",
    taskId: "EC-3",
    stem: "Which statement best distinguishes Confirm Elicitation Results from Verify Requirements?",
    options: ["Confirmation happens after approval; verification happens before it", "Confirmation checks quality of specification; verification checks stakeholder agreement", "Confirmation checks that captured information matches what stakeholders meant; verification checks that specified requirements are of sufficient quality", "They are interchangeable terms"],
    correctIndex: 2,
    explanation: "Confirmation is an accuracy check on raw elicitation output. Verification is a quality check on requirements once they are specified and modelled.",
    difficulty: "hard",
  },
  {
    id: "Q-EC-027",
    kaId: "EC",
    taskId: "EC-5",
    stem: "The output of Manage Stakeholder Collaboration is:",
    options: ["Stakeholder Engagement Approach", "Stakeholder Engagement", "Business Analysis Performance Assessment", "Business Analysis Information (communicated)"],
    correctIndex: 1,
    explanation: "The output is Stakeholder Engagement — willing participation sustained through the initiative. The Approach is the plan produced earlier in BAPM.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-028",
    kaId: "EC",
    taskId: "EC-2",
    stem: "An analyst builds a throwaway screen mock-up so users can react to a proposed workflow. Elicitation is being used here primarily to:",
    options: ["Draw out requirements that stakeholders cannot articulate abstractly", "Obtain formal approval of the design", "Measure solution performance", "Confirm previously gathered results"],
    correctIndex: 0,
    explanation: "Prototyping as elicitation surfaces needs people cannot express in the abstract. It is generative, not an approval or evaluation mechanism.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-029",
    kaId: "EC",
    taskId: "EC-4",
    stem: "A stakeholder group disputes requirements they were sent weeks earlier, saying they never understood them. Which task was performed ineffectively?",
    options: ["Prioritize Requirements", "Trace Requirements", "Conduct Elicitation", "Communicate Business Analysis Information"],
    correctIndex: 3,
    explanation: "Communication is complete only when stakeholders understand the information. Transmission without comprehension has not achieved the task's purpose.",
    difficulty: "medium",
  },
  {
    id: "Q-EC-030",
    kaId: "EC",
    taskId: "EC-5",
    caseStudyId: "CS-001",
    stem: "MeridianBank's branch staff fear the mobile channel makes them irrelevant, and are withholding process detail. What is the analyst's most effective approach?",
    options: ["Bypass branch staff and rely on the sponsor's description of the process", "Address the underlying concern openly and involve them in shaping the future state to rebuild collaboration", "Mandate their attendance through the sponsor", "Document the process from system logs instead"],
    correctIndex: 1,
    explanation: "Resistance rooted in perceived threat is managed by addressing the concern and giving stakeholders a genuine role, not by coercion or by routing around the people who hold the knowledge.",
    difficulty: "hard",
  },
];
