import type { Question } from "../types";

export const raddQuestions: Question[] = [
  {
    id: "Q-RADD-001",
    kaId: "RADD",
    taskId: "RADD-2",
    stem: "Confirming that a requirement is atomic, testable, and unambiguous is part of:",
    options: ["Verify Requirements", "Approve Requirements", "Trace Requirements", "Validate Requirements"],
    correctIndex: 0,
    explanation: "Verify Requirements checks quality characteristics — building the requirements right.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-002",
    kaId: "RADD",
    taskId: "RADD-3",
    stem: "Confirming that a requirement actually delivers value and aligns to business objectives is:",
    options: ["Verify Requirements", "Validate Requirements", "Specify and Model Requirements", "Maintain Requirements"],
    correctIndex: 1,
    explanation: "Validate Requirements ensures alignment to business needs and value — building the right requirements.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-003",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "Turning confirmed elicitation results into structured models and specifications is the purpose of:",
    options: ["Define Design Options", "Verify Requirements", "Specify and Model Requirements", "Define Requirements Architecture"],
    correctIndex: 2,
    explanation: "Specify and Model Requirements analyzes and represents requirements/designs at appropriate abstraction.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-004",
    kaId: "RADD",
    taskId: "RADD-5",
    caseStudyId: "CS-002",
    stem: "Northwind must decide between a custom integration and a vendor connector. In BABOK terms, describing and comparing these is part of:",
    options: ["Specify and Model Requirements", "Define Requirements Architecture", "Validate Requirements", "Define Design Options"],
    correctIndex: 3,
    explanation: "Define Design Options describes solution approaches (create vs. purchase vs. combine) and allocates requirements to components.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-005",
    kaId: "RADD",
    taskId: "RADD-6",
    stem: "When recommending a solution among options, the recommendation should be driven primarily by:",
    options: ["Highest potential value (benefits net of costs and risk)", "Vendor preference", "Shortest timeline", "Lowest cost"],
    correctIndex: 0,
    explanation: "Analyze Potential Value and Recommend Solution weighs benefits against costs and risk — value, not cost alone.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-006",
    kaId: "RADD",
    taskId: "RADD-4",
    stem: "Structuring requirements using viewpoints and views so they fit together coherently is:",
    options: ["Define Design Options", "Define Requirements Architecture", "Trace Requirements", "Prioritize Requirements"],
    correctIndex: 1,
    explanation: "Define Requirements Architecture organizes requirements into a coherent whole using viewpoints and views.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-007",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "Performance, security, and usability requirements are classified as:",
    options: ["Business requirements", "Functional requirements", "Non-functional requirements", "Transition requirements"],
    correctIndex: 2,
    explanation: "These quality attributes are non-functional requirements ('how well' rather than 'what').",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-008",
    kaId: "RADD",
    taskId: "RADD-3",
    stem: "Which guideline/input is essential to validate requirements against?",
    options: ["Elicitation Activity Plan", "Information Management Approach", "Proposed Change", "Future State Description / Business Objectives"],
    correctIndex: 3,
    explanation: "Validation checks alignment to business objectives, the future state, and potential value.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-009",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "A 'usable representation of a need' is BABOK's definition of a:",
    options: ["Requirement", "Stakeholder", "Solution component", "Design"],
    correctIndex: 0,
    explanation: "A requirement represents a need; a design represents a solution. The boundary is contextual.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-010",
    kaId: "RADD",
    taskId: "RADD-5",
    stem: "The three broad solution approaches when defining design options are:",
    options: ["Avoid, transfer, accept", "Build, test, deploy", "Create, purchase, or a combination", "Plan, do, check"],
    correctIndex: 2,
    explanation: "Solution approaches are create (build), purchase (buy/COTS), or a combination.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-011",
    kaId: "RADD",
    taskId: "RADD-6",
    stem: "Which pair are the inputs to Analyze Potential Value and Recommend Solution?",
    options: ["Needs and Elicitation Results", "Potential Value and Design Options", "Requirements and Designs", "Change Strategy and Solution Scope"],
    correctIndex: 1,
    explanation: "The task takes Potential Value and Design Options and outputs a Solution Recommendation.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-012",
    kaId: "RADD",
    taskId: "RADD-2",
    stem: "Reviews and checklists are most associated with which RADD task?",
    options: ["Verify Requirements", "Define Design Options", "Define Requirements Architecture", "Specify and Model Requirements"],
    correctIndex: 0,
    explanation: "Verify Requirements uses reviews, checklists, and acceptance/evaluation criteria to confirm quality.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-013",
    kaId: "RADD",
    taskId: "RADD-1",
    caseStudyId: "CS-002",
    stem: "Northwind's warehouse, finance, and logistics stakeholders need different views of the same requirements. Which technique set best serves this in Specify and Model Requirements?",
    options: ["Survey only", "Vendor Assessment", "Financial Analysis only", "Models such as process models, data models, and use cases for different viewpoints"],
    correctIndex: 3,
    explanation: "Different models (process, data, use cases) present requirements from the viewpoints each audience needs.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-014",
    kaId: "RADD",
    taskId: "RADD-4",
    stem: "Which input does Define Requirements Architecture rely on to know how information should be organized and reused?",
    options: ["Stakeholder Engagement Approach", "Elicitation Activity Plan", "Information Management Approach", "Risk Analysis Results"],
    correctIndex: 2,
    explanation: "The Information Management Approach (from BAPM-4) guides how the architecture organizes and relates requirements.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-015",
    kaId: "RADD",
    taskId: "RADD-3",
    stem: "An agile team writes acceptance criteria for each user story. In BABOK this most supports which task?",
    options: ["Measure Solution Performance", "Validate Requirements", "Trace Requirements", "Plan Business Analysis Governance"],
    correctIndex: 1,
    explanation: "Acceptance/evaluation criteria help validate that the requirement delivers the intended value.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-016",
    kaId: "RADD",
    taskId: "RADD-5",
    stem: "Design Options take which validated/prioritized artifact plus the requirements architecture and change strategy as inputs?",
    options: ["Requirements", "Needs", "Solution Performance Measures", "Proposed Change"],
    correctIndex: 0,
    explanation: "Define Design Options takes Change Strategy, Requirements (validated, prioritized), and Requirements Architecture.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-017",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "What fundamentally distinguishes a requirement from a design in BABOK?",
    options: ["Requirements come from business stakeholders and designs come from developers", "Requirements are text and designs are diagrams", "Requirements are high-level and designs are detailed", "A requirement expresses a need; a design expresses a solution to that need"],
    correctIndex: 3,
    explanation: "The distinction is intent, not format or level of detail. A wireframe can be a requirement if it states a need; a sentence can be a design if it prescribes a solution.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-018",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "'The system shall use a PostgreSQL database' is best classified as:",
    options: ["A transition requirement", "A business requirement", "A design element, since it prescribes how rather than what", "A non-functional requirement"],
    correctIndex: 2,
    explanation: "Naming a specific technology prescribes a solution. Unless it is an imposed constraint, it is a design decision rather than a statement of need.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-019",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "Requirements that describe capabilities needed only during the move from current to future state, such as data migration and parallel running, are:",
    options: ["Stakeholder requirements", "Transition requirements", "Non-functional requirements", "Business requirements"],
    correctIndex: 1,
    explanation: "Transition requirements are temporary by definition — they cease to apply once the future state is reached, which is why they are classified separately.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-020",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "'The system shall process 10,000 transactions per hour with 99.9% availability' is which class of requirement?",
    options: ["Functional", "Non-functional (quality of service)", "Business", "Transition"],
    correctIndex: 1,
    explanation: "Non-functional requirements describe qualities and conditions of the solution — performance, availability, security, usability — rather than the behaviour it performs.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-021",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "BABOK groups models into categories. A business process diagram showing the sequence of steps to approve a loan belongs to which category?",
    options: ["People and roles", "Rationale", "Activity flow", "Data and information"],
    correctIndex: 2,
    explanation: "Activity flow models depict sequences of actions and events. People and roles models depict organizational relationships; data models depict information structure.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-022",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "A decision tree showing why a claim is routed to manual review belongs to which model category?",
    options: ["Activity flow", "Capability", "People and roles", "Rationale"],
    correctIndex: 3,
    explanation: "Rationale models capture the reasoning behind decisions and rules — decision analysis, business rules, and root cause structures.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-023",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "An entity relationship diagram of customer, account, and transaction belongs to which model category?",
    options: ["Data and information", "Capability", "Rationale", "Activity flow"],
    correctIndex: 0,
    explanation: "Data and information models describe the structure, attributes, and relationships of the information the solution uses.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-024",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "Why does BABOK recommend using multiple model types for the same requirement set?",
    options: ["To satisfy documentation standards", "Because different models expose different aspects, and gaps visible in one view may be invisible in another", "Because stakeholders prefer variety", "To increase the volume of deliverables"],
    correctIndex: 1,
    explanation: "Each model is a partial view. Combining process, data, rule, and role views surfaces inconsistencies and omissions that a single representation would conceal.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-025",
    kaId: "RADD",
    taskId: "RADD-2",
    stem: "Verify Requirements checks that requirements are:",
    options: ["Traced to design elements", "Aligned with business objectives and will deliver value", "Of sufficient quality — unambiguous, testable, consistent, complete, and feasible", "Approved by the sponsor"],
    correctIndex: 2,
    explanation: "Verification is a quality check on the specification itself. Alignment with business value is the separate concern of Validate Requirements.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-026",
    kaId: "RADD",
    taskId: "RADD-3",
    stem: "A requirement is perfectly written, testable, and unambiguous, but does not support any stated business objective. Which check would catch this?",
    options: ["Trace Requirements", "Approve Requirements", "Verify Requirements", "Validate Requirements"],
    correctIndex: 3,
    explanation: "Validation asks whether the requirement delivers business value and aligns with the objectives. A flawlessly specified requirement can still be the wrong requirement.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-027",
    kaId: "RADD",
    taskId: "RADD-2",
    stem: "Which characteristic of requirements quality means a requirement describes a single, indivisible need?",
    options: ["Atomic", "Complete", "Consistent", "Concise"],
    correctIndex: 0,
    explanation: "Atomic requirements stand alone and cannot be usefully decomposed. Bundled requirements are hard to trace, prioritize, test, and change independently.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-028",
    kaId: "RADD",
    taskId: "RADD-2",
    stem: "A requirement reads 'the system should respond quickly'. Which quality characteristics does it most clearly fail?",
    options: ["Atomic and concise", "Unambiguous and testable", "Prioritized and complete", "Consistent and feasible"],
    correctIndex: 1,
    explanation: "'Quickly' admits multiple interpretations and provides no threshold to test against. A measurable target makes it both unambiguous and testable.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-029",
    kaId: "RADD",
    taskId: "RADD-2",
    stem: "Which technique is most directly used to examine requirements for quality defects with a group of peers or stakeholders?",
    options: ["Estimation", "Business Capability Analysis", "Reviews", "Prototyping"],
    correctIndex: 2,
    explanation: "Reviews — walkthroughs, inspections, and peer reviews — are the core verification technique for detecting quality defects before build.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-030",
    kaId: "RADD",
    taskId: "RADD-3",
    stem: "Validate Requirements primarily involves:",
    options: ["Confirming that requirements and designs deliver business value and align with the business objectives and desired future state", "Verifying that developers can build them", "Obtaining formal sign-off", "Checking spelling and formatting"],
    correctIndex: 0,
    explanation: "Validation tests worth. It asks whether building this will actually move the enterprise toward the value it set out to capture.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-031",
    kaId: "RADD",
    taskId: "RADD-3",
    stem: "Which technique is most directly associated with defining the conditions a requirement must meet to be accepted as delivered?",
    options: ["Functional Decomposition", "Organizational Modelling", "Document Analysis", "Acceptance and Evaluation Criteria"],
    correctIndex: 3,
    explanation: "Acceptance and evaluation criteria make validation concrete by stating in advance what 'satisfied' means for a requirement or solution.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-032",
    kaId: "RADD",
    taskId: "RADD-4",
    stem: "The purpose of Define Requirements Architecture is to:",
    options: ["Select a vendor platform", "Design the technical architecture of the solution", "Structure requirements so they work together as a coherent whole and support the solution scope", "Prioritize requirements for release"],
    correctIndex: 2,
    explanation: "Requirements architecture organises requirements and their relationships into a structure that can be shown complete and consistent. It is not the solution's technical architecture.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-033",
    kaId: "RADD",
    taskId: "RADD-4",
    stem: "Which set are the inputs to Define Requirements Architecture?",
    options: ["Elicitation Results and Needs", "Information Management Approach, Requirements, and Solution Scope", "Change Strategy, Requirements, and Requirements Architecture", "Potential Value and Design Options"],
    correctIndex: 1,
    explanation: "The information management plan sets the organising rules, the requirements are what gets structured, and the solution scope bounds what belongs in the structure.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-034",
    kaId: "RADD",
    taskId: "RADD-4",
    stem: "In requirements architecture, a 'viewpoint' is best described as:",
    options: ["A convention defining how a set of requirements is represented for a particular audience or concern", "The final approved architecture", "A traceability matrix", "A stakeholder's personal opinion of a requirement"],
    correctIndex: 0,
    explanation: "A viewpoint is the convention; the view is the resulting representation produced by applying it. Different concerns require different viewpoints over the same requirement set.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-035",
    kaId: "RADD",
    taskId: "RADD-4",
    stem: "An analyst discovers that two requirements from different stakeholder groups contradict each other. Which task is designed to surface this?",
    options: ["Conduct Elicitation", "Prioritize Requirements", "Measure Solution Performance", "Define Requirements Architecture, through relating and verifying requirement relationships"],
    correctIndex: 3,
    explanation: "Structuring requirements and examining their relationships exposes conflicts, gaps, and overlaps that are invisible when requirements are held as a flat list.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-036",
    kaId: "RADD",
    taskId: "RADD-5",
    stem: "Which set are the inputs to Define Design Options?",
    options: ["Solution Scope and Business Objectives", "Elicitation Results and Needs", "Change Strategy, validated and prioritized Requirements, and Requirements Architecture", "Potential Value and Design Options"],
    correctIndex: 2,
    explanation: "Design options are shaped by the agreed route of change, the requirements that matter most and have been validated, and the structure that holds them together.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-037",
    kaId: "RADD",
    taskId: "RADD-5",
    stem: "Deciding between building in-house, buying a package, or outsourcing is which element of Define Design Options?",
    options: ["Identify improvement opportunities", "Define solution approaches", "Requirements allocation", "Assess trade-offs"],
    correctIndex: 1,
    explanation: "Defining solution approaches settles the fundamental delivery route — build, buy, outsource, or a combination — before detailed components are allocated.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-038",
    kaId: "RADD",
    taskId: "RADD-5",
    stem: "Requirements allocation within Define Design Options means:",
    options: ["Assigning requirements to solution components and releases", "Ranking requirements by value", "Assigning requirements to stakeholders for approval", "Verifying requirements quality"],
    correctIndex: 0,
    explanation: "Allocation distributes requirements across the components and increments of a design option so each option can be assessed as a coherent whole.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-039",
    kaId: "RADD",
    taskId: "RADD-5",
    caseStudyId: "CS-002",
    stem: "Northwind must choose between a custom integration and a vendor connector for the logistics provider. Which technique most directly supports evaluating the vendor route?",
    options: ["Data Flow Diagrams", "Observation", "Lessons Learned", "Vendor Assessment"],
    correctIndex: 3,
    explanation: "Vendor Assessment evaluates a supplier's capability, viability, and fit against the requirements, which is precisely what a buy decision turns on.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-040",
    kaId: "RADD",
    taskId: "RADD-6",
    stem: "Which pair are the inputs to Analyze Potential Value and Recommend Solution?",
    options: ["Requirements and Designs", "Change Strategy and Solution Scope", "Business Objectives and Implemented Solution", "Potential Value and Design Options"],
    correctIndex: 3,
    explanation: "The task compares each design option against the potential value identified in Strategy Analysis, then recommends the option that best delivers it.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-041",
    kaId: "RADD",
    taskId: "RADD-6",
    stem: "The output of Analyze Potential Value and Recommend Solution is:",
    options: ["Solution Recommendation", "Solution Scope", "Recommended Actions", "Design Options"],
    correctIndex: 0,
    explanation: "The task produces a Solution Recommendation. Recommended Actions is the output of Recommend Actions to Increase Solution Value in Solution Evaluation.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-042",
    kaId: "RADD",
    taskId: "RADD-6",
    stem: "Option A delivers the highest financial return but requires capabilities the organization lacks. Option B delivers less return but is achievable. What should the analyst do?",
    options: ["Recommend Option A because value is the deciding factor", "Assess the trade-offs, including feasibility and risk, and recommend on expected realisable value", "Recommend Option B automatically as the safe choice", "Present both without a recommendation"],
    correctIndex: 1,
    explanation: "Potential value that the enterprise cannot actually capture is not value. The task explicitly includes assessing trade-offs among options before recommending.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-043",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "Which technique is most appropriate for modelling the interactions between an actor and a system to achieve a goal, including alternate flows?",
    options: ["Financial Analysis", "Risk Analysis and Management", "Use Cases and Scenarios", "Balanced Scorecard"],
    correctIndex: 2,
    explanation: "Use cases and scenarios capture goal-directed interactions including main, alternate, and exception flows, making system behaviour explicit.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-044",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "An analyst needs to capture the conditions under which a discount applies, independent of any system that enforces it. Which technique fits best?",
    options: ["Prototyping", "Interface Analysis", "Scope Modelling", "Business Rules Analysis"],
    correctIndex: 3,
    explanation: "Business rules analysis expresses rules as reusable statements of policy and logic, separate from the processes or systems that implement them.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-045",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "Breaking a complex business capability into progressively smaller sub-capabilities is which technique?",
    options: ["Functional Decomposition", "Root Cause Analysis", "Data Modelling", "Benchmarking"],
    correctIndex: 0,
    explanation: "Functional decomposition breaks a whole into constituent parts to reduce complexity and make each part analysable and estimable.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-046",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "Which technique is most directly used to identify and define the interactions between the solution and external systems or organizations?",
    options: ["Estimation", "Interface Analysis", "Organizational Modelling", "Lessons Learned"],
    correctIndex: 1,
    explanation: "Interface analysis identifies the boundaries between the solution and its environment, and the information exchanged across them.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-047",
    kaId: "RADD",
    taskId: "RADD-1",
    caseStudyId: "CS-004",
    stem: "At the Benefits Agency, eligibility rules change with each legislative session. How should the analyst specify these rules to minimise future rework?",
    options: ["Capture them only in user stories for the current release", "Embed the rules inside the process model steps", "Specify them as separately maintained business rules referenced by the processes that apply them", "Write them directly into the system design"],
    correctIndex: 2,
    explanation: "Separating rules from processes means a legislative change touches one rule definition rather than every process, model, and story that applies it.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-048",
    kaId: "RADD",
    taskId: "RADD-2",
    caseStudyId: "CS-004",
    stem: "A reviewer finds that two Benefits Agency requirements specify different waiting periods for the same claim type. Which quality characteristic has been violated?",
    options: ["Concise", "Prioritized", "Feasible", "Consistent"],
    correctIndex: 3,
    explanation: "Consistency means requirements do not contradict one another and use terms uniformly. Contradictory values for the same concept is the textbook failure.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-049",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "Which statement about levels of abstraction is most accurate?",
    options: ["Both requirements and designs can exist at any level of abstraction", "Abstraction level determines whether something is a requirement", "Requirements exist only at high levels of abstraction", "Designs exist only at low levels of abstraction"],
    correctIndex: 0,
    explanation: "Abstraction is orthogonal to the requirement/design distinction. What separates them is whether the statement expresses a need or prescribes a solution.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-050",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "BABOK describes requirements and designs as existing in a repeating cycle. This means:",
    options: ["The cycle applies only to adaptive approaches", "Requirements are always finished before design begins", "A design decision at one level becomes the requirement that shapes the next level of detail", "Designs replace requirements once approved"],
    correctIndex: 2,
    explanation: "Choosing a design creates new needs at the next level down. The pattern of need then solution then new need repeats through progressive elaboration.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-051",
    kaId: "RADD",
    taskId: "RADD-3",
    stem: "A stakeholder insists on a requirement that duplicates functionality already delivered elsewhere at lower cost. What does validation demand?",
    options: ["Accept it, since the stakeholder is the authority", "Challenge whether it delivers incremental value given the existing capability", "Reject it without analysis", "Defer it to Solution Evaluation"],
    correctIndex: 1,
    explanation: "Validation tests whether the requirement delivers value in context. Duplicating an existing capability typically adds cost without adding value, and that must be surfaced.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-052",
    kaId: "RADD",
    taskId: "RADD-2",
    stem: "Which statement correctly orders verification and approval?",
    options: ["Requirements are verified, then submitted for approval", "Verification and approval are the same activity", "Approval precedes both verification and validation", "Requirements are approved, then verified"],
    correctIndex: 0,
    explanation: "Approve Requirements takes Requirements (verified) as its input. Quality is established before stakeholders are asked to commit.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-053",
    kaId: "RADD",
    taskId: "RADD-1",
    caseStudyId: "CS-006",
    stem: "SwiftFreight's order volumes are projected to grow tenfold in 18 months. Which requirement class most needs explicit specification?",
    options: ["Business requirements", "Stakeholder requirements", "Transition requirements", "Non-functional requirements covering scalability and throughput"],
    correctIndex: 3,
    explanation: "Growth projections translate into quality-of-service demands. Leaving scalability implicit is how systems pass acceptance and then fail under real load.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-054",
    kaId: "RADD",
    taskId: "RADD-1",
    caseStudyId: "CS-006",
    stem: "SwiftFreight must exchange shipment data with four carrier systems, each with its own format. Which technique should the analyst apply first?",
    options: ["Brainstorming", "Lessons Learned", "Interface Analysis", "Balanced Scorecard"],
    correctIndex: 2,
    explanation: "Interface analysis defines each boundary, the data crossing it, and the conditions of exchange — the prerequisite for designing any integration.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-055",
    kaId: "RADD",
    taskId: "RADD-4",
    caseStudyId: "CS-007",
    stem: "Northgate University is consolidating three student systems whose requirements were written by separate faculties using different terms for the same concepts. What should the analyst establish first?",
    options: ["A prioritized backlog", "A glossary and a requirements architecture that reconciles terminology and relationships", "A vendor shortlist", "Acceptance criteria for each requirement"],
    correctIndex: 1,
    explanation: "Inconsistent vocabulary makes conflicts and duplicates invisible. A shared glossary plus a structure relating requirements is what makes the combined set analysable.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-056",
    kaId: "RADD",
    taskId: "RADD-4",
    stem: "Which technique is most directly used to establish and maintain agreed definitions of terms across a requirement set?",
    options: ["Glossary", "Estimation", "Prototyping", "Financial Analysis"],
    correctIndex: 0,
    explanation: "A glossary fixes shared meaning for domain terms, which is foundational when multiple groups contribute requirements to one architecture.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-057",
    kaId: "RADD",
    taskId: "RADD-4",
    stem: "Completeness in requirements architecture means:",
    options: ["Every requirement has been implemented", "All models have been drawn", "Every requirement has been approved", "The requirement set covers the solution scope with no gaps, and every requirement belongs in that scope"],
    correctIndex: 3,
    explanation: "Completeness is judged against scope in both directions — nothing needed is missing, and nothing present falls outside what the solution is meant to cover.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-058",
    kaId: "RADD",
    taskId: "RADD-5",
    caseStudyId: "CS-005",
    stem: "Cedarview Health is weighing a configurable commercial scheduling package against a custom build. Which element of Define Design Options does this decision belong to?",
    options: ["Analyze potential value", "Requirements allocation", "Define solution approaches", "Identify improvement opportunities"],
    correctIndex: 2,
    explanation: "Buy versus build is the solution approach decision, settled before requirements are allocated to the components of each candidate option.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-059",
    kaId: "RADD",
    taskId: "RADD-5",
    caseStudyId: "CS-005",
    stem: "The commercial package meets 80% of Cedarview's requirements out of the box. What must the analyst do before this can be compared with the custom option?",
    options: ["Drop the unmet 20% of requirements", "Determine how the unmet requirements would be addressed — configuration, extension, process change, or acceptance of the gap", "Assume the vendor will build the remainder", "Recommend the package on cost alone"],
    correctIndex: 1,
    explanation: "A design option must be complete enough to evaluate. The treatment of the gap is part of the option, and it is often where the real cost and risk sit.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-060",
    kaId: "RADD",
    taskId: "RADD-5",
    stem: "'Identify improvement opportunities' within Define Design Options refers to:",
    options: ["Improvements to the business analysis process", "Opportunities to increase efficiency or capability beyond simply meeting the stated requirements", "Defect fixes in the current system", "Improvements to the requirements architecture"],
    correctIndex: 1,
    explanation: "Design work can surface gains the requirements never asked for — automation, reduced handoffs, removed duplication — and these are legitimate parts of an option.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-061",
    kaId: "RADD",
    taskId: "RADD-6",
    stem: "Which technique most directly supports quantifying the expected costs and benefits of competing design options?",
    options: ["Glossary", "Item Tracking", "Financial Analysis", "Observation"],
    correctIndex: 2,
    explanation: "Financial analysis assesses the cost and benefit of options in monetary terms, supporting the value comparison the recommendation rests on.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-062",
    kaId: "RADD",
    taskId: "RADD-6",
    stem: "In Analyze Potential Value and Recommend Solution, 'value' should be understood as:",
    options: ["The cost of the solution", "The number of requirements satisfied", "Financial return only", "The benefit delivered to stakeholders in a context, which may be financial or non-financial"],
    correctIndex: 3,
    explanation: "BABOK treats value broadly — it can be a reduced risk, a regulatory obligation met, or an improved experience, not only money.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-063",
    kaId: "RADD",
    taskId: "RADD-2",
    stem: "Which is the correct output pair of Verify Requirements?",
    options: ["Requirements (verified) and Designs (verified)", "Requirements (validated) and Designs (validated)", "Requirements (approved) and Designs (approved)", "Requirements (traced) and Designs (traced)"],
    correctIndex: 0,
    explanation: "Verification applies to both requirements and designs, producing verified versions of each. Validation and approval are separate downstream states.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-064",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "Which model category would a RACI matrix belong to?",
    options: ["Rationale", "People and roles", "Activity flow", "Data and information"],
    correctIndex: 1,
    explanation: "People and roles models describe organizational units, roles, responsibilities, and their relationships to activities.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-065",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "An analyst writes: 'As a claims handler, I want to see a customer's full history on one screen so that I can assess risk without switching systems.' This is an example of:",
    options: ["A transition requirement", "A non-functional requirement", "A user story capturing a stakeholder requirement with its rationale", "A design element"],
    correctIndex: 2,
    explanation: "The role-need-benefit form expresses a stakeholder requirement and carries its rationale, without prescribing how the screen is built.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-066",
    kaId: "RADD",
    taskId: "RADD-3",
    caseStudyId: "CS-007",
    stem: "Northgate's registrar requests a feature that serves only one faculty and does not support the consolidation objective. What should the analyst do?",
    options: ["Silently drop it", "Reclassify it as a non-functional requirement", "Include it, since the registrar is a senior stakeholder", "Surface the misalignment with the business objectives so a deliberate decision is made about its value"],
    correctIndex: 3,
    explanation: "Validation makes alignment visible so stakeholders decide with full information. The analyst neither rubber-stamps nor unilaterally discards.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-067",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "Which technique is most appropriate for representing how data moves between processes, stores, and external entities?",
    options: ["Data Flow Diagrams", "Balanced Scorecard", "SWOT Analysis", "Vendor Assessment"],
    correctIndex: 0,
    explanation: "Data flow diagrams show the movement and transformation of information, complementing data models that show structure.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-068",
    kaId: "RADD",
    taskId: "RADD-5",
    stem: "Design options should be defined:",
    options: ["As a single recommended option to avoid confusing stakeholders", "As multiple viable alternatives so trade-offs can be assessed before recommending", "Only after the solution has been selected", "Only by the technical architect"],
    correctIndex: 1,
    explanation: "The task is plural by design. Without genuine alternatives there is no trade-off analysis and the recommendation is a foregone conclusion.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-069",
    kaId: "RADD",
    taskId: "RADD-2",
    stem: "Which quality characteristic requires that a requirement be achievable within known constraints of budget, schedule, and technology?",
    options: ["Concise", "Testable", "Feasible", "Atomic"],
    correctIndex: 2,
    explanation: "Feasibility asks whether the requirement can actually be delivered in context. An infeasible requirement wastes downstream effort regardless of how well it is written.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-070",
    kaId: "RADD",
    taskId: "RADD-4",
    stem: "The Information Management Approach is an input to Define Requirements Architecture because it:",
    options: ["Sets how business analysis information will be organised, stored, traced, and reused", "Defines the solution's data model", "Prioritizes the requirements", "Lists the stakeholders who must approve requirements"],
    correctIndex: 0,
    explanation: "The architecture must obey the organising and traceability rules established during planning, which is exactly what the Information Management Approach records.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-071",
    kaId: "RADD",
    taskId: "RADD-6",
    caseStudyId: "CS-005",
    stem: "Cedarview's custom build has the higher projected benefit but the hospital has never delivered software of that scale. How should this affect the recommendation?",
    options: ["It disqualifies the custom option automatically", "It should be raised only after the decision is made", "It is irrelevant; projected benefit decides", "Delivery capability and risk are part of the trade-off assessment and should temper the expected realisable value"],
    correctIndex: 3,
    explanation: "Expected value must be discounted by the probability of achieving it. Organizational capability to deliver is a legitimate and material input to the trade-off.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-072",
    kaId: "RADD",
    taskId: "RADD-1",
    stem: "Which technique is most appropriate for defining the boundary of what is inside and outside the solution?",
    options: ["Survey or Questionnaire", "Metrics and Key Performance Indicators", "Scope Modelling", "Root Cause Analysis"],
    correctIndex: 2,
    explanation: "Scope modelling depicts boundaries — what the solution covers and what lies outside it — which anchors both the requirements architecture and design options.",
    difficulty: "medium",
  },
  {
    id: "Q-RADD-073",
    kaId: "RADD",
    taskId: "RADD-2",
    stem: "During verification, an analyst finds a requirement that cannot be proven satisfied by any observable outcome. Which characteristic does it fail?",
    options: ["Understandable", "Testable", "Concise", "Prioritized"],
    correctIndex: 1,
    explanation: "A requirement must be verifiable through some test, demonstration, inspection, or analysis. Without that, there is no way to know when it has been met.",
    difficulty: "easy",
  },
  {
    id: "Q-RADD-074",
    kaId: "RADD",
    taskId: "RADD-1",
    caseStudyId: "CS-004",
    stem: "Benefits Agency stakeholders describe the claims process differently at each of five offices. Which modelling approach best supports agreeing one future process?",
    options: ["Model the current variants, then facilitate agreement on a single target process model", "Adopt the largest office's process without analysis", "Defer process modelling until after the system is built", "Write separate requirements for each office"],
    correctIndex: 0,
    explanation: "Making variation visible is what allows a deliberate choice of target process. Modelling the differences turns an implicit disagreement into a decidable one.",
    difficulty: "hard",
  },
  {
    id: "Q-RADD-075",
    kaId: "RADD",
    taskId: "RADD-6",
    stem: "After the recommendation is accepted, what most directly connects RADD back to Solution Evaluation?",
    options: ["The design options are re-evaluated after go-live", "The verified requirements are re-verified in production", "The Requirements Architecture becomes the performance baseline", "The potential value used to justify the recommendation becomes the benchmark against which realised performance is later analysed"],
    correctIndex: 3,
    explanation: "Potential Value is an input to Analyze Performance Measures. The value promised at recommendation time is exactly what Solution Evaluation later holds the solution to.",
    difficulty: "hard",
  },
];
