import type { Question } from "../types";

export const rlcmQuestions: Question[] = [
  {
    id: "Q-RLCM-001",
    kaId: "RLCM",
    taskId: "RLCM-1",
    stem: "Which capability does Trace Requirements primarily enable?",
    options: ["Elicitation preparation", "Value measurement", "Stakeholder analysis", "Impact analysis and coverage"],
    correctIndex: 3,
    explanation: "Traceability links requirements to one another, to designs, and to objectives, enabling impact analysis and coverage checks.",
    difficulty: "easy",
  },
  {
    id: "Q-RLCM-002",
    kaId: "RLCM",
    taskId: "RLCM-4",
    caseStudyId: "CS-002",
    stem: "At Northwind, change requests arrive weekly. Before accepting one, the BA should evaluate it for benefit, cost, impact, schedule, and urgency. Which task is this?",
    options: ["Approve Requirements", "Prioritize Requirements", "Assess Requirements Changes", "Maintain Requirements"],
    correctIndex: 2,
    explanation: "Assess Requirements Changes performs impact analysis (benefit, cost, impact, schedule, urgency) on a proposed change.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-003",
    kaId: "RLCM",
    taskId: "RLCM-3",
    stem: "Which is NOT a typical basis for prioritizing requirements in BABOK?",
    options: ["Dependencies", "Alphabetical order", "Regulatory compliance", "Risk"],
    correctIndex: 1,
    explanation: "Bases include benefit, penalty, cost, risk, dependencies, time sensitivity, stability, and regulatory/policy — not alphabetical order.",
    difficulty: "easy",
  },
  {
    id: "Q-RLCM-004",
    kaId: "RLCM",
    taskId: "RLCM-2",
    stem: "Keeping a business rule accurate so it can be reused after the project ends is the purpose of:",
    options: ["Maintain Requirements", "Approve Requirements", "Validate Requirements", "Trace Requirements"],
    correctIndex: 0,
    explanation: "Maintain Requirements retains accuracy/consistency so requirements remain valuable, reusable assets.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-005",
    kaId: "RLCM",
    taskId: "RLCM-5",
    stem: "Which input distinguishes Approve Requirements from the other RLCM tasks?",
    options: ["Needs", "Elicitation Results", "Proposed Change", "Requirements (verified)"],
    correctIndex: 3,
    explanation: "Approve Requirements takes verified requirements as input — approval follows verification.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-006",
    kaId: "RLCM",
    taskId: "RLCM-1",
    stem: "'Requirement A cannot be implemented unless Requirement B is also implemented.' This is which traceability relationship?",
    options: ["Satisfy", "Validate", "Depends", "Derive"],
    correctIndex: 2,
    explanation: "A Depends relationship captures necessity or effort dependencies between requirements.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-007",
    kaId: "RLCM",
    taskId: "RLCM-3",
    caseStudyId: "CS-002",
    stem: "With a fixed go-live date and conflicting requirements, Northwind's BA must continually rank what gets built first. This is:",
    options: ["Maintain Requirements", "Prioritize Requirements", "Trace Requirements", "Verify Requirements"],
    correctIndex: 1,
    explanation: "Prioritize Requirements ranks relative importance and is continual — essential under fixed time constraints.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-008",
    kaId: "RLCM",
    taskId: "RLCM-4",
    stem: "Effective impact analysis of a proposed change depends most directly on having:",
    options: ["Good requirements traceability", "A completed mock exam", "Vendor assessments", "A signed business case"],
    correctIndex: 0,
    explanation: "Traceability (RLCM-1) reveals what a change touches, which is the foundation of impact analysis.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-009",
    kaId: "RLCM",
    taskId: "RLCM-5",
    stem: "Who may approve requirements is determined by:",
    options: ["The Change Strategy", "The Solution Scope", "The Information Management Approach", "The Governance Approach"],
    correctIndex: 3,
    explanation: "The Governance Approach defines decision authority and the approval process.",
    difficulty: "easy",
  },
  {
    id: "Q-RLCM-010",
    kaId: "RLCM",
    taskId: "RLCM-3",
    stem: "In an adaptive (agile) context, prioritization is best described as:",
    options: ["Done once at project start", "Continual, at each iteration", "Handled only by governance", "Unnecessary"],
    correctIndex: 1,
    explanation: "Prioritization is continual; backlogs are re-prioritized frequently as understanding evolves.",
    difficulty: "easy",
  },
  {
    id: "Q-RLCM-011",
    kaId: "RLCM",
    taskId: "RLCM-2",
    stem: "Which requirements are most likely to be maintained for reuse beyond a single initiative?",
    options: ["Status reports", "Transition requirements", "Business rules and non-functional requirements", "Meeting notes"],
    correctIndex: 2,
    explanation: "Stable artifacts like business rules and NFRs often outlive the project and are reused.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-012",
    kaId: "RLCM",
    taskId: "RLCM-1",
    stem: "A requirement states 'the system shall log every KYC decision' because a regulation demands an audit trail. What relationship type links the requirement to the regulation?",
    options: ["Validate", "Necessity", "Satisfy", "Derive"],
    correctIndex: 3,
    explanation: "A derive relationship links a requirement back to the requirement or source it was derived from, typically from a higher level of abstraction such as a regulation or business requirement.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-013",
    kaId: "RLCM",
    taskId: "RLCM-1",
    stem: "A design element implements a stated functional requirement. Which traceability relationship applies?",
    options: ["Satisfy", "Depend", "Validate", "Derive"],
    correctIndex: 0,
    explanation: "Satisfy links an implementation element, such as a design or solution component, to the requirement it fulfils.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-014",
    kaId: "RLCM",
    taskId: "RLCM-1",
    stem: "Requirement B cannot deliver value unless requirement A is also implemented. Which relationship and sub-type is this?",
    options: ["Satisfy", "Depend — necessity", "Depend — effort", "Derive"],
    correctIndex: 1,
    explanation: "A necessity dependency means one requirement is meaningless or valueless without the other. An effort dependency means one merely becomes easier or cheaper if the other is implemented first.",
    difficulty: "hard",
  },
  {
    id: "Q-RLCM-015",
    kaId: "RLCM",
    taskId: "RLCM-1",
    stem: "Implementing requirement A first makes requirement B cheaper to build, but B still delivers value on its own. This is best recorded as:",
    options: ["Derive", "Depend — necessity", "Depend — effort", "Validate"],
    correctIndex: 2,
    explanation: "An effort dependency affects cost or ease of implementation, not whether the requirement is viable. Mislabelling it as necessity would wrongly constrain sequencing.",
    difficulty: "hard",
  },
  {
    id: "Q-RLCM-016",
    kaId: "RLCM",
    taskId: "RLCM-1",
    stem: "The primary business reason for maintaining traceability is to:",
    options: ["Produce a document for the project archive", "Replace the need for requirements verification", "Satisfy auditors regardless of cost", "Support impact analysis, coverage, and consistent change decisions across the requirement set"],
    correctIndex: 3,
    explanation: "Traceability exists to make change manageable — showing coverage, allocation, and what else is affected when something moves. Audit evidence is a by-product, not the purpose.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-017",
    kaId: "RLCM",
    taskId: "RLCM-2",
    stem: "A business rule about overdraft limits applies to three different initiatives across the organization. What should Maintain Requirements enable?",
    options: ["Maintaining the rule so it can be reused across initiatives rather than duplicated", "Archiving the rule once the first initiative closes", "Converting the rule into a design element", "Rewriting the rule separately for each initiative"],
    correctIndex: 0,
    explanation: "Maintain Requirements keeps requirements accurate, consistent, and reusable over time. Requirements reuse is a core element of the task, and duplication is what it prevents.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-018",
    kaId: "RLCM",
    taskId: "RLCM-2",
    stem: "For a requirement to be genuinely reusable across future initiatives, it must primarily be:",
    options: ["Written at a very low level of implementation detail", "Named, clearly defined, and stored at a level of abstraction that is not tied to one initiative's context", "Approved by every stakeholder in the organization", "Assigned the highest priority"],
    correctIndex: 1,
    explanation: "Reusable requirements are context-independent and well defined. Requirements welded to one initiative's implementation detail cannot travel to the next one.",
    difficulty: "hard",
  },
  {
    id: "Q-RLCM-019",
    kaId: "RLCM",
    taskId: "RLCM-3",
    stem: "Which of these is NOT a typical basis for prioritizing requirements in BABOK?",
    options: ["Cost and risk", "Regulatory or policy compliance", "Alphabetical order of requirement titles", "Benefit and penalty"],
    correctIndex: 2,
    explanation: "BABOK lists bases including benefit, penalty, cost, risk, dependencies, time sensitivity, stability, and regulatory or policy compliance. Ordering by title is arbitrary and value-blind.",
    difficulty: "easy",
  },
  {
    id: "Q-RLCM-020",
    kaId: "RLCM",
    taskId: "RLCM-3",
    stem: "A requirement has modest business benefit but a legal deadline in nine weeks. Which prioritization basis most justifies raising it?",
    options: ["Effort dependency", "Benefit", "Time sensitivity and regulatory compliance", "Stability"],
    correctIndex: 2,
    explanation: "Time sensitivity captures value that decays or expires with a date; regulatory compliance captures obligations that are not optional regardless of benefit.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-021",
    kaId: "RLCM",
    taskId: "RLCM-3",
    stem: "Every stakeholder group has marked all of its own requirements as 'must have'. What is the analyst's most effective response?",
    options: ["Accept the rankings and let the delivery team decide", "Facilitate prioritization against agreed, explicit criteria such as value, cost, and risk", "Give each group an equal quota of must-haves", "Escalate to the sponsor to pick winners"],
    correctIndex: 1,
    explanation: "Prioritization is a facilitated, criteria-driven negotiation. Explicit shared criteria convert positional bargaining into a comparison stakeholders can reason about together.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-022",
    kaId: "RLCM",
    taskId: "RLCM-3",
    stem: "Prioritization in BABOK is best characterised as:",
    options: ["Continuous, revisited as context, value, and constraints change", "The sponsor's sole responsibility", "Applicable only to functional requirements", "A one-time activity completed before development starts"],
    correctIndex: 0,
    explanation: "Priorities shift as information emerges and constraints change, so prioritization is ongoing throughout the life cycle rather than a gate passed once.",
    difficulty: "easy",
  },
  {
    id: "Q-RLCM-023",
    kaId: "RLCM",
    taskId: "RLCM-4",
    stem: "Which is the distinguishing input to Assess Requirements Changes, compared with Trace, Maintain, and Prioritize Requirements?",
    options: ["Solution Scope", "Designs", "Requirements", "Proposed Change"],
    correctIndex: 3,
    explanation: "All four tasks take Requirements and Designs. Only Assess Requirements Changes additionally takes the Proposed Change that triggers the assessment.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-024",
    kaId: "RLCM",
    taskId: "RLCM-4",
    stem: "When assessing a proposed change, which set of considerations does BABOK direct the analyst to weigh?",
    options: ["Only the effect on the delivery date", "Only the cost of implementation", "Benefit, cost, impact, urgency, and alignment with the change strategy", "Only whether the sponsor supports it"],
    correctIndex: 2,
    explanation: "Change assessment is multi-dimensional: what it gains, what it costs, what it disturbs, how time-critical it is, and whether it still serves the agreed strategy.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-025",
    kaId: "RLCM",
    taskId: "RLCM-4",
    caseStudyId: "CS-002",
    stem: "At Northwind, a proposed change to the warehouse picking rule would also affect finance reporting and the logistics provider's interface. What must the analyst produce before a decision is made?",
    options: ["An updated Requirements Architecture", "A Requirements Change Assessment covering the traced impacts across affected requirements and designs", "A new Elicitation Activity Plan", "A revised Business Analysis Approach"],
    correctIndex: 1,
    explanation: "Assess Requirements Changes produces the Requirements Change Assessment (and Designs Change Assessment). Traceability is what makes the cross-area impacts visible.",
    difficulty: "hard",
  },
  {
    id: "Q-RLCM-026",
    kaId: "RLCM",
    taskId: "RLCM-4",
    stem: "The output of Assess Requirements Changes is best described as:",
    options: ["A recommendation on the proposed change, for the appropriate decision maker to act on", "An updated solution scope", "A new requirement", "An approved change"],
    correctIndex: 0,
    explanation: "The task assesses and recommends. The decision itself rests with whoever the Governance Approach gives change authority to.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-027",
    kaId: "RLCM",
    taskId: "RLCM-5",
    stem: "Which is the input to Approve Requirements that distinguishes it from the other RLCM tasks?",
    options: ["Requirements (prioritized)", "Proposed Change", "Requirements (traced)", "Requirements (verified)"],
    correctIndex: 3,
    explanation: "Approve Requirements takes Requirements (verified) — quality has already been checked in RADD before stakeholders are asked to commit to them.",
    difficulty: "hard",
  },
  {
    id: "Q-RLCM-028",
    kaId: "RLCM",
    taskId: "RLCM-5",
    stem: "Two stakeholder groups cannot agree on a requirement and approval is blocked. What does Approve Requirements direct the analyst to do?",
    options: ["Let the development team choose an interpretation", "Approve the version supported by the larger group", "Work to resolve the conflict, escalating through the agreed governance path if consensus cannot be reached", "Defer the requirement indefinitely"],
    correctIndex: 2,
    explanation: "Conflict and issue management is an element of the task. The analyst facilitates toward agreement and uses the governance escalation route when agreement is genuinely unreachable.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-029",
    kaId: "RLCM",
    taskId: "RLCM-5",
    stem: "Who has authority to approve requirements?",
    options: ["Always the business analyst", "Whoever the Governance Approach designates for that class of requirement", "The development team lead", "Always the project sponsor"],
    correctIndex: 1,
    explanation: "Approval authority is set during Plan Business Analysis Governance and can differ by requirement type, risk, or domain. It is not fixed to a single role by BABOK.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-030",
    kaId: "RLCM",
    taskId: "RLCM-1",
    stem: "An analyst wants to show that every business requirement has at least one stakeholder requirement beneath it and no orphans exist. What is being examined?",
    options: ["Requirements reuse", "Change impact", "Requirements allocation", "Coverage through the traceability relationships"],
    correctIndex: 3,
    explanation: "Coverage asks whether each requirement is traced up to a source and down to something that satisfies it, exposing orphans and gaps.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-031",
    kaId: "RLCM",
    taskId: "RLCM-2",
    stem: "After go-live, a set of requirements remains valid and describes how the organization operates. What should happen to them?",
    options: ["Maintain them as an ongoing representation of the business for reuse", "Convert them into design elements", "Archive them as read-only project records only", "Delete them, since the initiative has closed"],
    correctIndex: 0,
    explanation: "Requirements that outlive the initiative describe the enterprise, not the project. Maintaining them preserves organizational knowledge and enables reuse.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-032",
    kaId: "RLCM",
    taskId: "RLCM-3",
    stem: "A requirement is highly valuable but its definition keeps changing week to week. Which prioritization basis argues for deferring it?",
    options: ["Benefit", "Stability", "Penalty", "Regulatory compliance"],
    correctIndex: 1,
    explanation: "Stability asks whether a requirement is settled enough to build. Implementing an unstable requirement risks rework that destroys the value it promised.",
    difficulty: "hard",
  },
  {
    id: "Q-RLCM-033",
    kaId: "RLCM",
    taskId: "RLCM-4",
    stem: "A stakeholder insists a change is 'just a small tweak' and should bypass assessment. Which risk does skipping Assess Requirements Changes create?",
    options: ["The requirement will be assigned the wrong owner", "The requirement will be documented at the wrong level of abstraction", "Unseen impacts on traced requirements, designs, and the change strategy go undetected until later and cost more", "The stakeholder will lose engagement"],
    correctIndex: 2,
    explanation: "The purpose of assessment is to surface consequences that are not visible from the change request itself. Size as judged by the requester is not a reliable proxy for impact.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-034",
    kaId: "RLCM",
    taskId: "RLCM-1",
    stem: "In an adaptive initiative using a product backlog, how does BABOK view traceability?",
    options: ["It must use the same formal matrix as predictive initiatives", "It is replaced entirely by acceptance criteria", "It is unnecessary in adaptive approaches", "It still applies, at a level of formality appropriate to the context"],
    correctIndex: 3,
    explanation: "The need to understand relationships and impacts does not disappear with lifecycle. What changes is the formality and the tooling, not the underlying practice.",
    difficulty: "hard",
  },
  {
    id: "Q-RLCM-035",
    kaId: "RLCM",
    taskId: "RLCM-3",
    stem: "Which technique is most directly associated with negotiating relative requirement priority among competing stakeholder groups?",
    options: ["Prioritization", "Data Modelling", "Interface Analysis", "Lessons Learned"],
    correctIndex: 0,
    explanation: "The Prioritization technique provides structured schemes such as ranking, grouping, and timeboxing to compare requirements against agreed criteria.",
    difficulty: "easy",
  },
  {
    id: "Q-RLCM-036",
    kaId: "RLCM",
    taskId: "RLCM-5",
    stem: "Requirements were approved, but two weeks later stakeholders claim they never agreed. Which element of Approve Requirements was most likely weak?",
    options: ["Requirements reuse", "Tracking and communicating the approval so the agreed baseline is unambiguous", "Prioritization criteria", "Traceability relationships"],
    correctIndex: 1,
    explanation: "Approve Requirements includes tracking and communicating approvals. Without a recorded, communicated baseline, agreement is contestable after the fact.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-037",
    kaId: "RLCM",
    taskId: "RLCM-1",
    stem: "Which statement about requirements allocation is most accurate?",
    options: ["Allocation approves requirements for build", "Allocation verifies requirements quality", "Allocation assigns requirements to solution components or releases", "Allocation ranks requirements by business value"],
    correctIndex: 2,
    explanation: "Allocation distributes requirements across solution components and releases so the delivery increments are coherent. Ranking, approval, and verification are separate tasks.",
    difficulty: "medium",
  },
  {
    id: "Q-RLCM-038",
    kaId: "RLCM",
    taskId: "RLCM-4",
    caseStudyId: "CS-002",
    stem: "Northwind's fixed go-live date is immovable and a valuable but large change arrives. Which recommendation best reflects BABOK's change assessment reasoning?",
    options: ["Reject it automatically because the date is fixed", "Implement a partial version without assessing the impact", "Accept it, because business value always outranks schedule", "Assess benefit against cost, impact, and urgency, and recommend deferral to a later release if it endangers the committed scope"],
    correctIndex: 3,
    explanation: "Neither automatic acceptance nor automatic rejection is analysis. The task weighs the change on all dimensions and recommends a course, which may be deferral rather than a binary yes or no.",
    difficulty: "hard",
  },
];
