import type { Question } from "../types";

export const saQuestions: Question[] = [
  {
    id: "Q-SA-001",
    kaId: "SA",
    taskId: "SA-1",
    caseStudyId: "CS-001",
    stem: "Before defining MeridianBank's future onboarding, the BA must establish a baseline of how things work today. Which task produces that baseline?",
    options: ["Define Future State", "Analyze Current State", "Define Change Strategy", "Assess Risks"],
    correctIndex: 1,
    explanation: "Analyze Current State establishes the baseline (capabilities, processes, constraints) against which future state and value are judged.",
    difficulty: "easy",
  },
  {
    id: "Q-SA-002",
    kaId: "SA",
    taskId: "SA-2",
    stem: "Which set are outputs of Define Future State?",
    options: ["Business Objectives, Future State Description, Potential Value", "Change Strategy and Solution Scope", "Risk Analysis Results", "Current State Description and Business Requirements"],
    correctIndex: 0,
    explanation: "Define Future State outputs Business Objectives, the Future State Description, and Potential Value.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-003",
    kaId: "SA",
    taskId: "SA-4",
    stem: "Bridging the current and future states through gap analysis and transition planning is the purpose of:",
    options: ["Analyze Current State", "Define Design Options", "Assess Risks", "Define Change Strategy"],
    correctIndex: 3,
    explanation: "Define Change Strategy uses gap analysis to plan how to move from current to future state, producing the Change Strategy and Solution Scope.",
    difficulty: "easy",
  },
  {
    id: "Q-SA-004",
    kaId: "SA",
    taskId: "SA-2",
    stem: "Future-state business objectives are best written to be:",
    options: ["Confidential", "Aspirational and broad", "SMART (specific, measurable, achievable, relevant, time-bounded)", "Technology-specific"],
    correctIndex: 2,
    explanation: "SMART objectives make the future state measurable and testable.",
    difficulty: "easy",
  },
  {
    id: "Q-SA-005",
    kaId: "SA",
    taskId: "SA-3",
    stem: "An organization that prefers to avoid uncertainty even at higher cost is best described as:",
    options: ["Risk-neutral", "Risk-averse", "Risk-ignorant", "Risk-seeking"],
    correctIndex: 1,
    explanation: "Risk-averse stakeholders prioritize avoiding uncertainty; this shapes which risk responses are acceptable.",
    difficulty: "easy",
  },
  {
    id: "Q-SA-006",
    kaId: "SA",
    taskId: "SA-3",
    stem: "Transferring a risk to a third party (e.g. insurance or a vendor contract) is which response strategy?",
    options: ["Transfer", "Mitigate", "Accept", "Avoid"],
    correctIndex: 0,
    explanation: "Transfer shifts the impact/ownership of a risk to another party.",
    difficulty: "easy",
  },
  {
    id: "Q-SA-007",
    kaId: "SA",
    taskId: "SA-1",
    stem: "Which technique helps separate the root cause of a business problem from its symptoms during current-state analysis?",
    options: ["Backlog Management", "User Stories", "Prototyping", "Root Cause Analysis"],
    correctIndex: 3,
    explanation: "Root Cause Analysis (e.g. five whys, fishbone) distinguishes underlying causes from symptoms.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-008",
    kaId: "SA",
    taskId: "SA-4",
    stem: "Solution Scope is an output of which task?",
    options: ["Analyze Current State", "Define Future State", "Define Change Strategy", "Assess Risks"],
    correctIndex: 2,
    explanation: "Define Change Strategy produces both the Change Strategy and the Solution Scope.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-009",
    kaId: "SA",
    taskId: "SA-2",
    caseStudyId: "CS-001",
    stem: "The MeridianBank sponsor wants onboarding under 1 hour. Where does this measurable target most properly belong?",
    options: ["As a traceability relationship", "As a business objective in the Future State Description", "As a transition requirement", "As a governance rule"],
    correctIndex: 1,
    explanation: "A measurable target for the desired end state is a business objective defined when describing the future state.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-010",
    kaId: "SA",
    taskId: "SA-1",
    stem: "Which are the outputs of Analyze Current State?",
    options: ["Change Strategy and Solution Scope", "Risk Analysis Results and Influences", "Business Objectives and Potential Value", "Current State Description and Business Requirements"],
    correctIndex: 3,
    explanation: "Analyze Current State outputs the Current State Description and Business Requirements.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-011",
    kaId: "SA",
    taskId: "SA-4",
    stem: "Defining intermediate transition states and a release plan is part of which task?",
    options: ["Define Change Strategy", "Maintain Requirements", "Verify Requirements", "Measure Solution Performance"],
    correctIndex: 0,
    explanation: "Transition states and release planning are elements of Define Change Strategy.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-012",
    kaId: "SA",
    taskId: "SA-1",
    stem: "A sponsor states the need as 'we need a new CRM'. What is the analyst's correct first move in Analyze Current State?",
    options: ["Begin evaluating CRM vendors", "Identify the underlying business need and the problem or opportunity the CRM is assumed to address", "Draft requirements for the CRM", "Define the future state architecture"],
    correctIndex: 1,
    explanation: "A named solution is not a need. Analyze Current State establishes the actual problem or opportunity, so the change is not locked to an assumed answer before analysis begins.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-013",
    kaId: "SA",
    taskId: "SA-1",
    stem: "Which pair are the outputs of Analyze Current State?",
    options: ["Business Objectives and Solution Scope", "Needs and Risk Analysis Results", "Current State Description and Business Requirements", "Current State Description and Potential Value"],
    correctIndex: 2,
    explanation: "Analyze Current State produces a description of the present context plus the Business Requirements — the higher-level needs the change must serve.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-014",
    kaId: "SA",
    taskId: "SA-1",
    stem: "Which technique is most directly suited to identifying the underlying cause of a recurring operational problem during current state analysis?",
    options: ["Vendor Assessment", "Prototyping", "Backlog Management", "Root Cause Analysis"],
    correctIndex: 3,
    explanation: "Root Cause Analysis separates symptoms from causes so the change targets the condition producing the problem rather than its visible effects.",
    difficulty: "easy",
  },
  {
    id: "Q-SA-015",
    kaId: "SA",
    taskId: "SA-1",
    stem: "When analysing the current state, which of these is an internal element of the enterprise the analyst examines?",
    options: ["Organizational structure and culture", "Regulatory change in the industry", "Supplier market consolidation", "Competitor pricing"],
    correctIndex: 0,
    explanation: "Internal elements include structure, culture, capabilities, processes, technology, policies, architecture, and assets. Competitors, regulation, and supplier markets are external influences.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-016",
    kaId: "SA",
    taskId: "SA-2",
    stem: "Which business objective is best formed for Define Future State?",
    options: ["Make onboarding faster", "Reduce average account onboarding time from 3 days to under 1 hour by 31 December", "Modernise the onboarding platform", "Improve customer satisfaction"],
    correctIndex: 1,
    explanation: "Business objectives should be specific and measurable with a target and timeframe. The other options state direction without a testable target.",
    difficulty: "easy",
  },
  {
    id: "Q-SA-017",
    kaId: "SA",
    taskId: "SA-2",
    stem: "Which set are the outputs of Define Future State?",
    options: ["Current State Description and Business Requirements", "Risk Analysis Results and Influences", "Business Objectives, Future State Description, Potential Value", "Change Strategy and Solution Scope"],
    correctIndex: 2,
    explanation: "Define Future State produces the measurable objectives, the description of the desired state, and the potential value that reaching it would create.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-018",
    kaId: "SA",
    taskId: "SA-2",
    stem: "Potential Value, as an output of Define Future State, represents:",
    options: ["The cost of the change", "The value confirmed after implementation", "Value already realised by the current solution", "The value that could be realised if the future state is achieved"],
    correctIndex: 3,
    explanation: "Potential value is forward-looking and hypothetical. It later becomes an input to Analyze Performance Measures, where actual performance is compared against it.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-019",
    kaId: "SA",
    taskId: "SA-3",
    stem: "An organization with a strong balance sheet accepts a 30% chance of failure for a chance at market leadership. How is this risk tolerance described?",
    options: ["Risk-seeking", "Risk-transferring", "Risk-aversion", "Risk-neutral"],
    correctIndex: 0,
    explanation: "A risk-seeking stance accepts higher uncertainty in pursuit of higher return. Risk-averse stances prefer certainty even at lower expected value.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-020",
    kaId: "SA",
    taskId: "SA-3",
    stem: "Which of these is NOT typically an output or element considered within Assess Risks?",
    options: ["The final approved solution design", "Unknowns and uncertainties", "Constraints, assumptions, and dependencies", "Risk tolerance of stakeholders"],
    correctIndex: 0,
    explanation: "Assess Risks examines what could reduce or prevent value and produces Risk Analysis Results. Solution design is defined later, in RADD.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-021",
    kaId: "SA",
    taskId: "SA-3",
    stem: "Assess Risks takes Influences as an input. These are:",
    options: ["The stakeholders who influence approval decisions", "The techniques selected for elicitation", "Only internal factors the organization controls", "Internal and external factors that may affect achievement of the business objectives"],
    correctIndex: 3,
    explanation: "Influences are internal and external environmental factors bearing on whether the change can deliver its objectives, not people or method choices.",
    difficulty: "hard",
  },
  {
    id: "Q-SA-022",
    kaId: "SA",
    taskId: "SA-4",
    stem: "Which pair are the outputs of Define Change Strategy?",
    options: ["Business Requirements and Needs", "Risk Analysis Results and Influences", "Change Strategy and Solution Scope", "Future State Description and Potential Value"],
    correctIndex: 2,
    explanation: "Define Change Strategy produces both the strategy for moving from current to future state and the Solution Scope that bounds what the solution will cover.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-023",
    kaId: "SA",
    taskId: "SA-4",
    stem: "A change will take 18 months, but the organization needs partial benefit sooner and cannot absorb one large cutover. What should the change strategy define?",
    options: ["A single big-bang release at month 18", "Transition states and a release plan delivering value incrementally", "A longer elicitation phase", "A revised set of business objectives"],
    correctIndex: 1,
    explanation: "Transition states are interim states the enterprise passes through when the future state cannot be reached in one step. Release planning sequences the value delivery.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-024",
    kaId: "SA",
    taskId: "SA-4",
    stem: "Gap analysis within Define Change Strategy compares:",
    options: ["The current state capabilities against those required by the future state", "Planned against actual project spend", "Requirements against their test cases", "Two competing vendor products"],
    correctIndex: 0,
    explanation: "The gap is the set of capabilities the enterprise lacks today but needs in the future state. That gap is what the change strategy must close.",
    difficulty: "easy",
  },
  {
    id: "Q-SA-025",
    kaId: "SA",
    taskId: "SA-4",
    stem: "Enterprise readiness assessment within Define Change Strategy determines whether the organization:",
    options: ["Has selected a vendor", "Has verified its requirements", "Has approved the budget", "Is capable of making the change and sustaining it once made"],
    correctIndex: 3,
    explanation: "Readiness covers capacity, capability, and willingness to absorb and hold the change. A technically sound change that the enterprise cannot sustain will not deliver value.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-026",
    kaId: "SA",
    taskId: "SA-2",
    stem: "Which statement best describes the relationship between solution scope and the future state?",
    options: ["Solution scope is defined before the future state", "They are identical", "The future state describes the whole desired end condition; solution scope bounds what this particular solution will deliver toward it", "Solution scope is broader than the future state"],
    correctIndex: 2,
    explanation: "The future state may require organizational, process, and policy change beyond any one solution. Solution scope carves out what this solution is responsible for.",
    difficulty: "hard",
  },
  {
    id: "Q-SA-027",
    kaId: "SA",
    taskId: "SA-3",
    stem: "During risk assessment, the analyst finds a critical assumption that the logistics partner will expose an API by Q3. How should this be handled?",
    options: ["Record it as a requirement", "Record it as an assumption with an associated risk, and plan a response if it does not hold", "Ignore it, since it is outside the organization's control", "Treat it as a confirmed dependency needing no further attention"],
    correctIndex: 1,
    explanation: "Assumptions and dependencies are explicitly in scope for Assess Risks. Being outside the organization's control raises the risk rather than excusing it from analysis.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-028",
    kaId: "SA",
    taskId: "SA-1",
    stem: "Which technique best supports assessing an organization's internal strengths and weaknesses alongside external opportunities and threats during current state analysis?",
    options: ["SWOT Analysis", "Data Flow Diagrams", "Item Tracking", "Acceptance and Evaluation Criteria"],
    correctIndex: 0,
    explanation: "SWOT Analysis structures internal and external factors into a single view, making it a natural fit for framing the current state and its influences.",
    difficulty: "easy",
  },
  {
    id: "Q-SA-029",
    kaId: "SA",
    taskId: "SA-2",
    stem: "Which technique is most directly used to describe what the enterprise must be able to do in the future state, independent of how it will be done?",
    options: ["Prototyping", "Interface Analysis", "Survey or Questionnaire", "Business Capability Analysis"],
    correctIndex: 3,
    explanation: "Capability analysis expresses the enterprise's abilities without prescribing process or technology, which keeps the future state solution-agnostic.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-030",
    kaId: "SA",
    taskId: "SA-4",
    caseStudyId: "CS-001",
    stem: "MeridianBank must keep every account passing KYC/AML checks while cutting onboarding to under an hour. In the change strategy, the compliance requirement is best treated as:",
    options: ["A risk to be accepted", "A constraint that bounds the solution space", "An assumption to be validated later", "A business objective"],
    correctIndex: 1,
    explanation: "A non-negotiable regulatory obligation limits what solutions are permissible. It is a constraint, not a target to optimise or a proposition to test.",
    difficulty: "hard",
  },
  {
    id: "Q-SA-031",
    kaId: "SA",
    taskId: "SA-3",
    stem: "The output of Assess Risks is:",
    options: ["Solution Limitations", "A risk register maintained by the project manager", "Risk Analysis Results", "The Change Strategy"],
    correctIndex: 2,
    explanation: "Assess Risks produces Risk Analysis Results, which then feed Define Change Strategy alongside the current and future state descriptions.",
    difficulty: "easy",
  },
  {
    id: "Q-SA-032",
    kaId: "SA",
    taskId: "SA-1",
    stem: "Business Requirements, produced by Analyze Current State, are best characterised as:",
    options: ["The needs of individual stakeholder groups", "Constraints imposed by the technology platform", "Detailed functional specifications for the solution", "Statements of goals and outcomes the enterprise seeks, at a high level of abstraction"],
    correctIndex: 3,
    explanation: "Business requirements sit at the enterprise level. Stakeholder requirements express group needs; solution requirements express what the solution must do.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-033",
    kaId: "SA",
    taskId: "SA-4",
    stem: "The organization must choose between a phased rollout by region and a single enterprise-wide cutover. Which technique most directly supports this choice?",
    options: ["Decision Analysis", "Glossary", "Data Modelling", "Observation"],
    correctIndex: 0,
    explanation: "Decision Analysis provides a structured way to compare options against defined criteria and trade-offs, which is exactly the shape of a rollout strategy choice.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-034",
    kaId: "SA",
    taskId: "SA-2",
    stem: "A stakeholder proposes a future state that would require capabilities the organization has no realistic path to acquire. What should the analyst do?",
    options: ["Document it as the agreed future state anyway", "Surface the capability gap and readiness implications so the future state or the change strategy can be adjusted", "Remove the stakeholder from the initiative", "Defer the issue to Solution Evaluation"],
    correctIndex: 1,
    explanation: "A future state the enterprise cannot reach produces no value. The gap and readiness findings are fed back so either the ambition or the route to it is revised.",
    difficulty: "hard",
  },
  {
    id: "Q-SA-035",
    kaId: "SA",
    taskId: "SA-3",
    stem: "Risk Analysis Results are an input to which task?",
    options: ["Conduct Elicitation", "Measure Solution Performance", "Define Change Strategy", "Analyze Current State"],
    correctIndex: 2,
    explanation: "Define Change Strategy consumes the Current State Description, Future State Description, Risk Analysis Results, and Stakeholder Engagement Approach.",
    difficulty: "medium",
  },
  {
    id: "Q-SA-036",
    kaId: "SA",
    taskId: "SA-2",
    stem: "Which technique is most appropriate for presenting the justification for a proposed change, including costs, benefits, and alternatives, to decision makers?",
    options: ["Item Tracking", "Functional Decomposition", "Glossary", "Business Cases"],
    correctIndex: 3,
    explanation: "A business case assembles the need, options, costs, benefits, and risks into a single argument for the decision, drawing on the strategy analysis outputs.",
    difficulty: "easy",
  },
  {
    id: "Q-SA-037",
    kaId: "SA",
    taskId: "SA-4",
    caseStudyId: "CS-002",
    stem: "Northwind must keep the existing inventory module running while the new ERP component is introduced across warehouses. What does this most clearly require the change strategy to define?",
    options: ["Transition states in which both old and new capabilities coexist, with the conditions for moving between them", "A new set of business objectives", "A single cutover on the fixed go-live date", "A revised Business Analysis Approach"],
    correctIndex: 0,
    explanation: "When the enterprise cannot jump from current to future state in one move, the strategy defines interim transition states and the criteria for progressing through them.",
    difficulty: "hard",
  },
];
