import type { Question } from "../types";

export const seQuestions: Question[] = [
  {
    id: "Q-SE-001",
    kaId: "SE",
    taskId: "SE-1",
    stem: "Defining and collecting measures to evaluate a solution's effectiveness is:",
    options: ["Analyze Performance Measures", "Measure Solution Performance", "Assess Solution Limitations", "Recommend Actions to Increase Solution Value"],
    correctIndex: 1,
    explanation: "Measure Solution Performance defines, validates, and collects performance measures tied to objectives.",
    difficulty: "easy",
  },
  {
    id: "Q-SE-002",
    kaId: "SE",
    taskId: "SE-4",
    caseStudyId: "CS-003",
    stem: "BrightMart's loyalty app works fine, but store staff don't promote it and adoption is low. This shortfall is best classified as a:",
    options: ["Enterprise limitation", "Requirements defect", "Traceability gap", "Solution limitation"],
    correctIndex: 0,
    explanation: "The solution itself functions; the limit is in the enterprise (staff behavior/adoption) — an enterprise limitation.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-003",
    kaId: "SE",
    taskId: "SE-3",
    stem: "A defect inside the deployed solution that caps the value delivered is a:",
    options: ["Business requirement", "Transition requirement", "Enterprise limitation", "Solution limitation"],
    correctIndex: 3,
    explanation: "Factors internal to the solution that restrict value are solution limitations.",
    difficulty: "easy",
  },
  {
    id: "Q-SE-004",
    kaId: "SE",
    taskId: "SE-2",
    stem: "Comparing actual performance against potential value to spot trends and variances is:",
    options: ["Define Future State", "Measure Solution Performance", "Analyze Performance Measures", "Assess Enterprise Limitations"],
    correctIndex: 2,
    explanation: "Analyze Performance Measures interprets the collected data against expected value.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-005",
    kaId: "SE",
    taskId: "SE-3",
    caseStudyId: "CS-003",
    stem: "BrightMart discovers a key promotion rule was never configured in the app. In SE terms this missing configuration is a:",
    options: ["Enterprise limitation", "Solution limitation", "Risk response", "Governance gap"],
    correctIndex: 1,
    explanation: "A missing configuration inside the solution that caps value is a solution limitation.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-006",
    kaId: "SE",
    taskId: "SE-5",
    stem: "Which is a valid recommended action to increase solution value in BABOK?",
    options: ["Retire the solution", "Skip governance", "Remove traceability", "Ignore the measures"],
    correctIndex: 0,
    explanation: "Options include do nothing, organizational change, reduce complexity, eliminate redundancy/waste, add capabilities, or retire the solution.",
    difficulty: "easy",
  },
  {
    id: "Q-SE-007",
    kaId: "SE",
    taskId: "SE-1",
    stem: "Solution performance measures should be tied most closely to:",
    options: ["The project schedule", "Stakeholder seniority", "Vendor SLAs only", "The business objectives / potential value"],
    correctIndex: 3,
    explanation: "Measures should reflect the value/objectives the solution was meant to deliver.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-008",
    kaId: "SE",
    taskId: "SE-5",
    caseStudyId: "CS-003",
    stem: "Given low adoption (enterprise) and a missing rule (solution), what should BrightMart's BA deliver to leadership?",
    options: ["A traceability matrix", "A new Stakeholder Engagement Approach", "Recommended Actions addressing each limitation", "A revised Elicitation Activity Plan"],
    correctIndex: 2,
    explanation: "Recommend Actions to Increase Solution Value ties recommendations to the specific solution and enterprise limitations found.",
    difficulty: "hard",
  },
  {
    id: "Q-SE-009",
    kaId: "SE",
    taskId: "SE-4",
    stem: "Inputs to Assess Enterprise Limitations include the Current State Description and:",
    options: ["Business Analysis Approach", "Solution Performance Analysis", "Elicitation Activity Plan", "Governance Approach"],
    correctIndex: 1,
    explanation: "Assess Enterprise Limitations uses the Current State Description, the Solution Performance Analysis, and the implemented solution.",
    difficulty: "hard",
  },
  {
    id: "Q-SE-010",
    kaId: "SE",
    taskId: "SE-2",
    stem: "The output of Analyze Performance Measures is:",
    options: ["Recommended Actions", "Enterprise Limitation", "Solution Performance Measures", "Solution Performance Analysis"],
    correctIndex: 3,
    explanation: "Analyze Performance Measures produces the Solution Performance Analysis, which feeds the limitation-assessment tasks.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-011",
    kaId: "SE",
    taskId: "SE-1",
    stem: "Which pair are the inputs to Measure Solution Performance?",
    options: ["Business Objectives and the Implemented Solution", "Potential Value and Solution Performance Measures", "Current State Description and Solution Performance Analysis", "Enterprise Limitation and Solution Limitation"],
    correctIndex: 0,
    explanation: "Measurement needs something to measure (the implemented solution) and a standard to measure against (the business objectives defined in Strategy Analysis).",
    difficulty: "medium",
  },
  {
    id: "Q-SE-012",
    kaId: "SE",
    taskId: "SE-1",
    stem: "An organization launched a solution with no agreed measures of success. What is the analyst's first step in Measure Solution Performance?",
    options: ["Declare the solution a failure", "Establish measures traceable to the business objectives the change was meant to serve", "Survey users on whether they like the solution", "Begin recommending improvements immediately"],
    correctIndex: 1,
    explanation: "Performance is meaningless without a standard. Measures are defined from the business objectives so that performance can be judged against intended value rather than opinion.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-013",
    kaId: "SE",
    taskId: "SE-1",
    stem: "Which technique is most directly associated with defining what will be measured and the thresholds for acceptable solution performance?",
    options: ["Data Flow Diagrams", "Stakeholder List, Map, or Personas", "Metrics and Key Performance Indicators", "Brainstorming"],
    correctIndex: 2,
    explanation: "Metrics and KPIs establish quantifiable measures and their targets, making performance assessable rather than anecdotal.",
    difficulty: "easy",
  },
  {
    id: "Q-SE-014",
    kaId: "SE",
    taskId: "SE-2",
    stem: "Analyze Performance Measures compares actual performance against:",
    options: ["The project budget", "The original requirements count", "Competitor benchmarks only", "The potential value identified during Strategy Analysis"],
    correctIndex: 3,
    explanation: "Potential Value is an explicit input. The analysis asks whether the value that was projected is actually being realised.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-015",
    kaId: "SE",
    taskId: "SE-3",
    stem: "A solution is missing a business rule that was in the approved requirements. This is best classified as:",
    options: ["A solution limitation", "A risk", "A constraint", "An enterprise limitation"],
    correctIndex: 0,
    explanation: "Anything inside the solution boundary that prevents it from delivering expected value — defects, missing function, poor performance — is a solution limitation.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-016",
    kaId: "SE",
    taskId: "SE-4",
    stem: "A solution works exactly as specified, but staff have not been trained and continue using the legacy process. This is best classified as:",
    options: ["A solution limitation", "An enterprise limitation", "A defect", "A design flaw"],
    correctIndex: 1,
    explanation: "The constraint sits outside the solution, in the organization's readiness, skills, and behaviour. That is the defining test for an enterprise limitation.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-017",
    kaId: "SE",
    taskId: "SE-4",
    stem: "Which input distinguishes Assess Enterprise Limitations from Assess Solution Limitations?",
    options: ["Solution Performance Analysis", "Implemented Solution", "Current State Description", "Business Objectives"],
    correctIndex: 2,
    explanation: "Both tasks take the implemented solution and the performance analysis. Only Assess Enterprise Limitations also takes the Current State Description, because the constraint lies in the enterprise.",
    difficulty: "hard",
  },
  {
    id: "Q-SE-018",
    kaId: "SE",
    taskId: "SE-5",
    stem: "Which pair are the inputs to Recommend Actions to Increase Solution Value?",
    options: ["Business Objectives and Potential Value", "Solution Performance Measures and Current State Description", "Implemented Solution and Requirements", "Enterprise Limitation and Solution Limitation"],
    correctIndex: 3,
    explanation: "Recommendations are built directly on the two limitation outputs, so every recommended action traces to an identified limitation.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-019",
    kaId: "SE",
    taskId: "SE-5",
    stem: "Which of these is a legitimate recommended action under Recommend Actions to Increase Solution Value?",
    options: ["Retire the solution", "Re-run the elicitation phase", "Re-approve the original requirements", "Re-baseline the project schedule"],
    correctIndex: 0,
    explanation: "Recommendations include adjusting the solution, changing the organization, reducing complexity, eliminating redundancy or waste, doing nothing, and retiring the solution.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-020",
    kaId: "SE",
    taskId: "SE-5",
    stem: "Analysis shows the solution performs adequately and the cost of any improvement exceeds its benefit. What is the appropriate recommendation?",
    options: ["Recommend taking no action, with the supporting analysis", "Recommend retiring the solution", "Recommend restructuring the department", "Always recommend an enhancement to show progress"],
    correctIndex: 0,
    explanation: "'Do nothing' is a valid, evidence-backed recommendation. Recommending change that costs more than it returns destroys value rather than adding it.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-021",
    kaId: "SE",
    taskId: "SE-1",
    stem: "Solution Evaluation in BABOK applies:",
    options: ["Only to software solutions", "Only when a solution has failed", "Only after the solution is fully implemented in production", "Throughout the life cycle, including to prototypes, increments, and proposed designs"],
    correctIndex: 3,
    explanation: "Value can be assessed at any point — an early increment or a design option can be evaluated before full implementation. Post-go-live is a common case, not the only one.",
    difficulty: "hard",
  },
  {
    id: "Q-SE-022",
    kaId: "SE",
    taskId: "SE-2",
    stem: "The Solution Performance Analysis is an input to which tasks?",
    options: ["Define Future State and Assess Risks", "Trace Requirements and Approve Requirements", "Assess Solution Limitations and Assess Enterprise Limitations", "Measure Solution Performance and Recommend Actions"],
    correctIndex: 2,
    explanation: "The analysis of how the solution is performing feeds both limitation assessments, which in turn feed the recommendations.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-023",
    kaId: "SE",
    taskId: "SE-3",
    stem: "Users report the solution is slow at month-end, degrading beyond its agreed response threshold. This is best assessed as:",
    options: ["An enterprise limitation, since month-end volume is a business pattern", "A solution limitation, since the solution fails to meet a non-functional requirement under expected load", "A change request outside Solution Evaluation", "A risk that has not yet occurred"],
    correctIndex: 1,
    explanation: "Failure to meet an agreed non-functional requirement under anticipated conditions is a shortcoming of the solution itself, regardless of what drives the volume.",
    difficulty: "hard",
  },
  {
    id: "Q-SE-024",
    kaId: "SE",
    taskId: "SE-4",
    stem: "Which of these is most likely an enterprise limitation rather than a solution limitation?",
    options: ["A policy requiring two manual approvals that negates the automated workflow's speed gain", "An integration that drops records under load", "A calculation error in the pricing engine", "A screen that fails validation on valid input"],
    correctIndex: 0,
    explanation: "A policy sits outside the solution boundary. The software may work perfectly while an organizational rule prevents the value from being realised.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-025",
    kaId: "SE",
    taskId: "SE-2",
    stem: "Performance data shows the solution delivers 60% of projected value. Before recommending action, the analyst should:",
    options: ["Revise the original potential value estimate downward", "Escalate to the sponsor without further analysis", "Recommend replacing the solution", "Determine whether the shortfall stems from solution limitations, enterprise limitations, or both"],
    correctIndex: 3,
    explanation: "Recommendations must trace to causes. Acting on a value gap without identifying whether the constraint is inside or outside the solution risks fixing the wrong thing.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-026",
    kaId: "SE",
    taskId: "SE-1",
    stem: "Business Objectives are used in Measure Solution Performance to:",
    options: ["Approve the solution for release", "Define the solution's technical architecture", "Provide the basis against which solution performance is judged", "Prioritize the remaining backlog"],
    correctIndex: 2,
    explanation: "Objectives set from Strategy Analysis are the yardstick. This is why measurable objectives defined early make evaluation possible later.",
    difficulty: "easy",
  },
  {
    id: "Q-SE-027",
    kaId: "SE",
    taskId: "SE-5",
    caseStudyId: "CS-003",
    stem: "At BrightMart, staff are not promoting the loyalty app and a promotion rule was never configured. How should the recommendations be structured?",
    options: ["A single recommendation to rebuild the app", "Separate recommendations addressing the enterprise limitation (staff adoption) and the solution limitation (unconfigured rule)", "One recommendation to retire the feature", "A recommendation to re-run Strategy Analysis from the beginning"],
    correctIndex: 1,
    explanation: "Two distinct limitation types call for two distinct responses — an organizational change for adoption and a solution adjustment for the rule. Conflating them mistreats both.",
    difficulty: "hard",
  },
  {
    id: "Q-SE-028",
    kaId: "SE",
    taskId: "SE-3",
    stem: "Which technique most directly supports determining whether a solution meets the conditions stakeholders agreed it must satisfy?",
    options: ["Acceptance and Evaluation Criteria", "Organizational Modelling", "Interviews", "Glossary"],
    correctIndex: 0,
    explanation: "Acceptance and evaluation criteria state the conditions a solution must meet, giving an explicit test for whether it is delivering as agreed.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-029",
    kaId: "SE",
    taskId: "SE-4",
    stem: "An analyst finds that two departments each maintain their own copy of customer data, undermining the new single-view solution. This is:",
    options: ["A traceability failure", "A prioritization failure", "A solution limitation requiring a software fix", "An enterprise limitation rooted in organizational structure and data ownership"],
    correctIndex: 3,
    explanation: "The obstruction is organizational — how the enterprise is structured and who owns data — not a shortcoming of the delivered solution.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-030",
    kaId: "SE",
    taskId: "SE-5",
    stem: "Which recommended action would be appropriate when analysis shows several overlapping systems performing the same function?",
    options: ["Retire the solution entirely", "Eliminate redundancy across the overlapping capabilities", "Do nothing", "Re-run Define Design Options"],
    correctIndex: 1,
    explanation: "Eliminating redundancy is an explicit recommendation category, targeted at duplicated capability that adds cost without adding value.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-031",
    kaId: "SE",
    taskId: "SE-2",
    stem: "Which statement best distinguishes Measure Solution Performance from Analyze Performance Measures?",
    options: ["They produce the same output", "Measurement occurs only pre-implementation; analysis only post-implementation", "Measurement collects the data; analysis interprets it against expected value", "Measurement interprets results; analysis collects the data"],
    correctIndex: 2,
    explanation: "SE-1 defines and gathers measures; SE-2 interprets them against potential value to produce the Solution Performance Analysis.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-032",
    kaId: "SE",
    taskId: "SE-5",
    stem: "Recommended Actions should be accompanied by:",
    options: ["A new requirements baseline", "An updated stakeholder map", "A detailed technical design", "The rationale linking each action to the limitation it addresses and the value it would recover"],
    correctIndex: 3,
    explanation: "Decision makers need the chain from evidence to limitation to action to expected value. Recommendations without that chain cannot be evaluated.",
    difficulty: "medium",
  },
  {
    id: "Q-SE-033",
    kaId: "SE",
    taskId: "SE-1",
    stem: "Stakeholders disagree on whether a solution is successful: operations cite faster processing, finance cites unchanged cost. What does this most indicate?",
    options: ["Performance measures were not agreed against shared business objectives before implementation", "Finance is using the wrong data", "The solution should be retired", "The solution has failed"],
    correctIndex: 0,
    explanation: "Competing success narratives usually signal that measures were never anchored to agreed objectives. Without that anchor, each group measures what it values.",
    difficulty: "hard",
  },
  {
    id: "Q-SE-034",
    kaId: "SE",
    taskId: "SE-3",
    caseStudyId: "CS-003",
    stem: "BrightMart's app has no major defects and works as designed, yet delivers 4% lift against a 15% target. What does this pattern most strongly suggest?",
    options: ["The solution limitations are severe", "The primary constraints are likely enterprise limitations rather than solution limitations", "The business objectives were correctly set", "The measures are invalid"],
    correctIndex: 1,
    explanation: "When the solution performs as designed but value does not materialise, the obstruction is usually outside the solution — adoption, process, incentives, or configuration ownership.",
    difficulty: "hard",
  },
  {
    id: "Q-SE-035",
    kaId: "SE",
    taskId: "SE-5",
    stem: "Leadership asks whether to invest further in an underperforming solution. Which BABOK task produces the answer?",
    options: ["Assess Requirements Changes", "Define Change Strategy", "Recommend Actions to Increase Solution Value", "Analyze Potential Value and Recommend Solution"],
    correctIndex: 2,
    explanation: "SE-5 addresses an implemented solution and recommends how to increase its value. RADD-6 recommends among design options before implementation.",
    difficulty: "medium",
  },
];
